#!/bin/bash

# Include script setup file
	source script-setup
	if [ ! $FUNCTIONS_ARE_DEFINED ]; then echo $0: Functions not defined. Aborting; logger $0: Functions not defined. Aborting; exit 1; fi
	if [ ! $VARIABLES_ARE_DEFINED ]; then echo $0: Variables not defined. Aborting; logger $0: Variables not defined. Aborting; exit 1; fi

# Require root
	f_require_root

# Run apt updates
	f_run_apt_updates

# NOTE: IPv4 Public Address is in IPV4_PUBLIC_ADDRESS

# NOTES about installation tutorials
#
# https://www.cyberciti.biz/faq/ubuntu-20-04-lts-set-up-openvpn-server-in-5-minutes/
#   June 16, 2020
#   The problem I have with this is the installation script you have to download from them (openvpn-ubuntu-install.sh).
# https://www.digitalocean.com/community/tutorials/how-to-set-up-and-configure-an-openvpn-server-on-ubuntu-20-04
#   May 6, 2020


# Abandoned code fragment from cyerciti.biz installation tutorial
# Following https://www.cyberciti.biz/faq/ubuntu-20-04-lts-set-up-openvpn-server-in-5-minutes/
# apt-get-update-if-needed && apt-get --yes install ca-certificates wget net-tools gnupg
# wget -qO - https://as-repository.openvpn.net/as-repo-public.gpg | apt-key add -
# echo "deb http://as-repository.openvpn.net/as/debian $UBUNTU_CODENAME main">/etc/apt/sources.list.d/openvpn-as-repo.list
# apt update && apt --yes install openvpn-as
# apt-get install --yes openvpn

# Include script footer file
	f_debug_variable "script_footer" "${PATHNAME[script_footer]}"
	source "${PATHNAME[script_footer]}"

exit 0
