#!/bin/bash

echo "I don't do anything yet."

exit 0

#################################################################################################
##### Optional Modules (move up to use) #########################################################
#################################################################################################
exit 1

# Require root
if [[ $EUID -ne 0 ]]; then
  echo "Root priviletes required." >&2
  exit 163
  fi


echo "This is a test" | mail -s "subject 1" -A ~/.bash* lane@lanehensley.org


