#!/bin/bash

# Include script setup file
	source script-setup
	if [ ! $FUNCTIONS_ARE_DEFINED ]; then echo $0: Functions not defined. Aborting; logger $0: Functions not defined. Aborting; exit 1; fi
	if [ ! $VARIABLES_ARE_DEFINED ]; then echo $0: Variables not defined. Aborting; logger $0: Variables not defined. Aborting; exit 1; fi

# Require root
	f_require_root

# Do the work
	# NOTE: Recommend leaving the f_balk command below until this script no longer is called by other scripts.
	# When it's time, you may want to leave the script intact so it can be invoked from the command line, but drop the balk warning below.
	f_balk "DEPRICATED. Source _functions and call f_apply_permissions. For now, running it anyway." false
	f_apply_permissions

# Include script footer file
	f_debug_variable "script_footer" "${PATHNAME[script_footer]}"
	source "${PATHNAME[script_footer]}"

exit 0
