#!/bin/bash
# _apply-permissions

# Invoked by _apply-configs

# Include script setup file
	source script-setup
	if [ ! $FUNCTIONS_ARE_DEFINED ]; then echo $0: Functions not defined. Aborting; logger $0: Functions not defined. Aborting; fi
	if [ ! $VARIABLES_ARE_DEFINED ]; then echo $0: Variables not defined. Aborting; logger $0: Variables not defined. Aborting; fi

# Set ownership and permissions in $SBIN_DIR
	chown -R $ROOT_USER:$ROOT_USER $SBIN_DIR
	find $SBIN_DIR -type d -print -exec chmod 700 {} \; >> /dev/null 2>&1
	find $SBIN_DIR -type f -print -exec chmod 770 {} \; >> /dev/null 2>&1

# Exceptions: These can be read or run by anyone
	# These based on functional requirements
		chmod 755 ${PATHNAME[currenttimeinseconds]}
		chmod 755 ${PATHNAME[intervalinseconds]}
		chmod 755 ${PATHNAME[lhlib]}
		chmod 755 ${PATHNAME[process_incoming_scans]}
		chmod 755 ${PATHNAME[rip]}
		chmod 755 ${PATHNAME[script_footer]} 
		chmod 755 ${PATHNAME[script_setup]} 
		chmod 755 ${PATHNAME[timeformat]}
		chmod 755 ${PATHNAME[transcode_ripped_dvds]}
	# These based on desire. CAUTION: Don't expose anything that has a password or code in it.
		chmod 740 ${PATHNAME[upd]} 
		chmod 740 ${PATHNAME[_apply_configs]}

# ddclient
	chmod 600 /etc/ddclient.conf /etc/default/declient
	chown $ROOT_USER:$ROOT_USER /etc/ddclient.conf /etc/default/declient

# Git
	chmod 600 $ROOT_HOME_DIR/.gitconfig
	chmod 600 $ADMIN_HOME_DIR/.gitconfig
	chown $ROOT_USER:$ROOT_USER $ROOT_HOME_DIR/.gitconfig
	chown $ADMIN_USER:$ADMIN_USER $ADMIN_HOME_DIR/.gitconfig
	chmod -R 400 $GIT_ROOT

# fstab
	chown $ROOT_USER:$ROOT_USER /etc/fstab*
	chmod 664 /etc/fstab*

# lsyncd
	chown $ROOT_USER:$ROOT_USER /etc/lsyncd/lsyncd.conf.lua
	chmod 600 /etc/lsyncd/lsyncd.conf.lua

# resolvconf
	chown $ROOT_USER:$ROOT_USER /etc/resolvconf/resolv.conf.d/head
	chmod 644 /etc/resolvconf/resolv.conf.d/head

# .ssh/authorized_keys
	chown -R $ADMIN_USER:$ADMIN_USER $ADMIN_HOME_DIR/.ssh
	chown -R $ROOT_USER:$ROOT_USER $ROOT_HOME_DIR/.ssh
	chmod -R 600 $ADMIN_HOME_DIR/.ssh $ROOT_HOME_DIR/.ssh

# SSHD config file
	chmod 644 "$SSHD_CONFIG"
	chown $ROOT_USER:$ROOT_USER "$SSHD_CONFIG"

# HandBrake config file
	chmod -R 600 $ADMIN_HOME_DIR/.HandBrake/*
	chown -R $ADMIN_USER:$ADMIN_USER $ADMIN_HOME_DIR/.HandBrake $ADMIN_HOME_DIR/Videos
	chown -R $ROOT_USER:$ROOT_USER $ROOT_HOME_DIR/.HandBrake

# Vim and vi config files
	chmod 600 $ADMIN_HOME_DIR/.vim*
	chown $ADMIN_USER:$ADMIN_USER $ADMIN_HOME_DIR/.vim*
	chown $ROOT_USER:$ROOT_USER $ROOT_HOME_DIR/.vim*

# Include script footer file
	f_debug_variable "script_footer" "${PATHNAME[script_footer]}"
	source "${PATHNAME[script_footer]}"

exit 0

