#!/bin/bash


###################################################
# Notes
#
# "getopts" is built into shell, which makes it run faster then "getopt", which is an external command
# But "getopts" does not support long command line arguments (e.g., shellscriptname --argument=value)
# STRONG RECOMMENDATION: Use getopt and not getopts
# Following tutorial at https://www.shellscript.sh/tips/getopt/
# man page for getopt is at https://man7.org/linux/man-pages/man1/getopt.1.html
# Defining terms
#    argument: any text appended to a command (syn.: parameter)
#    parameter: synonym for argument
#    option: a command argument preceded by a single or double hyphen (e.g., -o, or --option)
#       An option may have an argument of its own (an "option argument", e.g., -o value-o, or --option value-o, or --option=value-o)
#       All options are arguments, but not all arguments are options.
#    short option: an option consisting of single hyphen and letter, with or without an option argument specified (e.g., -a value-a -b)
#    long option: an option consisting of a double hyphen and word, with or without an option argument specified (e.g., --arga value-a --argb=value-b --argc)
#    switch: a short or long option, with no option argument specified (e.g., -a --argb)
#       All switches are options, but not all options are switches.
#    remaining arguments: command line arguments that are neither options nor option arguments


###################################################
# Basic Setup

# Include script setup file
	source script-setup
	if [ ! $FUNCTIONS_ARE_DEFINED ]; then echo $0: Functions not defined. Aborting; logger $0: Functions not defined. Aborting; exit 61; fi
	if [ ! $VARIABLES_ARE_DEFINED ]; then echo $0: Variables not defined. Aborting; logger $0: Variables not defined. Aborting; exit 61; fi

# Uncomment requirements for script execution
	f_require_root
    # f_require_ubuntu
    # f_deprecated
    # f_require_minimum_version_number "version-number"
    # f_require_maximum_version_number "version-number"
    # f_only_on_server "hostname"
    # f_require_confirmation "This text is displayed, requesting confirmation word." "ConfirmationWord"
    # set -x # For debugging


###################################################
# Functions

function f_print_usage {
  echo
  echo Usage: $(basename "$0") [-pqVv -set-plex-file-permissions --quiet --verbose --version --help]
  echo "Version $VERSION_NUMBER"
  echo Apply configureations and selected permissions on local system.
  echo Requires root or sudo.
  echo
  echo "Options:"
  echo "  -p --set-plex-file-permissions    Updates Plex Media Server file permissions globally. May take a while."
  echo "  -q --quiet                        Mimimal output"
  echo "  -V --verbose                      Verbose output"
  echo "  -v --version                      Display version number, then exit (no other options processed)"
  echo "  --help                            Display usage and help information, then exit (no other options processed)"
  echo
  echo "Example usage: " [sudo] $(basename "$0") --set-plex-file-permissions
  echo
  # Describe any exit codes returned. For examples below, comment out any unused values. EXAMPLE:
  echo Return values:
  echo "  " $EXIT_CODE_SUCCESS on success,
  echo "  " $EXIT_CODE_INTERNAL_ERROR on internal error,
  echo "  " $EXIT_CODE_INVALID_OPTIONS if invalid options specified,
  echo "  " $EXIT_CODE_ROOT_REQUIRED if root required,
  # echo "  " $EXIT_CODE_UBUNTU_REQUIRED if Ubuntu required,
  # echo "  " $EXIT_CODE_MINIMUM_OS_VERSION_REQUIRED if minimum OS version required,
  # echo "  " $EXIT_CODE_MAXIMUM_OS_VERSION_REQUIRED if maximum OS version required,
  # echo "  " $EXIT_CODE_SPECIFIC_SERVER_REQUIRED if specific server required,
  # echo "  " $EXIT_CODE_FILE_NOT_FOUND if file not found,
  # echo "  " $EXIT_CODE_DIRECTORY_NOT_FOUND if directory not found,
  # echo "  " $EXIT_CODE_FILE_IN_USE if file in use,
  echo "  " $EXIT_CODE_USER_ABORT on user abort
  echo
}


###################################################
# Set default variable values
VERSION_NUMBER="0.1.x"
QUIET_MODE=false
VERBOSE_MODE=false
ARGS="" # Add arguments to primary function called as needed
REDIRECT="/dev/stdout" # Switch to "/dev/null" for quiet mode
SET_PLEX_FILE_PERMISSIONS=false
# Option arguments can remain undefined.


###################################################
# Parse options and arguments with getopt

# Note about the following call to getopt
#   Options used here with the getopt command itself
#       --name : Script name, used for reporting errors
#       --options : Definition of short options
#       --longoptions (--long) : Definition of long options
#   Options used used with the getopt command itself
#       --alternative : Allow long options to start with a single '-'.
#       --help : Display help text and exit.  No other output is generated.
#       --quiet, --test, --unquoted, --version
#   Colon after an option means an argument is required. 
#       In this example, options A, B, and C are switches; a, b, and c expect arguments
#       Similarly for long options, options optionA, optionB, and optionC are switches; optiona, optionb, and optionc expect arguments
#   The '-- "$@"' at the end means that all other command arguments are "remaining arguments".
PARSED_ARGUMENTS=$(getopt --name $(basename "$0") --options pVvq \
    --long help,quiet,set-plex-file-permissions,verbose,version \
    -- "$@")
VALID_ARGUMENTS=$?
if [ "$VALID_ARGUMENTS" != "0" ]; then f_print_usage; exit $EXIT_CODE_INVALID_ARGUMENTS; fi
# Note about next command: 
# By reading that set of standardised arguments into the shell's input arguments 
#   the shell script now thinks that it was called with these simpler, standardised set of arguments.
eval set -- "$PARSED_ARGUMENTS"

while : ; do
    case "$1" in
      --help )
           f_print_usage
           exit $EXIT_CODE_SUCCESS
           ;;   
      -v | --version)  # Version number
           echo $VERSION_NUMBER
           exit $EXIT_CODE_SUCCESS
           ;;
      -q | --quiet)  # Quiet mode
           QUIET_MODE=true
           REDIRECT="/dev/null"
           ARGS+=" --quiet"
           shift # Only one (default) shift for a switch, i.e., no argument
           ;;
      -V | --verbose)  # Verbose mode
           VERBOSE_MODE=true
           shift # Only one (default) shift for a switch, i.e., no argument
           ;;
      -p | --set-plex-file-permissions)  # Set Plex Media Server video file permissions
           SET_PLEX_FILE_PERMISSIONS=true
           ARGS+=" --set-plex-file-permissions"
           shift # Only one (default) shift for a switch, i.e., no argument
           ;;
      --) # -- means the end of the arguments; drop this, and break out of the while loop
           shift
           break 
           ;;
      *) f_die "Unexpected option: $1 - Script programming error. Valid option has no handler." false $EXIT_CODE_INTERNAL_ERROR
           ;;
  esac
done


###################################################
# Do the work.
# IMPORTANT NOTES: 
#   Don't forget that you still can read and use environment variables!
#       Best practice: Required values should be required on and read from the command line, not environment variables.
#           Environment variables are fine for optional values.
#   We haven't yet tested for the existence of required options and/or remaining arguments (now $1, $2, etc.)
#   We also haven't yet tested for the valid options arguments and/or remaining arguments (now $1, $2, etc.)

# Set timezone
	echo
	echo "Setting timezone to $TIMEZONE"
    timedatectl set-timezone $TIMEZONE

# Clear /etc/NetworkManager/system-connections
	if $(f_is_installed "network-manager"); then 
		echo
		echo "Clearing /etc/NetworkManager/system-connections"
		rm -f /etc/NetworkManager/system-connections/*
		fi

# This heads off a network manager problem defined at https://askubuntu.com/questions/71159/network-manager-says-device-not-managed
	if $(f_is_installed "network-manager"); then 
		echo
		echo touch /etc/NetworkManager/conf.d/10-globally-managed-devices.conf
		touch /etc/NetworkManager/conf.d/10-globally-managed-devices.conf
		fi

# Update ~/.gitconfig
# Note that the original .gitconfig is made during setup/setup-os (original installation)
# using sudo, so the file is written to user root's home directory.
# That's why the copying goes from root to admin home directories.
	echo
	echo "Updating $ADMIN_HOME_DIR/.gitconfig from $ROOT_HOME_DIR/.gitconfig"
	cp $ROOT_HOME_DIR/.gitconfig $ADMIN_HOME_DIR/.gitconfig
	
# Update ~/.HandBrake
	rm -f "$ADMIN_HOME_DIR/.HandBrake"/* "$ROOT_HOME_DIR/.HandBrake/"*
	if $(f_is_installed "handbrake-cli"); then
		echo
		echo "Updating $ADMIN_HOME_DIR/.HandBrake from $GIT_GO_CONFIGS/ADMIN_HOME_DIR/.HandBrake"
		mkdir -p "$ADMIN_HOME_DIR/.HandBrake" "$ROOT_HOME_DIR/.HandBrake"
		cp "$GIT_GO_CONFIGS/ADMIN_HOME_DIR/.HandBrake/"* "$ADMIN_HOME_DIR/.HandBrake"
		cp "$GIT_GO_CONFIGS/ADMIN_HOME_DIR/.HandBrake/"* "$ROOT_HOME_DIR/.HandBrake"
		fi

# Update ~/.MakeMKV
	rm -f "$ADMIN_HOME_DIR/.MakeMKV/settings.conf" "$ROOT_HOME_DIR/.MakeMKV/settings.conf"
	if $(f_is_installed "makemkv-bin"); then
		echo
		echo "Updating $ADMIN_HOME_DIR/.MakeMKV/settings.conf from $GIT_GO_CONFIGS/ADMIN_HOME_DIR/.MakeMKV/settings.conf"
		mkdir -p "$ADMIN_HOME_DIR/.MakeMKV" "$ROOT_HOME_DIR/.MakeMKV"
		cp "$GIT_GO_CONFIGS/ADMIN_HOME_DIR/.MakeMKV/settings.conf" "$ADMIN_HOME_DIR/.MakeMKV/"
		cp "$GIT_GO_CONFIGS/ADMIN_HOME_DIR/.MakeMKV/settings.conf" "$ROOT_HOME_DIR/.MakeMKV/"
		fi

# Update ~/.ssh/authorized_keys
	if $(f_is_installed "ssh"); then
		echo
		echo "Updating $ADMIN_HOME_DIR/.ssh/authorized_keys from $GIT_GO_CONFIGS/ADMIN_HOME_DIR/.ssh/authorized_keys"
		cp "$GIT_GO_CONFIGS/ADMIN_HOME_DIR/.ssh/authorized_keys" "$ADMIN_HOME_DIR/.ssh/authorized_keys"
		cp "$GIT_GO_CONFIGS/ADMIN_HOME_DIR/.ssh/authorized_keys" "$ROOT_HOME_DIR/.ssh/authorized_keys"
		fi

# Update Vim and vi config file
# Commented out because defaults in Ubuntu 22 are much better
#	if [ -f $GIT_GO_CONFIGS/ADMIN_HOME_DIR/.vimrc ]; then
#		echo
#		echo Updating vim and vi config file
#		cp $GIT_GO_CONFIGS/ADMIN_HOME_DIR/.vim* $ADMIN_HOME_DIR/
#		cp $GIT_GO_CONFIGS/ADMIN_HOME_DIR/.vim* $ROOT_HOME_DIR/
#		fi

# Update /etc/exports
	rm -f /etc/exports
	if $(f_is_installed "nfs-kernel-server"); then
		echo
		echo "Updating /etc/exports from $GIT_GO_CONFIGS/etc/exports.$HOSTNAME"
		cp "$GIT_GO_CONFIGS/etc/exports.$HOSTNAME" "/etc/exports"
		exportfs -r
		systemctl restart nfs-*server
		fi

# Update /etc/fstab
	cp -n /etc/fstab /etc/fstab.original.install
	if $(f_is_file "$GIT_GO_CONFIGS/etc/fstab-peripherals.$HOSTNAME"); then
		echo
		echo "Updating /etc/fstab from /etc/fstab.original.install and $GIT_GO_CONFIGS/fstab/$HOSTNAME/fstab-peripherals"
		rm -f /etc/fstab
		cat /etc/fstab.original.install "$GIT_GO_CONFIGS/etc/fstab-peripherals.$HOSTNAME" > /tmp/fstab
		mv /tmp/fstab /etc/fstab
		mount --all &
		fi

# Update /etc/ddclient/ddclient.conf
	rm -f /etc/ddclient/*
	rm -f /etc/ddclient.*
	if $(f_is_installed "ddclient"); then
		echo
		echo "Updating /etc/ddclient.conf from $GIT_GO_CONFIGS/etc/ddclient/ddclient.conf.$HOSTNAME"
		mkdir -p /etc/ddclient
		cp $GIT_GO_CONFIGS/etc/ddclient/ddclient.conf.$HOSTNAME /etc/ddclient/ddclient.conf
		cp $GIT_GO_CONFIGS/etc/ddclient/ddclient.conf.default /etc/ddclient.conf.default
		fi

# Update /etc/hosts
	rm -f /etc/hosts
	if [ -f $GIT_GO_CONFIGS/hosts ]; then
		echo
		echo "Updating /etc/hosts from $GIT_GO_CONFIGS/hosts"
		cp "$GIT_GO_CONFIGS/etc/hosts" "/etc/hosts"
		fi

# Update /etc/lsyncd/*
	rm -f /etc/lyncd/*
	if $(f_is_installed "lsyncd"); then
		echo
		echo "Updating /etc/lsyncd/lsyncd.conf.lua from $GIT_GO_CONFIGS/lsyncd/lsyncd.conf.lua.$HOSTNAME"
		cp $GIT_GO_CONFIGS/lsyncd/lsyncd.conf.lua.$HOSTNAME /etc/lsyncd/lsyncd.conf.lua
		systemctl restart lsyncd
		fi

# Update /etc/motd
	if [ -f $GIT_GO_CONFIGS/etc/motd.$HOSTNAME ]; then
		echo
		echo "Updating /etc/motd from $GIT_GO_CONFIGS/etc/motd.$HOSTNAME"
		cp "$GIT_GO_CONFIGS/etc/motd.$HOSTNAME" "/etc/motd"
		fi

# Update any netplan configuration files
	if [ -f $GIT_GO_CONFIGS/etc/netplan/dynamic.yaml.$HOSTNAME ]; then
		echo
		echo "Updating /etc/netplan/current-plan.yaml from $GIT_GO_CONFIGS/etc/netplan/dynamic.yaml.$HOSTNAME"
		rm -f /etc/NetworkManager/system-connections/* /etc/netplan/*
		cp "$GIT_GO_CONFIGS/etc/netplan/dynamic.yaml.$HOSTNAME" /etc/netplan/current-plan.yaml
		netplan apply &
		fi

# Update /etc/resolvconf/resolv.conf.d/head
	if $(f_is_installed "resolvconf"); then
		echo
		echo "Updating /etc/resolvconf/resolv.conf.d/head from $GIT_GO_CONFIGS/resolvconf/resolv.conf.d/head"
		mkdir -p /etc/resolvconf/resolv.conf.d
		cp $GIT_GO_CONFIGS/resolvconf/resolv.conf.d/head /etc/resolvconf/resolv.conf.d/
		fi

# Update /etc/sshd_config
	if $(f_is_installed "ssh"); then
		echo
		echo "Updating /etc/ssh/sshd_config from $GIT_GO_CONFIGS/etc/ssh/sshd_config"
		cp "$GIT_GO_CONFIGS/etc/ssh/sshd_config" "/etc/ssh/sshd_config"
		systemctl restart ssh
		fi

# Update /etc/ufw/applications.d/lane-applications
	if $(f_is_directory "$GIT_GO_CONFIGS/etc/ufw/applications.d/lane-applications"); then
		echo
		echo "Updating /etc/ufw/applications.d/lane-applications from $GIT_GO_CONFIGS/etc/ufw/applications.d/lane-applications"
		cp $GIT_GO_CONFIGS//etc/ufw/applications.d/lane-applications /etc/ufw/applications.d/
		ufw app update lane-applications
		fi

# Update $PHPMYADMIN_DIR/config.inc.php
	if $(f_is_installed "phpmyadmin"); then
		echo
		echo "Updating $PHPMYADMIN_DIR/config.inc.php from $GIT_GO_CONFIGS$PHPMYADMIN_DIR/config.inc.php"
		mkdir -p "$PHPMYADMIN_DIR"
		cp "$GIT_GO_CONFIGS$PHPMYADMIN_DIR/config.inc.php" "$PHPMYADMIN_DIR/config.inc.php"
		systemctl restart apache2 &
		fi


############################################################################################################

# Apply permissions
	_apply-permissions $ARGS


###################################################
# Wrap up.

# Include script footer file
	f_debug_variable "script_footer" "${PATHNAME[script_footer]}"
	source "${PATHNAME[script_footer]}"
