#!/bin/bash
# _apply-permissions

# Invoked by _apply-configs

# Include script setup file
	source script-setup
	if [ ! $FUNCTIONS_ARE_DEFINED ]; then echo $0: Functions not defined. Aborting; logger $0: Functions not defined. Aborting; fi
	if [ ! $VARIABLES_ARE_DEFINED ]; then echo $0: Variables not defined. Aborting; logger $0: Variables not defined. Aborting; fi

# Set ownership and permissions in $SBIN_DIR
	chown -R $ROOT_USER:$ROOT_USER $SBIN_DIR
	find $SBIN_DIR -type d -print -exec chmod 700 {} \; >> /dev/null 2>&1
	find $SBIN_DIR -type f -print -exec chmod 750 {} \; >> /dev/null 2>&1

# Exceptions: These can be read or run by anyone
	# These based on functional requirements
		chmod 755 ${PATHNAME[currenttimeinseconds]}
		chmod 755 ${PATHNAME[intervalinseconds]}
		chmod 755 ${PATHNAME[lhlib]}
		chmod 755 ${PATHNAME[process_incoming_scans]}
		chmod 755 ${PATHNAME[rip]}
		chmod 755 ${PATHNAME[script_footer]} 
		chmod 755 ${PATHNAME[script_setup]} 
		chmod 755 ${PATHNAME[timeformat]}
		chmod 755 ${PATHNAME[transcode_ripped_dvds]}
	# These based on desire. CAUTION: Don't expose anything that has a password or code in it.
		chmod 740 ${PATHNAME[upd]} 
		chmod 740 ${PATHNAME[_apply_configs]}

# ddclient
	if [ -f $GIT_GO_CONFIGS/ddclient/$HOSTNAME/ddclient.conf ]; then
		chmod 600 /etc/ddclient.conf /etc/default/ddclient # confirmed value
		chown $ROOT_USER:$ROOT_USER /etc/ddclient.conf /etc/default/ddclient
		fi

# fstab
	if [ -f $GIT_GO_CONFIGS/fstab/$HOSTNAME/fstab ]; then
		chown $ROOT_USER:$ROOT_USER /etc/fstab*
		chmod 664 /etc/fstab* # confirmed value
		fi

# Git
	chmod 600 $ROOT_HOME_DIR/.gitconfig
	chmod 600 $ADMIN_HOME_DIR/.gitconfig
	chown $ROOT_USER:$ROOT_USER $ROOT_HOME_DIR/.gitconfig
	chown $ADMIN_USER:$ADMIN_USER $ADMIN_HOME_DIR/.gitconfig
	chmod -R 400 $GIT_ROOT/*

# lsyncd
	if [ -f $GIT_GO_CONFIGS/lsyncd/$HOSTNAME/lsyncd.conf.lua ]; then
		chown $ROOT_USER:$ROOT_USER /etc/lsyncd/lsyncd.conf.lua # NOT confirmed; relevant to system viability?
		chmod 600 /etc/lsyncd/lsyncd.conf.lua # NOT confirmed; relevant to system viability?
		fi

# resolvconf
	if [ -f $GIT_GO_CONFIGS/resolvconf/head ]; then
		chown $ROOT_USER:$ROOT_USER /etc/resolvconf/resolv.conf.d/head # NOT confirmed; relevant to system viability?
		chmod 644 /etc/resolvconf/resolv.conf.d/head # NOT confirmed; relevant to system viability?
		fi

# .ssh/authorized_keys
#	if [ -f $GIT_GO_CONFIGS/ssh/home-.ssh-authorized_keys ]; then
		chown -fR $ADMIN_USER:$ADMIN_USER $ADMIN_HOME_DIR/.ssh # Confirmed
		chown -fR $ROOT_USER:$ROOT_USER $ROOT_HOME_DIR/.ssh # Confirmed
		chmod -f 700 $ADMIN_HOME_DIR/.ssh $ROOT_HOME_DIR/.ssh # Confirmed
		chmod -f 644 $ADMIN_HOME_DIR/.ssh/id_rsa.pub $ROOT_HOME_DIR/.ssh/id_rsa.pub # Confirmed
		chmod -f 600 $ADMIN_HOME_DIR/.ssh/id_rsa $ROOT_HOME_DIR/.ssh/id_rsa $ADMIN_HOME_DIR/.ssh/authorized_keys $ROOT_HOME_DIR/.ssh/authorized_keys # Confirmed
		f_debug
#		fi

# SSHD config file
	if [ -f $GIT_GO_CONFIGS/ssh/etc-ssh-sshd_config ]; then
		chown $ROOT_USER:$ROOT_USER "$SSHD_CONFIG" # Confirmed
		chmod 644 "$SSHD_CONFIG" # Confirmed
		fi

# HandBrake config file
	chmod -fR 600 $ADMIN_HOME_DIR/.HandBrake
	chown -fR $ADMIN_USER:$ADMIN_USER $ADMIN_HOME_DIR/.HandBrake $ADMIN_HOME_DIR/Videos/*
	chown -fR $ROOT_USER:$ROOT_USER $ROOT_HOME_DIR/.HandBrake/*

# Vim and vi config files
	if [ -f $GIT_GO_CONFIGS/vim/.vimrc ]; then
		chmod 600 $ADMIN_HOME_DIR/.vim*
		chown $ADMIN_USER:$ADMIN_USER $ADMIN_HOME_DIR/.vim*
		chown $ROOT_USER:$ROOT_USER $ROOT_HOME_DIR/.vim*
		fi

echo "Installation complete."

# Include script footer file
	f_debug_variable "script_footer" "${PATHNAME[script_footer]}"
	source "${PATHNAME[script_footer]}"

exit 0

