#!/bin/bash
# _git

# Include script setup file
source $(dirname $0)/script-setup

# Install git token
# To get a new token, go to https://github.com/settings/tokens.
MY_GIT_TOKEN=4b662b7d4431ec1956127aa9d4fdbd8d75ec821a
git config --global url."https://api:$MY_GIT_TOKEN@github.com/".insteadOf "https://github.com/"
git config --global url."https://ssh:$MY_GIT_TOKEN@github.com/".insteadOf "ssh://git@github.com/"
git config --global url."https://git:$MY_GIT_TOKEN@github.com/".insteadOf "git@github.com:"
# This section re-pulls all go files from github and updates ${LANE_CONFIG[system.sbin-dir]}
# BRANCH="master"
BRANCH="dev"
# Change to local repository directory
cd ${LANE_CONFIG[system.git.go]}
# Blow away any local changes not uploaded to github
git reset --hard
# Select the designated branch
git checkout $BRANCH
# Pull down a copy of the repository
git pull
# Set permissions for git directory
chmod -R 400 ${LANE_CONFIG[system.git]}
# Copy scripts into /usr/local/sbin
rm -rf ${LANE_CONFIG[system.sbin-dir]}
cp -r ${LANE_CONFIG[system.git.go.sbin]} ${LANE_CONFIG[system.sbin-parent]}
cd
logger "$0: git branch $BRANCH pulled."

# Set ownership and permissions in /usr/local/sbin
chown -R root:root ${LANE_CONFIG[system.sbin-dir]}
find ${LANE_CONFIG[system.sbin-dir]} -type d -print -exec chmod 755 {} \; >> /dev/null 2>&1
find ${LANE_CONFIG[system.sbin-dir]} -type f -print -exec chmod 755 {} \; >> /dev/null 2>&1

# Reset permisions for /usr/local/sbin/*
# This kind of locks things down, and the apply-configs section below opens things up.
#chown -R root:root ${LANE_CONFIG[system.sbin-dir]}
#chmod 755 ${LANE_CONFIG[system.sbin-dir]} ${LANE_CONFIG[system.sbin-dir]}/setup ${LANE_CONFIG[system.sbin-dir]}/include
#chmod -R 500 ${LANE_CONFIG[system.sbin-dir]}/*

# Invoke /usr/local/sbin/_apply-configs
#chmod 500 ${LANE_CONFIG[system.sbin-dir]}/_apply-configs
${LANE_CONFIG[system.sbin-dir]}/_apply-configs

# Include script footer file
f_debug_variable "script.script-footer.pathname" "${LANE_CONFIG[script.script-footer.pathname]}"
source ${LANE_CONFIG[script.script-footer.pathname]}

exit 0