#!/bin/bash
# _git

# Include script setup file
source $(dirname $0)/script-setup

# Install git token
# To get a new token, go to https://github.com/settings/tokens.
MY_GIT_TOKEN=4b662b7d4431ec1956127aa9d4fdbd8d75ec821a
git config --global url."https://api:$MY_GIT_TOKEN@github.com/".insteadOf "https://github.com/"
git config --global url."https://ssh:$MY_GIT_TOKEN@github.com/".insteadOf "ssh://git@github.com/"
git config --global url."https://git:$MY_GIT_TOKEN@github.com/".insteadOf "git@github.com:"
# This section re-pulls all go files from github and updates /usr/local/sbin
USERNAME=$USER_ME
REPOSITORY=$GO
# BRANCH="master"
BRANCH="dev"
# Change to local repository directory
cd $REPOSITORY
# Blow away any local changes not uploaded to github
git reset --hard
# Select the designated branch
git checkout $BRANCH
# Pull down a copy of the repository
git pull
# Set permissions for git directory
chmod -R 400 $GIT
# Copy scripts into /usr/local/sbin
rm -rf $SBIN_DIR
cp -r $GO_SBIN $SBIN_PARENT
cd
# Change this to logging. Can't be seen anyway.
echo git update complete.

# Set ownership and permissions in /usr/local/sbin
chown -R root:root $SBIN_DIR
# chmod 755 $SBIN_DIR $SBIN_DIR/setup $SBIN_DIR/include
find $SBIN_DIR -type d -print -exec chmod 755 {} \; >> /dev/null 2>&1
# chmod -R 755 $SBIN_DIR/*
find $SBIN_DIR -type f -print -exec chmod 755 {} \; >> /dev/null 2>&1

# Reset permisions for /usr/local/sbin/*
# This kind of locks things down, and the apply-configs section below opens things up.
#	echo GO_SBIN $GO_SBIN
#	echo SBIN_PARENT $SBIN_PARENT
#	echo SBIN_DIR $SBIN_DIR
#	echo 1 About to chown -R root:root $SBIN_DIR
#	read -p "Press any key to resume ..."
#chown -R root:root $SBIN_DIR
#	echo GO_SBIN $GO_SBIN
#	echo SBIN_PARENT $SBIN_PARENT
#	echo SBIN_DIR $SBIN_DIR
#	echo 2 About to chmod 755 $SBIN_DIR $SBIN_DIR/setup $SBIN_DIR/include
#	read -p "Press any key to resume ..."
#chmod 755 $SBIN_DIR $SBIN_DIR/setup $SBIN_DIR/include
#	echo GO_SBIN $GO_SBIN
#	echo SBIN_PARENT $SBIN_PARENT
#	echo SBIN_DIR $SBIN_DIR
#	echo 3 About to chmod -R 500 $SBIN_DIR/(star)
#	read -p "Press any key to resume ..."
#chmod -R 500 $SBIN_DIR/*

# Invoke /usr/local/sbin/_apply-configs
# chmod 500 $SBIN_DIR/_apply-configs
	echo GO_SBIN $GO_SBIN
	echo SBIN_PARENT $SBIN_PARENT
	echo SBIN_DIR $SBIN_DIR
	echo 4 About to $SBIN_DIR/_apply-configs
	read -p "Press any key to resume ..."
$SBIN_DIR/_apply-configs

logger "$0 ended without error."
exit 0