#!/bin/bash
# apply-configs
#
# Include header file
logger Begin $0
PROGRAM_DIRECTORY=$(dirname $0)
source $PROGRAM_DIRECTORY/script-setup

# Changed apt-get to apt 1/31/19.
# See https://itsfoss.com/apt-vs-apt-difference/ for rationale.

# Set ownership and permissions in /usr/local/sbin
# 6/22/2020: Read access for root ONLY.
chown -R root:root $SBIN_DIR
chmod 755 $SBIN_DIR $SBIN_DIR/setup $SBIN_DIR/include
chmod -R 500 $SBIN_DIR/*

# Exceptions: These can be read or run by anyone
# These based on functional requirements
chmod 755 /usr/local/sbin/lhlib /usr/local/sbin/rip /usr/local/sbin/transcode
# These based on desire. CAUTION: Don't expose anything that has a password or code in it.
chmod 740 /usr/local/sbin/upd /usr/local/sbin/script-setup /usr/local/sbin/apply-configs

# Git
chmod 600 /root/.gitconfig
cp /root/.gitconfig $HOME_DIR/.gitconfig
chown root:root /root/.gitconfig
chown $USER_ME:$USER_ME $HOME_DIR/.gitconfig
chmod -R 400 $GIT

# ddclient
cp $GO_CONFIGS/ddclient/$HOST_NAME/ddclient.conf /etc/
chmod 600 /etc/ddclient.conf
chown root:root /etc/ddclient.conf
cp $GO_CONFIGS/ddclient/etc-default-ddclient /etc/default/ddclient
chmod 600 /etc/default/ddclient
chown root:root /etc/default/ddclient

# Lsyncd
cp $GO_CONFIGS/Lsyncd/$HOST_NAME/lsyncd.conf.lua /etc/Lsyncd
chmod 600 /etc/Lsyncd/lsyncd.conf.lua
chown root:root /etc/Lsyncd/lsyncd.conf.lua
systemctl restart lsyncd

# Update DNS resolution
mkdir -p /etc/resolvconf/resolv.conf.f
cp $GO_CONFIGS/resolvconf/head /etc/resolvconf/resolv.conf.d/
chown root:root /etc/resolvconf/resolv.conf.d/head
chmod 644 /etc/resolvconf/resolv.conf.d/head

# Update /home/$USER_ME/.ssh/authorized_keys
mkdir -p /home/$USER_ME/.ssh
cp $GO_CONFIGS/ssh/home-.ssh-authorized_keys /home/$USER_ME/.ssh/authorized_keys
chown -R $USER_ME:$USER_ME /home/$USER_ME/.ssh
chmod 600 /home/$USER_ME/.ssh/authorized_keys

# SSHD config file
cp $GO_CONFIGS/ssh/etc-ssh-sshd_config /etc/ssh/sshd_config
chmod 644 /etc/ssh/sshd_config
chown root:root /etc/ssh/sshd_config
systemctl restart ssh

# MakeMKV config file
mkdir -p $HOME_DIR/.MakeMKV
mkdir -p /root/.MakeMKV
cp $GO_CONFIGS/makemkv/settings.conf $HOME_DIR/.MakeMKV/
chmod 600 $HOME_DIR/.MakeMKV/settings.conf
chown -R $USER_ME:$USER_ME $HOME_DIR/.MakeMKV
cp $HOME_DIR/.MakeMKV/settings.conf /root/.MakeMKV/
chown -R root:root /root/.MakeMKV

# HandBrake config file
mkdir -p $HOME_DIR/.HandBrake
mkdir -p /root/.HandBrake
cp $GO_CONFIGS/handbrake/* $HOME_DIR/.HandBrake/
chmod 600 $HOME_DIR/.HandBrake/*
chown -R $USER_ME:$USER_ME $HOME_DIR/.HandBrake $HOME_DIR/Videos
cp $HOME_DIR/.HandBrake/* /root/.HandBrake/
chown -R root:root /root/.HandBrake

# Vim and vi config file
cp $GO_CONFIGS/vim/.vimrc $HOME_DIR/
chmod 600 $HOME_DIR/.vimrc
chown $USER_ME:$USER_ME $HOME_DIR/.vimrc
cp $HOME_DIR/.vimrc /root/
chown root:root /root/.vimrc

