#!/bin/bash

# Include script setup file
	source script-setup
	if [ ! $FUNCTIONS_ARE_DEFINED ]; then echo $0: Functions not defined. Aborting; logger $0: Functions not defined. Aborting; exit 1; fi
	if [ ! $VARIABLES_ARE_DEFINED ]; then echo $0: Variables not defined. Aborting; logger $0: Variables not defined. Aborting; exit 1; fi

# Require root
	f_require_root

# Require server nuc01
	f_only_on_server nuc01

# Mount target file system
	TARGET_FILE_SYSTEM="/mnt/12TBA"
	if ! $(f_mount_ro_fs_as_rw "$TARGET_FILE_SYSTEM") ; then
		f_die "$TARGET_FILE_SYSTEM is not mounted." true
		fi

# Run the backup (rsync)
	for this_directory in "plex" "plex-dvr" "plexlinks" "plex-other" "plex-tv" "plex-videos"
		do
			echo Syncing /mnt/cloteal/$this_directory ...
			rsync -aloprtvE --delete "/mnt/cloteal/$this_directory/"* "TARGET_FILE_SYSTEM/archives/nuc01/plexcontent/$this_directory"
#			rsync -aloprtvE --delete "nuc01.lanehensley.org:/mnt/cloteal/$this_directory/"* "/mnt/12TBA/archives/nuc01/plexcontent/$this_directory"
#			sudo -u $ADMIN_USER rsync -aloprtvE --delete "nuc01.lanehensley.org:/mnt/cloteal/$this_directory/"* "/mnt/12TBA/archives/nuc01/plexcontent/$this_directory"
		done

# Include script footer file
	f_debug_variable "script_footer" "${PATHNAME[script_footer]}"
	source "${PATHNAME[script_footer]}"

exit 0
