#!/bin/bash

# Include script setup file
	source script-setup
	if [ ! $FUNCTIONS_ARE_DEFINED ]; then echo $0: Functions not defined. Aborting; logger $0: Functions not defined. Aborting; exit 1; fi
	if [ ! $VARIABLES_ARE_DEFINED ]; then echo $0: Variables not defined. Aborting; logger $0: Variables not defined. Aborting; exit 1; fi

# Require root
	f_require_root

# Require server nuc01
	f_only_on_server nuc01

# Define variables
	SOURCE_PLEX_DVR_TS_CONTAINER_DIR="/mnt/bob/plex-dvr"
	SOURCE_PLEX_CONTENT_DIR="/mnt/cloteal"
	TARGET_FILE_SYSTEM="/mnt/12TBA"
	TARGET_PLEX_CONTENT_DIR="$TARGET_FILE_SYSTEM/archives/nuc01/plexcontent"
	TARGET_PLEX_DVR_TS_CONTAINER_DIR="$TARGET_PLEX_CONTENT_DIR/plex-dvr-in"

# Mount target file system
	if ! $(f_mount_fs_as_rw "$TARGET_FILE_SYSTEM") ; then
		f_die "$TARGET_FILE_SYSTEM cannot be mounted." true
		fi

# Backup all Plex content directories using rsync
	for this_directory in "plex" "plex-dvr" "plexlinks" "plex-other" "plex-tv" "plex-videos"
		do
			SOURCE_DIR="SOURCE_PLEX_CONTENT_DIR/$this_directory"
			TARGET_DIR="$TARGET_PLEX_CONTENT_DIR/$this_directory"
			rsync -aloprtvE --delete "$SOURCE_DIR/"* "$TARGET_DIR"
		done

# Move (removing source) all completed Plex DVR TS files using rsync
	echo Start TS
	rsync --archive --links --owner --perms --recursive --times \
		--verbose --executability --remove-source-files \
		"$SOURCE_PLEX_DVR_TS_CONTAINER_DIR/"* "$TARGET_PLEX_DVR_TS_CONTAINER_DIR"
	echo End TS

# Include script footer file
	f_debug_variable "script_footer" "${PATHNAME[script_footer]}"
	source "${PATHNAME[script_footer]}"

exit 0
