#!/bin/bash

# Dumps all the MySQL data (except system info)
# And stores the results
# Clean-up started 2026-06-17

# Set DEBUG_MODE to make the script
DEBUG_MODE=false; if $DEBUG_MODE ; then echo "DEBUG EXECUTING $0 line ${LINENO}" $(date +"%F %T.%3N %Z") ; fi
# if $DEBUG_MODE ; then echo "DEBUG MARKER $0 line ${LINENO}" $(date +"%F %T.%3N %Z") ; fi

# Include script setup file
	source script-setup
	if [ ! $FUNCTIONS_ARE_DEFINED ]; then echo $0: Functions not defined. Aborting; logger $0: Functions not defined. Aborting; exit 1; fi
	if [ ! $VARIABLES_ARE_DEFINED ]; then echo $0: Variables not defined. Aborting; logger $0: Variables not defined. Aborting; exit 1; fi

# Require root
	f_require_root

# CHECK FOR ENOUGH ARGUMENTS (change 0 to minimum arguments and flesh out Usage)
if [ $# -lt 0 ]; 
    then echo "$EXIT_CODE_DESC_DIRECTORY_NOT_FOUND" > /dev/stderr
	echo "Usage: $(basename $0)" > /dev/stderr
	exit $EXIT_CODE_DIRECTORY_NOT_FOUND
fi

# Debugging checkpoint
if $DEBUG_MODE ; then echo "DEBUG MARKER $0 line ${LINENO}" $(date +"%F %T.%3N %Z") ; fi

# Set variables
WORKING_DIR="/tmp/mysql-$UUID"
WORKING_DUMP="$WORKING_DIR/$HOSTNAME.sql"
TIMESTAMP="$(/bin/date '+%Y-%m-%d-%H-%M-%S-%Z')"

# echo WORKING_DIR="/tmp/mysql-$UUID"
echo WORKING_DUMP=$WORKING_DUMP
echo TIMESTAMP=$TIMESTAMP
# echo mkdir --mode=600 -p $WORKING_DIR
mkdir --mode=600 -p $WORKING_DIR

# echo "$(/bin/date '+%Y-%m-%d-%H-%M-%S-%Z'): Dumping all user databases. (This takes a while.)" > /dev/stderr
echo "Dumping all user databases. (This takes a while.)" > /dev/stderr
mysqldump --databases \
    $(for d in $(mysql -Bse 'show databases') ;
        do if [ "$d" != "information_schema" ] \
        && [ "$d" != "mysql" ] \
        && [ "$d" != "performance_schema" ] \
        && [ "$d" != "phpmyadmin" ] \
        && [ "$d" != "sys" ]; \
        then printf "%s " "$d"; fi; done) \
        --triggers --events --routines > $WORKING_DUMP

# echo chmod -R 600 $WORKING_DIR/*
chmod -R 600 $WORKING_DIR/*

############################################################################
# IMPORTANT: At this point, the $WORKING_DUMP is finished. 
# Everything else is compessing, moving it around, and naming it as helpful.

###### Disabling this section 2026-07-08
# if [ $HOSTNAME = dsm1 ] ; then
#     mkdir -p /mnt/5TBC/archives/mysql /mnt/20TBA/archives/mysql
#     echo $(/bin/date '+%Y-%m-%d-%H-%M-%S-%Z'): Copying the dump to /mnt/5TBC/archives/mysql/$HOSTNAME-d-$START_WEEKDAYSTAMP3.sql.gz  > /dev/stderr
#     cp $WORKING_DUMP /mnt/5TBC/archives/mysql/$HOSTNAME-d-$START_WEEKDAYSTAMP3.sql.gz
#     echo $(/bin/date '+%Y-%m-%d-%H-%M-%S-%Z'): Copying the dump to /mnt/5TBC/archives/mysql/$HOSTNAME-m-$START_MONTHSTAMP.sql.gz > /dev/stderr
#     cp $WORKING_DUMP /mnt/5TBC/archives/mysql/$HOSTNAME-m-$START_MONTHSTAMP.sql.gz
#     echo $(/bin/date '+%Y-%m-%d-%H-%M-%S-%Z'): Copying the dump to /mnt/20TBA/archives/mysql/$HOSTNAME-d-$START_WEEKDAYSTAMP3.sql.gz > /dev/stderr
#     cp $WORKING_DUMP /mnt/20TBA/archives/mysql/$HOSTNAME-d-$START_WEEKDAYSTAMP3.sql.gz
#     ln -f /mnt/5TBC/archives/mysql/$HOSTNAME-m-$START_MONTHSTAMP.sql.gz /mnt/5TBC/archives/mysql/dsm1.sql.gz
#     echo $(/bin/date '+%Y-%m-%d-%H-%M-%S-%Z'): Copying the dump to /mnt/20TBA/archives/mysql/$HOSTNAME-m-$START_MONTHSTAMP.sql.gz > /dev/stderr
#     cp $WORKING_DUMP /mnt/20TBA/archives/mysql/$HOSTNAME-m-$START_MONTHSTAMP.sql.gz
#     ln -f /mnt/20TBA/archives/mysql/$HOSTNAME-m-$START_MONTHSTAMP.sql.gz /mnt/20TBA/archives/mysql/dsm1.sql.gz
#     echo "$(/bin/date '+%Y-%m-%d-%H-%M-%S-%Z'): Copying the dump to pd1" > /dev/stderr
#     chown $ADMIN_USER $WORKING_DUMP
#     sudo -u $ADMIN_USER sftp pd1 <<< $"put $WORKING_DUMP" > /dev/null 2> /dev/null
#     echo "$(/bin/date '+%Y-%m-%d-%H-%M-%S-%Z'): Decompressing the dump on pd1" > /dev/stderr
#     sudo -u $ADMIN_USER ssh pd1 rm -f dsm1.sql
#     sudo -u $ADMIN_USER ssh pd1 gunzip dsm1.sql.gz
#     echo "$(/bin/date '+%Y-%m-%d-%H-%M-%S-%Z'): Importing the dump into MySQL on pd1.  (This REALLY takes a while.)" > /dev/stderr
#     sudo -u $ADMIN_USER ssh pd1 mysql < dsm1.sql
#     echo "$(/bin/date '+%Y-%m-%d-%H-%M-%S-%Z'): Cleaning up on pd1" > /dev/stderr
#     sudo -u $ADMIN_USER ssh pd1 rm -f dsm1.sql
#     chown $ROOT_USER $WORKING_DUMP
#     fi

###### Disabling this section 2026-07-08
# if [ $HOSTNAME = pd1 ] ; then
#     mkdir -p /mnt/bob/archives/mysql
#     echo "$(/bin/date '+%Y-%m-%d-%H-%M-%S-%Z'): Copying the dump to /mnt/bob/archives/mysql/$HOSTNAME-d-$START_WEEKDAYSTAMP3.sql.gz" > /dev/stderr
#     cp $WORKING_DUMP /mnt/bob/archives/mysql/$HOSTNAME-d-$START_WEEKDAYSTAMP3.sql.gz
#     echo "$(/bin/date '+%Y-%m-%d-%H-%M-%S-%Z'): Copying the dump to /mnt/bob/archives/mysql/$HOSTNAME-m-$START_MONTHSTAMP.sql.gz" > /dev/stderr
#     cp $WORKING_DUMP /mnt/bob/archives/mysql/$HOSTNAME-m-$START_MONTHSTAMP.sql.gz
#     ln -f /mnt/bob/archives/mysql/$HOSTNAME-m-$START_MONTHSTAMP.sql.gz /mnt/bob/archives/mysql/pd1.sql.gz
#     fi

mkdir --mode=600 -p "$ADMIN_HOME_DIR/backups/MySQL"
echo mv $WORKING_DUMP $ADMIN_HOME_DIR/backups/MySQL/
mv $WORKING_DUMP $ADMIN_HOME_DIR/backups/MySQL/

#####################################################################
# 2026-07-08: Is the command below necessary or helpful? Checking ...
rm -rf $WORKING_DIR
echo "$(/bin/date '+%Y-%m-%d-%H-%M-%S-%Z'): Done!" > /dev/stderr

# Option to text the administrator when the script ends
# echo "[$(hostname)] $(basename $0): completed" | mail "$ADMIN_CELL_EMAIL" > /dev/stderr

if $DEBUG_MODE ; then echo "DEBUG ENDING $0 line ${LINENO}" $(date +"%F %T.%3N %Z") ; fi

# Include script footer file
	f_debug_variable "script_footer" "${PATHNAME[script_footer]}"
	source "${PATHNAME[script_footer]}"

exit 0
