#!/bin/bash

# Include script setup file
	source script-setup
	if [ ! $FUNCTIONS_ARE_DEFINED ]; then echo $0: Functions not defined. Aborting; logger $0: Functions not defined. Aborting; exit 1; fi
	if [ ! $VARIABLES_ARE_DEFINED ]; then echo $0: Variables not defined. Aborting; logger $0: Variables not defined. Aborting; exit 1; fi

# To see what's currently "banned" by fail2ban, issue this command:
#     sudo fail2ban-client status sshd

# To see what Wordpress has blocked over the last 30 days,
# visit https://lanehensley.org/wp-admin/admin.php?page=WordfenceWAF

ufw deny from 5.161.136.10 to any # 2024-07-08 - United States address, blocked by Wordfence, block count 1
ufw deny from 15.204.52.61 to any
ufw deny from 23.137.104.110 to any # 2024-07-08 - United States address, blocked by Wordfence, block count 2
ufw deny from 23.137.104.208 to any # 2024-07-08 - United States address, blocked by Wordfence, block count 1
ufw deny from 43.131.2.238 to any # 2024-07-16 - Germany, blocked by Wordfence, block count 1
ufw deny from 43.157.25.217 to any # 2024-07-08 - Germany address, blocked by Wordfence, block count 1
ufw deny from 51.15.184.67 to any # 2024-07-08 - France address, blocked by Wordfence, block count 1
ufw deny from 54.80.109.178 to any # 2024-07-08 - United States address, blocked by Wordfence, block count 1
ufw deny from 62.146.177.34 to any # 2024-07-08 - Germany address, blocked by Wordfence, block count 8
ufw deny from 77.95.113.13 to any # 2024-07-08 - United Kingdom address, blocked by Wordfence, block count 1
ufw deny from 79.110.49.196 to any # 2024-07-08 - France address, blocked by Wordfence, block count 8
ufw deny from 79.110.62.2 to any # 2024-07-08 - Bulgaria address, blocked by Wordfence, block count 8
ufw deny from 80.76.49.175 to any # 2024-07-08 - United States address, blocked by Wordfence, block count 13
ufw deny from 82.102.27.195 to any # 2024-07-08 - Norway address, blocked by Wordfence, block count 1
ufw deny from 87.236.176.87 to any
ufw deny from 91.92.240.138 to any # 2024-07-08 - Bulgaria address, blocked by Wordfence, block count 32
ufw deny from 91.92.242.218 to any # 2024-07-08 - Bulgaria address, blocked by Wordfence, block count 45
ufw deny from 91.92.242.218 to any # 2024-07-16 - Bulgaria, blocked by Wordfence, block count 45
ufw deny from 91.92.243.31 to any # 2024-07-08 - Bulgaria address, blocked by Wordfence, block count 23
ufw deny from 91.92.243.143 to any # 2024-07-08 - Bulgaria address, blocked by Wordfence, block count 1
ufw deny from 91.92.244.113 to any # 2024-07-08 - Bulgaria address, blocked by Wordfence, block count 1
ufw deny from 91.92.248.144 to any # 2024-07-08 - Bulgaria address, blocked by Wordfence, block count 8
ufw deny from 91.92.252.16 to any # 2024-07-08 - Bulgaria address, blocked by Wordfence, block count 8
ufw deny from 94.156.65.48 to any # 2024-07-08 - Bulgaria address, blocked by Wordfence, block count 2
ufw deny from 94.156.66.185 to any # 2024-07-08 - Bulgaria address, blocked by Wordfence, block count 2
ufw deny from 94.156.68.8 to any # 2024-07-08 - Netherlands address, blocked by Wordfence, block count 4
ufw deny from 94.156.69.126 to any # 2024-07-08 - Bulgaria address, blocked by Wordfence, block count 4
ufw deny from 94.156.69.127 to any # 2024-07-08 - Bulgaria address, blocked by Wordfence, block count 5
ufw deny from 101.132.97.62 to any # 2024-07-08 - China address, blocked by Wordfence, block count 1
ufw deny from 104.193.135.243 to any # 2024-07-08 - Canada address, blocked by Wordfence, block count 7
ufw deny from 138.128.174.26 to any # 2024-07-08 - United States address, blocked by Wordfence, block count 1
ufw deny from 138.199.47.241 to any # 2024-07-08 - France address, blocked by Wordfence, block count 1
ufw deny from 139.99.220.157 to any # 2024-07-08 - Australia address, blocked by Wordfence, block count 12
ufw deny from 156.38.128.82 to any # 2024-07-08 - South Africa address, blocked by Wordfence, block count 1
ufw deny from 167.99.79.202 to any # 2024-07-08 - Singapore address, blocked by Wordfence, block count 2
ufw deny from 178.159.37.38 to any # 2024-07-08 - Ukraine address, blocked by Wordfence, block count 14
ufw deny from 179.43.191.18 to any # 2024-07-08 - Switzerland address, blocked by Wordfence, block count 2
ufw deny from 184.105.247.223 to any
ufw deny from 184.154.46.40 to any # 2024-07-08 - United States address, blocked by Wordfence, block count 1
ufw deny from 188.164.196.16 to any # 2024-07-08 - Spain address, blocked by Wordfence, block count 1
ufw deny from 193.189.100.204 to any # 2024-07-08 - Sweden address, blocked by Wordfence, block count 1
ufw deny from 194.38.20.13 to any # 2024-07-22 - Ukraine address, blocked by Wordfence, block count 3
ufw deny from 194.38.23.16 to any # 2024-07-08 - Ukraine address, blocked by Wordfence, block count 35
ufw deny from 194.163.145.202 to any # 2024-07-08 - Germany address, blocked by Wordfence, block count 17
ufw deny from 198.12.234.215 to any # 2024-07-08 - United States address, blocked by Wordfence, block count 1
ufw deny from 199.19.72.125 to any
ufw deny from 199.45.154.114 to any
ufw deny from 206.168.34.37 to any
# Include script footer file
	f_debug_variable "script_footer" "${PATHNAME[script_footer]}"
	source "${PATHNAME[script_footer]}"

exit 0
