#!/bin/bash 

# Include script setup file
	source script-setup
	if [ ! $FUNCTIONS_ARE_DEFINED ]; then echo $0: Functions not defined. Aborting; logger $0: Functions not defined. Aborting; exit 1; fi
	if [ ! $VARIABLES_ARE_DEFINED ]; then echo $0: Variables not defined. Aborting; logger $0: Variables not defined. Aborting; exit 1; fi


# POSSIBLE OPTION: USE IF YOU WANT
# Require root
	f_require_root

touch /etc/public-ipv4 /etc/public-ipv6
v4_On_File=$(cat /etc/public-ipv4 2> /dev/null)
v6_On_File=$(cat /etc/public-ipv6 2> /dev/null)
v4_Now=$(curl -s4 ifconfig.me.noexist/ip 2> /dev/null) ; EN4=$?
v6_Now=$(curl -s6 ifconfig.me/ip 2> /dev/null) ; EN6=$?

# get DYNU_LOGIN and DYNU_PWD definitions
	source $ADMIN_HOME_DIR/.dynu.com

if [ "$v4_On_File" != "$v4_Now" ] && ! $(f_is_valid_ipv4_address "$v4_Now") && \\
	[ "$DMZ_HOST" == "$HOSTNAME" ] && [ $EN4 -eq 0 ] ; then
		message="IPv4 on $HOST_FQDN: '$v4_On_File' to '$v4_Now'. "
		message="$message Manual update to A record required. $(date)"
		echo && echo && echo $message
		echo $message | mail -s"$HOST_FQDN update" $ADMIN_CELL_EMAIL $ADMIN_EMAIL
		echo "$v4_Now" > /etc/public-ipv4
		chmod 644 /etc/public-ipv4
		fi

if [ "$v6_On_File" != "$v6_Now" ] && validation::ipv6 "$v6_Now" && [ $EN6 -eq 0 ] ; then
	message="IPv6 on $HOST_FQDN: '$v6_On_File' to '$v6_Now'. "
	message="$message Manual update to AAAA record required. $(date)"
	echo $message
	echo $message | mail -s"$HOST_FQDN update" $ADMIN_CELL_EMAIL $ADMIN_EMAIL
	echo "$v6_Now" > /etc/public-ipv6
	chmod 644 /etc/public-ipv6
	fi

# Include script footer file
	f_debug_variable "script_footer" "${PATHNAME[script_footer]}"
	source "${PATHNAME[script_footer]}"

exit 0

