#!/bin/bash

# Include script setup file
	source script-setup
	if [ ! $FUNCTIONS_ARE_DEFINED ]; then echo $0: Functions not defined. Aborting; logger $0: Functions not defined. Aborting; exit 1; fi
	if [ ! $VARIABLES_ARE_DEFINED ]; then echo $0: Variables not defined. Aborting; logger $0: Variables not defined. Aborting; exit 1; fi


# POSSIBLE OPTION: USE IF YOU WANT
# Require root
	f_require_root

touch /etc/public-ipv4 /etc/public-ipv6
v4_On_File=$(cat /etc/public-ipv4 2> /dev/null)
v6_On_File=$(cat /etc/public-ipv6 2> /dev/null)
v4_Now=$(curl -s4 ifconfig.me/ip 2> /dev/null)
v6_Now=$(curl -s6 ifconfig.me/ip 2> /dev/null)

# get DYNU_LOGIN and DYNU_PWD definitions
	source $ADMIN_HOME_DIR/.dynu.com

echo HOST_FQDN $HOST_FQDN
echo DYNU_LOGIN $DYNU_LOGIN
echo DYNU_PWD $DYNU_PWD
echo v4_On_File $v4_On_File
echo v6_On_File $v6_On_File
echo v4_Now $v4_Now
echo v6_Now $v6_Now
echo curl "https://api.dynu.com/nic/update?username=$DYNU_LOGIN&password=$DYNU_PWD&hostname=$HOST_FQDN&myip=$v4_Now"
echo curl "https://api.dynu.com/nic/update?username=$DYNU_LOGIN&password=$DYNU_PWD&hostname=$HOST_FQDN&myipv6=$v6_Now"

if [ "$v4_On_File" != "$v4_Now" ] ; then
	if [ "$v4_Now" != "" ] ; then
#		if [ "$DMZ_HOST" == "$HOSTNAME" ] ; then
			message="IPv4 address on $HOST_FQDN has changed to $v4_Now. Updating DDNS."
			echo && echo && echo $message
			echo $message | mail -s"$HOST_FQDN update" $ADMIN_CELL_EMAIL $ADMIN_EMAIL
			# Updating IPv4 address on dynu.com
			echo curl "https://api.dynu.com/nic/update?username=$DYNU_LOGIN&password=$DYNU_PWD&hostname=$HOST_FQDN&myip=$v4_Now"
			curl "https://api.dynu.com/nic/update?username=$DYNU_LOGIN&password=$DYNU_PWD&hostname=$HOST_FQDN&myip=$v4_Now"
			if $? ; then
					message="IPv4 address update on $HOST_FQDN FAILED."
					echo $message
					echo $message | mail -s"$HOST_FQDN update" $ADMIN_CELL_EMAIL $ADMIN_EMAIL
				else
					echo "$v4_Now" > /etc/public-ipv4
				fi
			echo
#			fi
		fi
	fi

if [ "$v6_On_File" != "$v6_Now" ] ; then
	if [ "$v6_Now" != "" ] ; then
		message="IPv6 address on $HOST_FQDN has changed to $v6_Now. Updating DDNS."
		echo && echo && echo $message
		echo $message | mail -s"$HOST_FQDN update" $ADMIN_CELL_EMAIL $ADMIN_EMAIL
		# Updating IPv6 address on dynu.com
		echo curl "https://api.dynu.com/nic/update?password=$DYNU_PWD&hostname=$HOST_FQDN&myipv6=$v6_Now"
		curl "https://api.dynu.com/nic/update?username=$DYNU_LOGIN&password=$DYNU_PWD&hostname=$HOST_FQDN&myipv6=$v6_Now"
		if $? ; then
				message="IPv6 address update on $HOST_FQDN FAILED."
				echo $message
				echo $message | mail -s"$HOST_FQDN update" $ADMIN_CELL_EMAIL $ADMIN_EMAIL
			else
				echo "$v6_Now" > /etc/public-ipv6
			fi
		echo
		fi
	fi

# Include script footer file
	f_debug_variable "script_footer" "${PATHNAME[script_footer]}"
	source "${PATHNAME[script_footer]}"

exit 0

