#!/bin/bash
# syncvault

# Include header file
PROGRAM_DIRECTORY=$(dirname $0)
source $PROGRAM_DIRECTORY/script-setup

BASEDIR='~/cryfs-basedir'
MOUNTDIR='~/vault'

# Close local vault
sudo -u $USER_ME cryfs-unmount $MOUNTDIR
if [ $? -ne 0 ]
then
  echo "Could not close $MOUNTDIR on localhost."
fi
