#!/bin/bash
# cold-backup

# Include script setup file
	source script-setup
	if [ ! $FUNCTIONS_ARE_DEFINED ]; then echo $0: Functions not defined. Aborting; logger $0: Functions not defined. Aborting; exit 1; fi
	if [ ! $VARIABLES_ARE_DEFINED ]; then echo $0: Variables not defined. Aborting; logger $0: Variables not defined. Aborting; exit 1; fi

# Stop services as needed
	systemctl stop $COLD_PROTECTED_SERVICES

# Store current directory and switch to root
CURRENT_DIRECTORY="$(pwd)"
cd /

if [ $COLD_BACKUP_FS_READ_ONLY ]; then
	f_mount_ro_fs_as_rw "$COLD_BACKUP_FILE_SYSTEM"
	fi

# Make container directory
mkdir -p "$COLD_BACKUP_DIRECTORY"

# Do backup with rsync
# rsync options used
#    -a = archive mode, equivalent to -rlptgoD
#    -g = preserve group ownership
#    -l = recreate symlinks on destination
#    -n = dry run
#    -o = preserve owner
#    -p = preserve permissions
#    -q = quiet
#    -r = recursive (includes subdirectories)
#    -t = preserve modification times
#    -v = verbose
#    -D = preserve device files and special files
#    -E = preserve executability
#    -R = use relative paths (see https://linux.die.net/man/1/rsync for more info)
#    --delete = delete extraneous files from dest dirs
rsync -aloprtvER --delete $COLD_BACKUP_SOURCES "$COLD_BACKUP_DIRECTORY"

# Restore working directory
cd "$CURRENT_DIRECTORY"

if [ $COLD_BACKUP_FS_READ_ONLY ]; then
	f_mount_ro_fs_as_ro "$COLD_BACKUP_FILE_SYSTEM" $COLD_BACKUP_FS_READ_ONLY
	fi

# Start services as needed
	systemctl start $COLD_PROTECTED_SERVICES

# Update log
	echo
	echo Backup completed $(/bin/date '+%Y-%m-%d-%H-%M-%S-%Z')
	echo Backup completed $(/bin/date '+%Y-%m-%d-%H-%M-%S-%Z') >> $COLD_BACKUP_LOG

# Include script footer file
	f_debug_variable "script_footer" "${PATHNAME[script_footer]}"
	source "${PATHNAME[script_footer]}"

exit 0
