#!/bin/bash

DEBUG_MODE=true; if ! $DEBUG_MODE ; then echo "DEBUG EXECUTING $0 line ${LINENO}" $(date +"%F %T.%3N %Z") ; fi
# if ! $DEBUG_MODE ; then echo "DEBUG MARKER $0 line ${LINENO}" $(date +"%F %T.%3N %Z") ; fi

# Include script setup file
	source script-setup
	if [ ! $FUNCTIONS_ARE_DEFINED ]; then echo $0: Functions not defined. Aborting; logger $0: Functions not defined. Aborting; exit 1; fi
	if [ ! $VARIABLES_ARE_DEFINED ]; then echo $0: Variables not defined. Aborting; logger $0: Variables not defined. Aborting; exit 1; fi


# POSSIBLE OPTION: USE IF YOU WANT
# Require root
	f_require_root

# Ensure that a target directory has been specified
	if [ "$1" == "" ]; then
		f_die "No target directory specified."
		fi

# Do stuff here
if ! $DEBUG_MODE ; then echo "DEBUG MARKER $0 line ${LINENO}" $(date +"%F %T.%3N %Z") ; fi
	mkdir "$1"
	cp /var/lib/mysql/ca-key.pem "$1"
	cp /var/lib/mysql/ca.pem "$1"
	cp /var/lib/mysql/client-cert.pem "$1"
	cp /var/lib/mysql/client-key.pem "$1"
	cp /var/lib/mysql/private_key.pem "$1"
	cp /var/lib/mysql/public_key.pem "$1"
	cp /var/lib/mysql/server-cert.pem "$1"
	cp /var/lib/mysql/server-key.pem "$1"

if ! $DEBUG_MODE ; then echo "DEBUG ENDING $0 line ${LINENO}" $(date +"%F %T.%3N %Z" ; fi

# Include script footer file
	f_debug_variable "script_footer" "${PATHNAME[script_footer]}"
	source "${PATHNAME[script_footer]}"

exit 0

