#!/bin/bash

DEBUG_MODE=false; if $DEBUG_MODE ; then echo "DEBUG EXECUTING $0 line ${LINENO}" $(date +"%F %T.%3N %Z") ; fi
# if $DEBUG_MODE ; then echo "DEBUG MARKER $0 line ${LINENO}" $(date +"%F %T.%3N %Z") ; fi

# Include script setup file
	source script-setup
	if [ ! $FUNCTIONS_ARE_DEFINED ]; then echo $0: Functions not defined. Aborting; logger $0: Functions not defined. Aborting; exit 1; fi
	if [ ! $VARIABLES_ARE_DEFINED ]; then echo $0: Variables not defined. Aborting; logger $0: Variables not defined. Aborting; exit 1; fi


# POSSIBLE OPTION: USE IF YOU WANT
# Require root
	# f_require_root

# POSSIBLE OPTION: USE IF YOU WANT
# Require a specific host
	# f_require_host [HOST]

# CHECK FOR ENOUGH ARGUMENTS (change 0 to minimum arguments and flesh out Usage)
if [ $# -lt 1 ]; 
    then echo "$EXIT_CODE_DESC_DIRECTORY_NOT_FOUND"
	echo "Usage: $(basename $0) VIDEO_FILE_NAME"
	exit $EXIT_CODE_DIRECTORY_NOT_FOUND
fi

# Do stuff here
if $DEBUG_MODE ; then echo "DEBUG MARKER $0 line ${LINENO}" $(date +"%F %T.%3N %Z") ; fi

Filename="$1"

if ! [ -f "$Filename" ] ; then 
    echo "$START_DATEANDTIMESTAMP $Filename is not a file."
    exit -1
    fi

if ! [ $(exiftool -api largefilesupport=1 -s3 -MIMEType "$Filename" | cut -c1-5) = "video" ] ; then 
    echo "$START_DATEANDTIMESTAMP $Filename is not a video file."
    exit -1
    fi

if ! [ -w "$Filename" ] ; then 
    echo "$START_DATEANDTIMESTAMP $Filename is not writable."
    exit -1
    fi

if [ "X"$(exiftool -api largefilesupport=1 -s3 -Encoder "$Filename" | cut -c1-9) = "XHandBrake" ] ; then 
    echo "$START_DATEANDTIMESTAMP $Filename already rendered by HandBrake."
    exit -1
    fi

HandbrakePreset="/etc/HandBrake/Lane-2024-07-04.json"
echo "$START_DATEANDTIMESTAMP $Filename re-rendering started."
HandBrakeCLI --preset-import-file "$HandbrakePreset" -i "$Filename" -o "/tmp/$UUID" >> /dev/null 2>> /dev/null
if ! [ $? ] ; then 
    echo "$START_DATEANDTIMESTAMP $Filename re-rendering FAILED."
    exit -1
    fi
exiftool -api largefilesupport=1 -Comment="$HandbrakePreset" "/tmp/$UUID"
if ! [ $? ] ; then 
    echo "$START_DATEANDTIMESTAMP $Filename exif comment add FAILED."
    exit -1
    fi
rm "$Filename"
mv "/tmp/$UUID" $(f_replace_ext "$Filename" "mp4")
if ! [ $? ] ; then 
    echo "$START_DATEANDTIMESTAMP $Filename overwrite from temp file FAILED."
    exit -1
    fi
echo "$START_DATEANDTIMESTAMP $Filename successfully re-rendered."

if $DEBUG_MODE ; then echo "DEBUG ENDING $0 line ${LINENO}" $(date +"%F %T.%3N %Z") ; fi

# Include script footer file
	f_debug_variable "script_footer" "${PATHNAME[script_footer]}"
	source "${PATHNAME[script_footer]}"

exit 0

