#!/bin/bash

DEBUG_MODE=false; if $DEBUG_MODE ; then echo "DEBUG EXECUTING $0 line ${LINENO}" $(date +"%F %T.%3N %Z") ; fi
# if $DEBUG_MODE ; then echo "DEBUG MARKER $0 line ${LINENO}" $(date +"%F %T.%3N %Z") ; fi

# Include script setup file
	source script-setup
	if [ ! $FUNCTIONS_ARE_DEFINED ]; then echo $0: Functions not defined. Aborting; logger $0: Functions not defined. Aborting; exit 1; fi
	if [ ! $VARIABLES_ARE_DEFINED ]; then echo $0: Variables not defined. Aborting; logger $0: Variables not defined. Aborting; exit 1; fi


# Uncomment requirements for script execution
     # f_require_root
    # f_require_ubuntu
    # f_deprecated
    # f_require_minimum_version_number "version-number"
    # f_require_maximum_version_number "version-number"
    # f_only_on_server "hostname"
    # f_require_confirmation "This text is displayed, requesting confirmation word." "ConfirmationWord"
    # set -x # For debugging

# POSSIBLE OPTION: USE IF YOU WANT
# Require root
	f_require_root

# POSSIBLE OPTION: USE IF YOU WANT
# Require a specific host
	f_require_host dsm1

# CHECK FOR ENOUGH ARGUMENTS (change 0 to minimum arguments and flesh out Usage)
if [ $# -lt 0 ]; 
    then echo "$EXIT_CODE_DESC_DIRECTORY_NOT_FOUND"
	echo "Usage: $(basename $0)" 
	exit $EXIT_CODE_DIRECTORY_NOT_FOUND
fi

# Do stuff here
if $DEBUG_MODE ; then echo "DEBUG MARKER $0 line ${LINENO}" $(date +"%F %T.%3N %Z") ; fi

templog="/tmp/compress-with-hevc.log"

date | tee -a "$templog"
echo "START" | tee -a "$templog"
df -h | tee -a "$templog"

_apply-plex-permissions | tee -a "$templog"
compress-with-hevc-dir /home/lhensley/plex
# compress-with-hevc-dir /mnt/4TBA/plex
# compress-with-hevc-dir /mnt/12TBA/plex
# _apply-plex-permissions | tee -a "$templog"

SOURCEBASE="/home/lhensley/plex/Inbox/TV Shows"
TARGETBASE="/mnt/12TBA/plex/TV Shows/Regular"

SOURCE="$SOURCEBASE/Alfred Hitchcock Hour (1962)"
TARGET="$TARGETBASE/The Alfred Hitchcock Hour (1962) {tvdb=74488}"
rsync -avuE --progress "$SOURCE"/* "$TARGET" | tee -a "$templog"
rm -r "$SOURCE"

SOURCE="$SOURCEBASE/Bonanza (1959) {tvdb=73378}"
TARGET="$TARGETBASE/Bonanza (1959) {tvdb=73378}"
rsync -avuE --progress "$SOURCE"/* "$TARGET" | tee -a "$templog"
rm -r "$SOURCE"

SOURCE="$SOURCEBASE/Carol Burnett and Friends (1972) {tvdb=77645}"
TARGET="$TARGETBASE/Carol Burnett and Friends (1972) {tvdb=77645}"
rsync -avuE --progress "$SOURCE"/* "$TARGET" | tee -a "$templog"
rm -r "$SOURCE"

SOURCE="$SOURCEBASE/Criminal Minds (2005) {tvdb=75710}"
TARGET="$TARGETBASE/Criminal Minds (2005) {tvdb=75710}"
rsync -avuE --progress "$SOURCE"/* "$TARGET" | tee -a "$templog"
rm -r "$SOURCE"

SOURCE="$SOURCEBASE/Father Brown (2013) {tvdb=265834}"
TARGET="$TARGETBASE/Father Brown (2013) {tvdb=265834}"
rsync -avuE --progress "$SOURCE"/* "$TARGET" | tee -a "$templog"
rm -r "$SOURCE"

SOURCE="$SOURCEBASE/Good Times (1974) {tvdb=77357}"
TARGET="$TARGETBASE/Good Times (1974) {tvdb=77357}"
rsync -avuE --progress "$SOURCE"/* "$TARGET" | tee -a "$templog"
rm -r "$SOURCE"

SOURCE="$SOURCEBASE/Green Acres (1965) {tvdb=78101}"
TARGET="$TARGETBASE/Green Acres (1965) {tvdb=78101}"
rsync -avuE --progress "$SOURCE"/* "$TARGET" | tee -a "$templog"
rm -r "$SOURCE"

SOURCE="$SOURCEBASE/Hawaii Five-0 (1968)"
TARGET="$TARGETBASE/Hawaii Five-0 (2010) {tvdb=164541}"
rsync -avuE --progress "$SOURCE"/* "$TARGET" | tee -a "$templog"
rm -r "$SOURCE"

SOURCE="$SOURCEBASE/I Dream Of Jeannie (1965) {tvdb=77388}"
TARGET="$TARGETBASE/I Dream Of Jeannie (1965) {tvdb=77388}"
rsync -avuE --progress "$SOURCE"/* "$TARGET" | tee -a "$templog"
rm -r "$SOURCE"

SOURCE="$SOURCEBASE/Interview With a Killer (2024) {tvdb=455903}"
TARGET="$TARGETBASE/Interview With a Killer (2024) {tvdb=455903}"
rsync -avuE --progress "$SOURCE"/* "$TARGET" | tee -a "$templog"
rm -r "$SOURCE"

SOURCE="$SOURCEBASE/Interview With a Killer (2024)"
TARGET="$TARGETBASE/Interview With a Killer (2024) {tvdb=455903}"
rsync -avuE --progress "$SOURCE"/* "$TARGET" | tee -a "$templog"
rm -r "$SOURCE"

SOURCE="$SOURCEBASE/Law & Order (1990) {tvdb=72368}"
TARGET="$TARGETBASE/Law & Order (1990) {tvdb=72368}"
rsync -avuE --progress "$SOURCE"/* "$TARGET" | tee -a "$templog"
rm -r "$SOURCE"

SOURCE="$SOURCEBASE/Law & Order Criminal Intent (2001) {tvdb=71489}"
TARGET="$TARGETBASE/Law & Order Criminal Intent (2001) {tvdb=71489}"
rsync -avuE --progress "$SOURCE"/* "$TARGET" | tee -a "$templog"
rm -r "$SOURCE"

SOURCE="$SOURCEBASE/Law & Order Special Victims Unit (1999) {tvdb=75692}"
TARGET="$TARGETBASE/Law & Order Special Victims Unit (1999) {tvdb=75692}"
rsync -avuE --progress "$SOURCE"/* "$TARGET" | tee -a "$templog"
rm -r "$SOURCE"

SOURCE="$SOURCEBASE/Sanford & Son (1972)"
TARGET="$TARGETBASE/Sanford and Son (1972) {tvdb=78193}"
rsync -avuE --progress "$SOURCE"/* "$TARGET" | tee -a "$templog"
rm -r "$SOURCE"

SOURCE="$SOURCEBASE/Sanford and Son (1972) {tvdb=78193}"
TARGET="$TARGETBASE/Sanford and Son (1972) {tvdb=78193}"
rsync -avuE --progress "$SOURCE"/* "$TARGET" | tee -a "$templog"
rm -r "$SOURCE"

SOURCE="$SOURCEBASE/Saturday Night Live (1975) {tvdb=76177}"
TARGET="$TARGETBASE/Saturday Night Live (1975) {tvdb=76177}"
rsync -avuE --progress "$SOURCE"/* "$TARGET" | tee -a "$templog"
rm -r "$SOURCE"

SOURCE="$SOURCEBASE/Soap (1977) {tvdb=77370}"
TARGET="$TARGETBASE/Soap (1977) {tvdb=77370}"
rsync -avuE --progress "$SOURCE"/* "$TARGET" | tee -a "$templog"
rm -r "$SOURCE"

SOURCE="$SOURCEBASE/Star Trek The Next Generation (1987) {tvdb=71470}"
TARGET="$TARGETBASE/Star Trek The Next Generation (1987) {tvdb=71470}"
rsync -avuE --progress "$SOURCE"/* "$TARGET" | tee -a "$templog"
rm -r "$SOURCE"

SOURCE="$SOURCEBASE/Superman & Lois (2021) {tvdb=375655}"
TARGET="$TARGETBASE/Superman & Lois (2021) {tvdb=375655}"
rsync -avuE --progress "$SOURCE"/* "$TARGET" | tee -a "$templog"
rm -r "$SOURCE"

SOURCE="$SOURCEBASE/The Adventures of Superman (1952)"
TARGET="$TARGETBASE/Adventures of Superman (1952) {tvdb=77403}"
rsync -avuE --progress "$SOURCE"/* "$TARGET" | tee -a "$templog"
rm -r "$SOURCE"

SOURCE="$SOURCEBASE/The Alfred Hitchcock Hour (1962) {tvdb=74488}"
TARGET="$TARGETBASE/The Alfred Hitchcock Hour (1962) {tvdb=74488}"
rsync -avuE --progress "$SOURCE"/* "$TARGET" | tee -a "$templog"
rm -r "$SOURCE"

SOURCE="$SOURCEBASE/The Beverly Hillbillies (1962) {tvdb=71471}"
TARGET="$TARGETBASE/The Beverly Hillbillies (1962) {tvdb=71471}"
rsync -avuE --progress "$SOURCE"/* "$TARGET" | tee -a "$templog"
rm -r "$SOURCE"

SOURCE="$SOURCEBASE/The Brady Bunch (1969) {tvdb=77010}"
TARGET="$TARGETBASE/The Brady Bunch (1969) {tvdb=77010}"
rsync -avuE --progress "$SOURCE"/* "$TARGET" | tee -a "$templog"
rm -r "$SOURCE"

SOURCE="$SOURCEBASE/The Fugitive (1963) {tvdb=75258}"
TARGET="$TARGETBASE/The Fugitive (1963) {tvdb=75258}"
rsync -avuE --progress "$SOURCE"/* "$TARGET" | tee -a "$templog"
rm -r "$SOURCE"

SOURCE="$SOURCEBASE/The Irrational (2023) {tvdb=428894}"
TARGET="$TARGETBASE/The Irrational (2023) {tvdb=428894}"
rsync -avuE --progress "$SOURCE"/* "$TARGET" | tee -a "$templog"
rm -r "$SOURCE"

SOURCE="$SOURCEBASE/The Love Boat (1977) {tvdb=76954}"
TARGET="$TARGETBASE/The Love Boat (1977) {tvdb=76954}"
rsync -avuE --progress "$SOURCE"/* "$TARGET" | tee -a "$templog"
rm -r "$SOURCE"

SOURCE="$SOURCEBASE/The Powers of Matthew Star (1982) {tvdb=78295}"
TARGET="$TARGETBASE/The Powers of Matthew Star (1982) {tvdb=78295}"
rsync -avuE --progress "$SOURCE"/* "$TARGET" | tee -a "$templog"
rm -r "$SOURCE"

SOURCE="$SOURCEBASE/The Simpsons (1989) {tvdb=71663}"
TARGET="$TARGETBASE/The Simpsons (1989) {tvdb=71663}"
rsync -avuE --progress "$SOURCE"/* "$TARGET" | tee -a "$templog"
rm -r "$SOURCE"

SOURCE="$SOURCEBASE/The Universe (2007)"
TARGET="$TARGETBASE/The Universe (2007) {tvdb=80198}"
rsync -avuE --progress "$SOURCE"/* "$TARGET" | tee -a "$templog"
rm -r "$SOURCE"

SOURCE="$SOURCEBASE/The Universe (2007) {tvdb=80198}"
TARGET="$TARGETBASE/The Universe (2007) {tvdb=80198}"
rsync -avuE --progress "$SOURCE"/* "$TARGET" | tee -a "$templog"
rm -r "$SOURCE"

SOURCE="$SOURCEBASE/The Wild Wild West (1965)"
TARGET="$TARGETBASE/The Wild, Wild West (1965) {tvdb=71637}"
rsync -avuE --progress "$SOURCE"/* "$TARGET" | tee -a "$templog"
rm -r "$SOURCE"

SOURCE="$SOURCEBASE/The Wild, Wild West (1965) {tvdb=71637}"
TARGET="$TARGETBASE/The Wild, Wild West (1965) {tvdb=71637}"
rsync -avuE --progress "$SOURCE"/* "$TARGET" | tee -a "$templog"
rm -r "$SOURCE"

SOURCE="$SOURCEBASE/Welcome Back Kotter (1975)"
TARGET="$TARGETBASE/Welcome Back Kotter (1975) {tvdb=78572}"
rsync -avuE --progress "$SOURCE"/* "$TARGET" | tee -a "$templog"
rm -r "$SOURCE"

SOURCE="$SOURCEBASE/Wings (1990) {tvdb=71962}"
TARGET="$TARGETBASE/Wings (1990) {tvdb=71962}"
rsync -avuE --progress "$SOURCE"/* "$TARGET" | tee -a "$templog"
rm -r "$SOURCE"

# compress-with-hevc-dir /mnt/4TBA/plex
# compress-with-hevc-dir /mnt/12TBA/plex
# plex-sync # DON'T DO THIS AUTOMATICALLY. WHAT IF ORIGINAL IS DAMAGED?

_apply-plex-permissions | tee -a "$templog"
date | tee -a "$templog"
echo "END" | tee -a "$templog"

if $DEBUG_MODE ; then echo "DEBUG ENDING $0 line ${LINENO}" $(date +"%F %T.%3N %Z") ; fi

# Include script footer file
	f_debug_variable "script_footer" "${PATHNAME[script_footer]}"
	source "${PATHNAME[script_footer]}"

exit 0

