#!/bin/bash
# dvr-processing

# Include script setup file
	source script-setup
	f_require_true "$FUNCTIONS_ARE_DEFINED" "true" "$0: ABORTED. Functions not defined."
	f_require_true "$VARIABLES_ARE_DEFINED" "true" "$0: ABORTED. Variables not defined."

# Verify essential files and directories
	f_require_directory "$VIDEO_WORK_DIRECTORY" "true"
	f_require_directory "$VIDEO_STORE_DIRECTORY" "true"

	while true; do
		find "$VIDEO_WORK_DIRECTORY" -type f -name "*.ts" -exec f_process_ts_file "{}" "$VIDEO_WORK_DIRECTORY" "$VIDEO_STORE_DIRECTORY" \
		sleep
	done

# Include script footer file
	f_debug_variable "script_footer" "${PATHNAME[script_footer]}"
	source "${PATHNAME[script_footer]}"

exit 1