#!/bin/bash
# See https://en.wikipedia.org/wiki/E.123
# Probably OK do dump (or archive) this.

# Include script setup file
	source script-setup
	if [ ! $FUNCTIONS_ARE_DEFINED ]; then echo $0: Functions not defined. Aborting; logger $0: Functions not defined. Aborting; exit 1; fi
	if [ ! $VARIABLES_ARE_DEFINED ]; then echo $0: Variables not defined. Aborting; logger $0: Variables not defined. Aborting; exit 1; fi

INPUT_STRING="ABC# .1-2;-3akas,idf+j8"
OUTPUT_STRING=$(echo $INPUT_STRING | sed 's/[^+,;0-9]//g')
echo $OUTPUT_STRING

# Include script footer file
	f_debug_variable "script_footer" "${PATHNAME[script_footer]}"
	source "${PATHNAME[script_footer]}"

exit 0

