#!/bin/bash

# Include script setup file
	source script-setup
	if [ ! $FUNCTIONS_ARE_DEFINED ]; then echo $0: Functions not defined. Aborting; logger $0: Functions not defined. Aborting; exit 1; fi
	if [ ! $VARIABLES_ARE_DEFINED ]; then echo $0: Variables not defined. Aborting; logger $0: Variables not defined. Aborting; exit 1; fi


# POSSIBLE OPTION: USE IF YOU WANT
# Require root
#	f_require_root

# Do stuff here
TEMP_DB="liturgy"
mysqldump --host=localhost --port=3306 --default-character-set=utf8 \
    --protocol=tcp --column-statistics=FALSE --routines --events \
    --databases $TEMP_DB > $ADMIN_HOME_DIR/$TEMP_DB-$START_WEEKDAYSTAMP.sql

# Include script footer file
	f_debug_variable "script_footer" "${PATHNAME[script_footer]}"
	source "${PATHNAME[script_footer]}"

exit 0

