#!/bin/bash

DEBUG_MODE=false; if $DEBUG_MODE ; then echo "DEBUG EXECUTING $0 line ${LINENO}" $(date +"%F %T.%3N %Z") ; fi

# Do stuff here
if $DEBUG_MODE ; then echo "DEBUG MARKER $0 line ${LINENO}" $(date +"%F %T.%3N %Z") ; fi

search_string="$1"
file="$2"
delimiter=":"
field_number=1

# CHECK FOR ENOUGH ARGUMENTS
if [ $# -lt 2 ]; then
    echo "$(basename $0): Not enough arguments" >&2
	echo "Usage: $(basename $0) string-to-find file-to-search [start-byte-number]" >&2
    echo "Purpose: Displays the byte position of the first instance of a string in a file." >&2
    echo "First byte of the file is 1, not 0." >&2
	exit 1
    fi

if [ ! -f "$file" ]; then  # Check whether $file is not a regular file
    echo "$(basename $0): $file: File not found." >&2
	echo "Usage: $(basename $0) string-to-find file-to-search [start-byte-number]" >&2
    echo "Purpose: Displays the byte position of the first instance of a string in a file." >&2
    echo "First byte of the file is 1, not 0." >&2
    exit 169
    fi

if [ $# -gt 2 ] ; then
    if [[ ! "$3" =~ ^-?[0-9]+$ ]] || [ ! $3 -gt 0 ]; then
        echo "$(basename $0): If specified, the start-byte-number must be an integer greater than zero." >&2
        echo "Usage: $(basename $0) string-to-find file-to-search [start-byte-number]" >&2
        echo "Purpose: Displays the byte position of the first instance of a string in a file." >&2
        echo "First byte of the file is 1, not 0." >&2
        exit 22
        fi
    fi

if $DEBUG_MODE ; then echo "DEBUG ENDING $0 line ${LINENO}" $(date +"%F %T.%3N %Z") ; fi

start_byte=1
if [ $# -gt 2 ]; then
    if [ $3 -gt 0 ]; then
        start_byte="$3"
        fi
    fi

grepresult=$(tail -c+"$start_byte" "$file" | grep -abo "$search_string" | head -1 )
result=$(($(echo "$grepresult" | cut -d "$delimiter" -f "$field_number") + "$start_byte" ))
echo $result

exit 0
