#!/bin/bash
# get-config
# Usage: get-config <config-name> <primary-config-file> [<alternate-config-file>]

config-name="$1"
input="$2"
# IFS=$'[ \t]*=[ \t]*'
IFS="="
declare -A config
while read -r name value
do
	config[$name]="$value"
	echo "#$name#$value#"
done < "$input"

echo ""
echo config["$config-name"]
echo ""

exit 0
