#!/bin/bash
# get-config
# Usage: get-config <config-name> <primary-config-file> [<alternate-config-file>]
# Ref: https://unix.stackexchange.com/questions/505258/parse-config-file-and-pass-parameters-to-another-script

CONFIG_NAME="$1"
INPUT="$2"
IFS=$'[ \t]*=[ \t]*'
# IFS="="
declare -A CONFIG
while read -r NAME VALUE
do	
	if [ "$NAME" != "" ]; then
	 	CONFIG[$NAME]="$VALUE"
		echo "#$NAME#$VALUE#"
		echo "<next>"
	fi
done < "$INPUT"

echo ""
echo ${CONFIG[CONFIG_NAME]}
echo ""

exit 0
