#!/bin/bash

# Include script setup file
	source script-setup
	if [ ! $FUNCTIONS_ARE_DEFINED ]; then echo $0: Functions not defined. Aborting; logger $0: Functions not defined. Aborting; exit 1; fi
	if [ ! $VARIABLES_ARE_DEFINED ]; then echo $0: Variables not defined. Aborting; logger $0: Variables not defined. Aborting; exit 1; fi


# POSSIBLE OPTION: USE IF YOU WANT
# Require root
	f_require_root

# Runs only on nuc01
	f_require_host "nuc01"

# Do stuff here
	TEMPFILE="/tmp/files-in-plex-dvr-directory-$(uuidgen)"
	OUTFILE="~/dvr-files.txt"
	find "$VIDEO_STORE_DIRECTORY" -type f > "$TEMPFILE"
	rm -f "$OUTFILE"
	cat "$TEMPFILE" | while read in; do echo $(stat -c "%s" "$in")$'\t'$in >> "$OUTFILE"; done
	rm -f "$TEMPFILE"

# Include script footer file
	f_debug_variable "script_footer" "${PATHNAME[script_footer]}"
	source "${PATHNAME[script_footer]}"

exit 0

