#!/bin/bash
# get-config
# Usage: get-config <config-name> <primary-config-file> [<alternate-config-file>]
# Ref: https://unix.stackexchange.com/questions/505258/parse-config-file-and-pass-parameters-to-another-script

CONFIG_NAME="$1"
INPUT="$2"
IFS=$'[ \t]*=[ \t]*'
# IFS="="
declare -A CONFIG
while read -r NAME VALUE
do	
	if [ "$NAME" != "" ] && [[ "$NAME" != "#"* ]]; then # Line is not blank and is not a comment
	 	CONFIG[$NAME]="$VALUE"
		# echo "#$NAME#$VALUE#"
		# echo "<next>"
	fi
done < "$INPUT"

# Ref https://stackoverflow.com/questions/3601515/how-to-check-if-a-variable-is-set-in-bash
if [ -z ${CONFIG[$CONFIG_NAME]+x} ]; then # The requested config is undefined
	exit 1
	fi
echo ${CONFIG[$CONFIG_NAME]}
exit 0
