#!/bin/bash
# hot-restore

# Include script setup file
	source script-setup
	if [ ! $FUNCTIONS_ARE_DEFINED ]; then echo $0: Functions not defined. Aborting; logger $0: Functions not defined. Aborting; fi
	if [ ! $VARIABLES_ARE_DEFINED ]; then echo $0: Variables not defined. Aborting; logger $0: Variables not defined. Aborting; fi

# Confirm that this is what the user wants
	echo -en "\007" # Beep
	echo
	echo "CAUTION CAUTION CAUTION"
	echo
	echo "This will overwrite your current system configuration and data."
	read -p "To continue type the word Restore (case sensitive) and press <ENTER>.  " ANSWER
	if [ "$ANSWER" != "Restore" ]; then
		echo $0: ABORT from user.
		logger $0: ABORT from user.
		fi

# Stop services as needed
	systemctl stop plexmediaserver

# Restore working directory
cd $HOT_BACKUP_DIRECTORY

# Do restore with rsync
# rsync options used
#    -a = archive mode, equivalent to -rlptgoD
#    -g = preserve group ownership
#    -l = recreate symlinks on destination
#    -n = dry run
#    -o = preserve owner
#    -p = preserve permissions
#    -q = quiet
#    -r = recursive (includes subdirectories)
#    -t = preserve modification times
#    -v = verbose
#    -D = preserve device files and special files
#    -E = preserve executability
#    -R = use relative paths (see https://linux.die.net/man/1/rsync for more info)
#    --delete = delete extraneous files from dest dirs
rsync -aoprtvER --delete --exclude=etc/fstab $HOT_BACKUP_SOURCES /

# Restore working directory
cd "$CURRENT_DIRECTORY"

# Start services as needed
	systemctl start plexmediaserver

# Include script footer file
	f_debug_variable "script_footer" "${PATHNAME[script_footer]}"
	source "${PATHNAME[script_footer]}"

exit 0
