#!/bin/bash
# NOTE: This script is intended to be run on a dedicated certificate authority server (i.e., ca).
# Procedure adapted from https://www.digitalocean.com/community/tutorials/how-to-set-up-and-configure-a-certificate-authority-ca-on-ubuntu-20-04

# Include script setup file
	source script-setup
	if [ ! $FUNCTIONS_ARE_DEFINED ]; then echo $0: Functions not defined. Aborting; logger $0: Functions not defined. Aborting; exit 1; fi
	if [ ! $VARIABLES_ARE_DEFINED ]; then echo $0: Variables not defined. Aborting; logger $0: Variables not defined. Aborting; exit 1; fi

# Require root
	f_require_root

# Run apt updates
	f_run_apt_updates

# Install Easy-RSA
	apt-get install -y easy-rsa

# Preparing a Public Key Infrastructure Directory
	mkdir ~/easy-rsa
	ln -s /usr/share/easy-rsa/* ~/easy-rsa/
	chmod 700 /home/$USER/easy-rsa
	cd ~/easy-rsa
	./easyrsa init-pki

# Creating a Certificate Authority
	echo 'set_var EASYRSA_BATCH          "yes"' > vars
	echo 'set_var EASYRSA_REQ_COUNTRY    "US"' >> vars
	echo 'set_var EASYRSA_REQ_PROVINCE   "IA"' >> vars
	echo 'set_var EASYRSA_REQ_CITY       "Des Moines"' >> vars
	echo 'set_var EASYRSA_REQ_ORG        "Hog Heaven DSM"' >> vars
	echo 'set_var EASYRSA_REQ_EMAIL      "root@lanehensley.org"' >> vars
	echo 'set_var EASYRSA_REQ_OU         "CA"' >> vars
	echo 'set_var EASYRSA_REQ_CN         "CA"' >> vars
	echo 'set_var EASYRSA_ALGO           "ec"' >> vars
	echo 'set_var EASYRSA_DIGEST         "sha512"' >> vars
	./easyrsa build-ca nopass

# Fix permissions
	chown -R $USER:$USER ~/easy-rsa

# Display ca.crt location
	sftp nuc01.lanehensley.org <<EOF
	echo "Done. Now copy ONLY ~/easy-rsa/pki/ca.crt to clients and servers."

# Include script footer file
	f_debug_variable "script_footer" "${PATHNAME[script_footer]}"
	source "${PATHNAME[script_footer]}"

exit 0


