#!/bin/bash
# install-ntp
# Assumes Ubuntu 22.04

# IMPORTANT: You don't need this. Ubuntu uses timesyncd to keep time updated.


# Include script setup file
	source script-setup
	if [ ! $FUNCTIONS_ARE_DEFINED ]; then echo $0: Functions not defined. Aborting; logger $0: Functions not defined. Aborting; exit 1; fi
	if [ ! $VARIABLES_ARE_DEFINED ]; then echo $0: Variables not defined. Aborting; logger $0: Variables not defined. Aborting; exit 1; fi

# Require root
	f_require_root

# Some error checking that would help:
	# Confirm that debconf-set-selections with
		# sudo dpkg-query -S /usr/bin/debconf-set-selections

# Install
	# To restart relevant services automatically without prompting the user
		sed -i 's/#$nrconf{restart} = '"'"'i'"'"';/$nrconf{restart} = '"'"'a'"'"';/g' /etc/needrestart/needrestart.conf
	# Update existing Debian packages
		apt-get-update-if-needed
	# Install main package
		apt install ntpdate sntp

# Include script footer file
	f_debug_variable "script_footer" "${PATHNAME[script_footer]}"
	source "${PATHNAME[script_footer]}"

exit 0

