#!/bin/bash

# Include script setup file
	source script-setup
	if [ ! $FUNCTIONS_ARE_DEFINED ]; then echo $0: Functions not defined. Aborting; logger $0: Functions not defined. Aborting; exit 1; fi
	if [ ! $VARIABLES_ARE_DEFINED ]; then echo $0: Variables not defined. Aborting; logger $0: Variables not defined. Aborting; exit 1; fi

# Require root
	f_require_root

# Install VirtualBox Guest Additions
    apt -y update
    apt install -y build-essential linux-headers-$(uname -r)
    mount /dev/cdrom /media
    cd /media
    ./VBoxLinuxAdditions.run
	echo
	echo "YOU MUST REBOOT FOR CHANGES TO TAKE EFFECT."

# Include script footer file
	f_debug_variable "script_footer" "${PATHNAME[script_footer]}"
	source "${PATHNAME[script_footer]}"

exit 0

