#!/bin/bash

# Read all content from the pipe into a variable
# content=$(cat)

echo "$testlane"

if [[ -p /dev/stdin ]] || ! test -t 0 ; then  # Testing for anything at tty or pipe (stdin)
     content=$(cat)
     fi

# Process the content (e.g., print it)
echo "$content"
# echo "Ignoring content."
# echo $(left "$content" 100)

