#!/bin/bash

# Include script setup file
	source script-setup
	if [ ! $FUNCTIONS_ARE_DEFINED ]; then echo $0: Functions not defined. Aborting; logger $0: Functions not defined. Aborting; exit 1; fi
	if [ ! $VARIABLES_ARE_DEFINED ]; then echo $0: Variables not defined. Aborting; logger $0: Variables not defined. Aborting; exit 1; fi


# POSSIBLE OPTION: USE IF YOU WANT
# Require root
	f_require_root

# Do stuff here
	if $(f_is_valid_ipv4_address "149.79.1.1") ; then echo $? A ; fi
	if $(f_is_valid_ipv4_address "invalid") ; then echo $? B ; fi
	if ! $(f_is_valid_ipv4_address "149.79.1.1") ; then echo $? C ; fi
	if ! $(f_is_valid_ipv4_address "invalid") ; then echo $? D ; fi
	echo Done

# Include script footer file
	f_debug_variable "script_footer" "${PATHNAME[script_footer]}"
	source "${PATHNAME[script_footer]}"

exit 0

