#!/bin/bash
# lgh

# Include script setup file
	source script-setup
    source _functions-staging
	if [ ! $FUNCTIONS_ARE_DEFINED ]; then echo $0: Functions not defined. Aborting; logger $0: Functions not defined. Aborting; exit 1; fi
	if [ ! $STAGING_FUNCTIONS_ARE_DEFINED ]; then echo $0: Staging functions not defined. Aborting; logger $0: Variables not defined. Aborting; exit 1; fi
	if [ ! $VARIABLES_ARE_DEFINED ]; then echo $0: Variables not defined. Aborting; logger $0: Variables not defined. Aborting; exit 1; fi

	#   $SOURCE_FILE_NAME_PATTERN  # For Plex DVR, this is "*.ts"
	#                              # For DVDs ripped with MakeMKV, this is "*.mkv"
	#   $TARGET_FILE_EXTENSION     # Normally this is ".m4v"
	#   $SOURCE_ROOT               # For Plex DVR, this is $VIDEO_WORK_DIRECTORY
	#  	     					   # For DVDs ripped with MakeMKV, this is $MAKEMKV_OUTPUT_DIRECTORY
	#   $TARGET_ROOT               # For Plex DVR, this is $VIDEO_STORE_DIRECTORY
	#   $SET_PLEX_PERMISSIONS      # If the output file is part of a Plex Library, this is true; otherwise (default) false
	#   $USE_TV_FILTERS            # Should only be true when converting Plex DVR files. Default is false

    SOURCE_FILE_NAME_PATTERN="*.mp4"
    TARGET_FILE_EXTENSION=".m4v"
    SOURCE_ROOT="/mnt/ext10tb01/Zoom"
    TARGET_ROOT="/mnt/ext10tb01/ZoomTranscoded"
    SET_PLEX_PERMISSIONS=false
    USE_TV_FILTERS=false
    FLATTEN_TARGET_DIRECTORY=true
    USE_PARENT_DIR_AS_BASENAME=false
    PREPEND_PARENT_DIR_TO_BASENAME=false
    APPEND_UUID_TO_TARGET_FILE=false

    # Testing a Plex DVR single iteration
    f_iterate_handbrake_source_video_files "*.ts" "m4v" "$VIDEO_WORK_DIRECTORY" "$VIDEO_STORE_DIRECTORY" true true

    # Looks good to here.
    # NEXT PRIORITY: What about Zoom files where the output file name needs to change to that of parent directory?
    #   zoom_0.mp4; zoom_1? others?
    # Is this an issue for MKV rips also?

    exit 1




    # Tested through Ubuntu 20.04.1
    # Install Plex Media Server
      echo "Installing Plex Media Server"
      rm -rf /etc/apt/sources.list.d/plexmediaserver.list
      echo "# When enabling this repo please remember to add the PlexPublic.Key into the apt setup." > /etc/apt/sources.list.d/plexmediaserver.list
      echo "# wget -q https://downloads.plex.tv/plex-keys/PlexSign.key -O - | sudo apt-key add -" >> /etc/apt/sources.list.d/plexmediaserver.list >> /etc/apt/sources.list.d/plexmediaserver.list
      echo "#" >> /etc/apt/sources.list.d/plexmediaserver.list >> /etc/apt/sources.list.d/plexmediaserver.list
      echo "deb https://downloads.plex.tv/repo/deb/ public main" >> /etc/apt/sources.list.d/plexmediaserver.list >> /etc/apt/sources.list.d/plexmediaserver.list
      wget -q https://downloads.plex.tv/plex-keys/PlexSign.key -O - | sudo apt-key add -
      apt-get -y update
      apt-get install --reinstall -o Dpkg::Options::="--force-confold" plexmediaserver
      # f_install plexmediaserver
      ufw allow 32400/tcp # if not already specified
      echo "Plex Media Server installed."
        # Install Tautulli for https://this-server:8181
        # Ref: https://tautulli.com/
            DEBIAN_FRONTEND=noninteractive apt-get install -yq python python-setuptools tzdata
            cd /opt
            git clone https://github.com/Tautulli/Tautulli.git
            addgroup tautulli && sudo adduser --system --no-create-home tautulli --ingroup tautulli
            cp /opt/Tautulli/init-scripts/init.systemd /lib/systemd/system/tautulli.service
            chown tautulli:tautulli -R /opt/Tautulli
            systemctl daemon-reload
            systemctl enable tautulli.service
            systemctl start tautulli.service
            ufw allow 8181
            cd


  exit 1




set -x

# Make the cold backup file system writable
if [ $COLD_BACKUP_FS_READ_ONLY ]; then
	f_mount_ro_fs_as_rw "$COLD_BACKUP_FILE_SYSTEM"
	fi

# Archive the cold backup
 	mkdir -p "$THIS_ARCHIVE_DIRECTORY"
 	nice tar $BACKUP_OPTIONS $COLD_BACKUP_DIRECTORY
	nice cp "$ARCHIVE_TAR_FULL_WEEKDAY" "$ARCHIVE_TAR_FULL_MONTH"

if [ $COLD_BACKUP_FS_READ_ONLY ]; then
	f_mount_ro_fs_as_ro "$COLD_BACKUP_FILE_SYSTEM" $COLD_BACKUP_FS_READ_ONLY
	fi

set +x

exit 0

f_require_value "MakeMKV Program Path" "${PATHNAME[makemkvcones]}"
f_require_value "MakeMKV Output Directory" "$MAKEMKV_OUTPUT_DIRECTORY"
exit 0


# Include script setup file
	echo ${LINENO}
	source script-setup
	echo ${LINENO}
	if [ ! $FUNCTIONS_ARE_DEFINED ]; then echo $0: Functions not defined. Aborting; logger $0: Functions not defined. Aborting; exit 1; fi
	echo ${LINENO}
	if [ ! $VARIABLES_ARE_DEFINED ]; then echo $0: Variables not defined. Aborting; logger $0: Variables not defined. Aborting; exit 1; fi
	echo ${LINENO}

if [ -z "$1" ]; then
  echo "Usage: rip \"Title (year) [ movie | <minimum_number_of_seconds> ]\" &"
  exit -1
  fi
echo ${LINENO}

if [ -z "$2" ]; then
    MINLENGTH=1200
  else if [ "$2" == "movie" ]; then
    MINLENGTH=4500
    else MINLENGTH=$2
    fi
  fi
echo ${LINENO}

f_require_value "MakeMKV Program Path" "${PATHNAME[makemkvcon]}"
echo ${LINENO}
f_require_value "MakeMKV Output Directory" "$MAKEMKV_OUTPUT_DIRECTORY"
echo ${LINENO}

sudo -u $RUN_AS mkdir -p "$MAKEMKV_OUTPUT_DIRECTORY/$1"
echo ${LINENO}
f_require_directory "$MAKEMKV_OUTPUT_DIRECTORY/$1"
echo ${LINENO}

sudo -u $RUN_AS nice "${PATHNAME[makemkvcon]}" --minlength=$MINLENGTH mkv disc:0 all "$MAKEMKV_OUTPUT_DIRECTORY/$1"
exit_status=$?
f_beep
eject
if [ $exit_status -eq 0 ] ; then
  echo "$1: Disk ripping completed successfully." | mail "$TEXT_ALERTS"
  else echo "$1: Disk ripping FAILED. Code $exit_status" | mail "$TEXT_ALERTS"
  fi





# Include script footer file
	f_debug_variable "script_footer" "${PATHNAME[script_footer]}"
	source "${PATHNAME[script_footer]}"

exit 0