#!/bin/bash
# This script should be run as root from cron, executed at boot time.
# Does NOT remove extraneous files from target directories

# Include script setup file
	source script-setup
	if [ ! $FUNCTIONS_ARE_DEFINED ]; then echo $0: Functions not defined. Aborting; logger $0: Functions not defined. Aborting; exit 1; fi
	if [ ! $VARIABLES_ARE_DEFINED ]; then echo $0: Variables not defined. Aborting; logger $0: Variables not defined. Aborting; exit 1; fi

# Only allow this to run on server oz.
	f_only_on_server "oz"

# Do the looping work
	THIS_SCRIPT=$(basename "$0")
	while true; do
		# Define file locations
			SOURCE_ROOT_DIR="/mnt/ext10tb01/plex/dvr-oz"
			TARGET_ROOT_DIR="/mnt/cloteal/Plex/Pool06-1TB/dvr-nuc01"
			TARGET_SERVER="nuc01.lanehensley.org"
			WAIT_AFTER_SOURCE_SCAN="6h"
			MOVE_MASK="*.m4v"
			EXCLUDE_MASK1="*.ts"
			EXCLUDE_MASK2=".*"
			EXCLUDE_MASK3=".grab/"
		# See https://github.com/lhensley/go/blob/master/documentation/rsync%20options.md
        sudo -u $ADMIN_USER \
			rsync --remove-source-files --include "$MOVE_MASK" \
			--exclude "$EXCLUDE_MASK1" --exclude "$EXCLUDE_MASK2" \
			--exclude "$EXCLUDE_MASK3" -aloprtv \
			"$SOURCE_ROOT_DIR"/* "$TARGET_SERVER:$TARGET_ROOT_DIR" \
			| logger -t "$THIS_SCRIPT"
		f_log_and_echo "Sleeping $WAIT_AFTER_SOURCE_SCAN." false
		sleep "$WAIT_AFTER_SOURCE_SCAN"
        done

# Include script footer file
	f_debug_variable "script_footer" "${PATHNAME[script_footer]}"
	source "${PATHNAME[script_footer]}"

exit 0

