#!/bin/bash
# Looks for for Zoom recordings and transcodes them. Pauses, then repeats forever.
# This script should be run as root from cron, executed at boot time.

# Include script setup file
	source script-setup
	if [ ! $FUNCTIONS_ARE_DEFINED ];         then echo $0: Functions not defined. Aborting; logger $0: Functions not defined. Aborting;         exit 1; fi
	if [ ! $VARIABLES_ARE_DEFINED ];         then echo $0: Variables not defined. Aborting; logger $0: Variables not defined. Aborting;         exit 1; fi

# Set the variables
    WAIT_AFTER_SOURCE_SCAN="1h"                         # How long to wait after looping through all source files
    SOURCE_FILE_NAME_PATTERN="$ZOOM_FILE_NAME_PATTERN"  # For Plex DVR,                 this is "$PLEX_FILE_NAME_PATTERN"              (defined in _vars)
                                                        # For DVDs ripped with MakeMKV, this is "$MAKEMKV_FILE_NAME_PATTERN"           (defined in _vars)
                                                        # For Zoom meeting recordings,  this is "$ZOOM_FILE_NAME_PATTERN"              (defined in _vars)
    SOURCE_ROOT="$ZOOM_RAW_FILES"                       # For Plex DVR, this is "$VIDEO_WORK_DIRECTORY"                                (defined in _vars)
	  	     					                        # For DVDs ripped with MakeMKV, this is "$MAKEMKV_OUTPUT_DIRECTORY"            (defined in _vars)
	  	     					                        # For Zoom meeting recordings, this is "$ZOOM_RAW_FILES"                       (defined in _vars)
    TARGET_ROOT="$ZOOM_TRANSCODED_FILES"                # For Plex DVR, this is "$VIDEO_STORE_DIRECTORY"                               (defined in _vars)
	  	     					                        # For DVDs ripped with MakeMKV, this is "$MAKEMKV_TRANSCODED_FILES_DIRECTORY"  (defined in _vars)
	  	     					                        # For Zoom meeting recordings, this is "$ZOOM_TRANSCODED_FILES"                (defined in _vars)
    TARGET_FILE_EXTENSION=".m4v"                        # Normally this is ".m4v"                                                      (default defined in _vars)
    SET_PLEX_PERMISSIONS=false                          # Normally true only for Plex content files                                    (default defined in _vars)
    USE_TV_FILTERS=false                                # Normally true only for Plex DVR files                                        (default defined in _vars)
    FLATTEN_TARGET_DIRECTORY=true                       # Normally used for Zoom meeting recordings and MAYBE Ripped DVDs (maybe; TBD) (default defined in _vars)
    PREPEND_PARENT_DIR_TO_BASENAME=true                 # Normally used for Zoom meeting recordings                                    (default defined in _vars)
    APPEND_UUID_TO_TARGET_FILE=false                    # Normally used for Plex files so that multiple media files can be retained.   (default defined in _vars)
    USE_PARENT_DIR_AS_BASENAME=false                    # May be useful for ripped DVDs. TBD. Think about this first                   (default defined in _vars)

# Allow this script to run only on server oz
    f_only_on_server "oz"

# Do the looping work
    while true ; do
        f_iterate_handbrake_source_video_files
	    f_log_and_echo "Sleeping $WAIT_AFTER_SOURCE_SCAN." false  # The TRUE part at the end means this sends pager notices.
																  # Drop this when stable, and consider bumping up the interval.
	    sleep "$WAIT_AFTER_SOURCE_SCAN"
        done

# Include script footer file
	f_debug_variable "script_footer" "${PATHNAME[script_footer]}"
	source "${PATHNAME[script_footer]}"

exit 0

