#!/bin/bash
# This script should be run as root from cron, executed at boot time.
# For now, this should ONLY run on oz, because server-specific values are defined.

# Include script setup file
	source script-setup
	if [ ! $FUNCTIONS_ARE_DEFINED ]; then echo $0: Functions not defined. Aborting; logger $0: Functions not defined. Aborting; exit 1; fi
	if [ ! $VARIABLES_ARE_DEFINED ]; then echo $0: Variables not defined. Aborting; logger $0: Variables not defined. Aborting; exit 1; fi

# Only allow this to run on server nuc01.
	f_only_on_server "nuc01"

# Define file locations
	SOURCE_ROOT_DIR_1="/mnt/cloteal/Plex/Pool06-1TB/TV-Shows"
	TARGET_ROOT_DIR_1="/mnt/ext10tb01/plex"
	SOURCE_ROOT_DIR_2="/var/lib/plexmediaserver/Library/work/TV-DSM"
	TARGET_ROOT_DIR_2="/mnt/ext10tb01/plex"
	TARGET_SERVER="oz.lanehensley.org"
	WAIT_AFTER_SOURCE_SCAN="6h"
	MOVE_MASK="*.ts"
	BLOCK_MASK="*.m4v"

# Do the looping work
# CRITICAL: Note string literals and variables set here. All should be moved to _vars
	THIS_SCRIPT=$(basename "$0")
	while true; do
        sudo -u $ADMIN_USER \
			rsync --remove-source-files --include "$MOVE_MASK" --exclude "$BLOCK_MASK" --exclude ".*" -aloprtv \
			"$SOURCE_ROOT_DIR_1" "$TARGET_SERVER:$TARGET_ROOT_DIR_1" \
			| logger -t "$THIS_SCRIPT"
        sudo -u $ADMIN_USER \
			rsync --remove-source-files --include "$MOVE_MASK" --exclude "$BLOCK_MASK" --exclude ".*" -aloprtv \
			"$SOURCE_ROOT_DIR_2" "$TARGET_SERVER:$TARGET_ROOT_DIR_2" \
			| logger -t "$THIS_SCRIPT"
		f_log_and_echo "Sleeping $WAIT_AFTER_SOURCE_SCAN." false
		sleep "$WAIT_AFTER_SOURCE_SCAN"
        done

# Include script footer file
	f_debug_variable "script_footer" "${PATHNAME[script_footer]}"
	source "${PATHNAME[script_footer]}"

exit 0

