#!/bin/bash
# This script should be run as root from cron, executed at boot time.

# Include script setup file
	source script-setup
	if [ ! $FUNCTIONS_ARE_DEFINED ]; then echo $0: Functions not defined. Aborting; logger $0: Functions not defined. Aborting; exit 1; fi
	if [ ! $VARIABLES_ARE_DEFINED ]; then echo $0: Variables not defined. Aborting; logger $0: Variables not defined. Aborting; exit 1; fi

# Define file locations
	SOURCE_ROOT_DIR="/home/lhensley/Videos/HandBrake-Completed"
	TARGET_ROOT_DIR="nuc01.lanehensley.org:/mnt/cloteal/Plex/uploads"
	TARGET_SERVER="nuc01.lanehensley.org"
	WAIT_AFTER_SOURCE_SCAN="6h"
	MOVE_MASK="*.m4v"

# MOVE (not copy) files to new directory or server/directory
# Useful for MOVING (not copying) completed video files
# Does NOT remove extraneous files from target directories
# rsync options considered
#    -a = archive mode, equivalent to -rlptgoD
#    -g = preserve group ownership
#    -l = recreate symlinks on destination
#    -n = dry run
#    -o = preserve owner
#    -p = preserve permissions
#    -q = quiet
#    -r = recursive (includes subdirectories)
#    -t = preserve modification times
#    -v = verbose
#    -D = preserve device files and special files
#    -E = preserve executability
#    -R = use relative paths (see https://linux.die.net/man/1/rsync for more info)
#    --delete = delete extraneous files from dest dirs

# Do the looping work
	THIS_SCRIPT=$(basename "$0")
	while true; do
        sudo -u $ADMIN_USER \
			rsync --remove-source-files --include $MOVE_MASK -aloprtv \
			"$SOURCE_ROOT_DIR" "$TARGET_SERVER:$TARGET_ROOT_DIR" \
			| logger -t "$THIS_SCRIPT"
		f_log_and_echo "Sleeping $WAIT_AFTER_SOURCE_SCAN." true
		sleep "$WAIT_AFTER_SOURCE_SCAN"
        done

# Include script footer file
	f_debug_variable "script_footer" "${PATHNAME[script_footer]}"
	source "${PATHNAME[script_footer]}"

exit 0

