#!/bin/bash
# Waits for files to enter $WATCH_DIRECTORY and uploads the to $REMOTE_NAME:$REMOTE_DIRECTORY. Loops forever.
# This script should be run as root from cron, executed at boot time.

# Include script setup file
	source script-setup
	if [ ! $FUNCTIONS_ARE_DEFINED ];         then echo $0: Functions not defined. Aborting; logger $0: Functions not defined. Aborting;         exit 1; fi
	if [ ! $VARIABLES_ARE_DEFINED ];         then echo $0: Variables not defined. Aborting; logger $0: Variables not defined. Aborting;         exit 1; fi

# Only allow this to run on server oz.
	f_only_on_server "oz"

# Set variables
	WATCH_DIRECTORY="/home/brother/Scans"
	REMOTE_NAME="lane-onedrive"
	REMOTE_DIRECTORY="Brother"

# Watch and wait
	sudo -u $ADMIN_USER rclone copyto $WATCH_DIRECTORY "$REMOTE_NAME":"$REMOTE_DIRECTORY"
	rm -f "$WATCH_DIRECTORY"/*
	inotifywait -m "$WATCH_DIRECTORY" -e create -e moved_to | 
		while read TEMP_PATH TEMP_ACTION TEMP_FILE; do 
			f_log_and_echo "Moving $TEMP_FILE to $REMOTE_NAME:$REMOTE_DIRECTORY/"
			sudo -u $ADMIN_USER rclone copyto "$TEMP_FILE" "$REMOTE_NAME":"$REMOTE_DIRECTORY/"
			rm -f "$TEMP_FILE"
		done

# Include script footer file
	f_debug_variable "script_footer" "${PATHNAME[script_footer]}"
	source "${PATHNAME[script_footer]}"

exit 0