#!/bin/bash
# show-plex-ts-files

production_mode=true
debug_mode=false
# debug_mode=true
if $debug_mode ; then
  set -x
  fi

logger "$0: Starting."

# Make sure only root can run our script
if [[ $EUID -ne 0 ]]; then
  echo "This script must be run as root."
  logger "$0: FAILED. This script must be run as root."
  exit 1
fi

# Confirm that this host is oz
if [[ $(hostname -s) != "oz" ]]; then
  echo "This script can ony be run on server oz."
  logger "$0: FAILED. This script can only be run on server oz."
  exit 1
fi

WORK_ROOT="/mnt/ssd1tb/plex"
FILES=0

find "$WORK_ROOT" -type f -name "*.ts" -print -exec let FILES++
echo ""
ps -ef | grep "HandBrake\|cskipper\|sleep\|shrink-plex-ts-files"
echo ""
df -Ht ext4

echo Files: $FILES
echo ""

logger "$0: Ended without error."
exit 0
