#!/bin/bash
# lgh3

# Include script setup file
source $(dirname $0)/script-setup

# Include script footer file
f_debug_variable "script.script-footer.pathname" "${LANE_CONFIG[script.script-footer.pathname]}"
source ${LANE_CONFIG[script.script-footer.pathname]}

# Notes:
# Amend config lookup so it checks the variable and not the file