#!/bin/bash

# Include script setup file
	source script-setup
	if [ ! $FUNCTIONS_ARE_DEFINED ]; then echo $0: Functions not defined. Aborting; logger $0: Functions not defined. Aborting; exit 1; fi
	if [ ! $VARIABLES_ARE_DEFINED ]; then echo $0: Variables not defined. Aborting; logger $0: Variables not defined. Aborting; exit 1; fi


# Require host
	f_require_host "nuc01"

# Define variables
	DOWNLOAD_FILE="https://datasets.imdbws.com/title.basics.tsv.gz"
	TAB_SORTED="title.basics.tsv"
	JSON_FILE="imdb.json"
	SQL_FILE="imdb.sql"

# Do stuff here
	mkdir -f ~/imdb
	cd ~/imdb
	sudo apt-get --yes install jq
	wget "$DOWNLOAD_FILE"
	gunzip "$TAB_SORTED"
	echo "{ \"title\": " > "$JSON_FILE"
	sed '1d' "$TAB_SORTED" | jq --raw-input --slurp 'split("\n") | map(split("\t")) | .[0:-1] | map( { "tconst": .[0], \
		"titleType": .[1], "primaryTitle": .[2], "originalTitle": .[3], "isAdult": .[4], "startYear": .[5], "endYear": .[6], \
		"runtimeMinutes": .[7], "genres": .[8] } )' >> "$JSON_FILE"
	sed '1d' "$TAB_SORTED" | jq --raw-input --slurp 'split("\n") | map(split("\t")) | .[0:-1] | map( { "tconst": .[0], \
		"titleType": .[1], "primaryTitle": .[2], "originalTitle": .[3], "isAdult": .[4], "startYear": .[5], "endYear": .[6], \
		"runtimeMinutes": .[7], "genres": .[8] } )' >> "$JSON_FILE"
	echo "}" >> "$JSON_FILE"
	echo "USE imdb;" > "$SQL_FILE"
	echo "TRUNCATE titles;" >> "$SQL_FILE"
	cat "$JSON_FILE" | jq --raw-output '.title[] | "INSERT INTO titles VALUES (\"\(.tconst)\", \"\(.titleType)\", \
		\"\(.primaryTitle)\", \"\(.originalTitle)\", \(.isAdult), \(.title.startYear), \(.endYear), \
		\(.runtimeMinutes), \"\(.genres)\");"' >> "$SQL_FILE"
	sed -i 's/, \"null\"/, NULL/g' "$SQL_FILE"
	sed -i 's/, null/, NULL/g' "$SQL_FILE"
	sed -i 's/, \"\\N\"/, NULL/g' "$SQL_FILE"
	sed -i 's/, \\N/, NULL/g' "$SQL_FILE"
	mysql < "$SQL_FILE"
	cd
	# rm -f "$TAB_SORTED" "$JSON_FILE" "$SQL_FILE"

# Include script footer file
	f_debug_variable "script_footer" "${PATHNAME[script_footer]}"
	source "${PATHNAME[script_footer]}"

exit 0

