#!/bin/bash
# loop-forever

source $(dirname $0)/script-setup

f_debug_variable "script.master-loop.pathname" "$(f_get-config script.master-loop.pathname)"
REPEATING_PROGRAM=$(f_get-config script.master-loop.pathname)

while true; do # Endless loop
	logger "$0: Sleeping for 10 seconds."
	sleep 10 # Sleep for 10 seconds, just in case
	logger "$0: Woke up."
	logger "$0: Starting $REPEATING_PROGRAM"
	$REPEATING_PROGRAM
	logger "$0: Exit Code $? for $REPEATING_PROGRAM"
done # Endless loop

$(f_get-config script.script-footer.pathname)
exit 1