#!/bin/bash

DEBUG_MODE=false; if $DEBUG_MODE ; then echo "DEBUG EXECUTING $0 line ${LINENO}" $(date +"%F %T.%3N %Z") ; fi
# if $DEBUG_MODE ; then echo "DEBUG MARKER $0 line ${LINENO}" $(date +"%F %T.%3N %Z") ; fi

# Include script setup file
	source script-setup
	if [ ! $FUNCTIONS_ARE_DEFINED ]; then echo $0: Functions not defined. Aborting; logger $0: Functions not defined. Aborting; exit 1; fi
	if [ ! $VARIABLES_ARE_DEFINED ]; then echo $0: Variables not defined. Aborting; logger $0: Variables not defined. Aborting; exit 1; fi

# POSSIBLE OPTION: USE IF YOU WANT
# Require root
	f_require_root

TEMP_DIR="$ADMIN_HOME_DIR/seeds-$START_DATEANDTIMESTAMP"
SEED_TAR_FILE="$ADMIN_HOME_DIR/seeds-$START_DATEANDTIMESTAMP.tar.gz"
SEED_GPG_FILE="$ADMIN_HOME_DIR/seeds-$START_DATEANDTIMESTAMP.tar.gz.gpg"

if $DEBUG_MODE ; then echo "DEBUG MARKER $0 line ${LINENO}" $(date +"%F %T.%3N %Z") ; fi
echo "Making sure gpg is installed"
apt-get -y install gpg
echo "Making directory '$TEMP_DIR'"
if ! $(mkdir "$TEMP_DIR"); then f_die "Failed making directory '$TEMP_DIR'" false $?; fi
# echo "Setting ownership for '$TEMP_DIR'"
# if ! $(chown $ADMIN_USER:$ADMIN_USER "$TEMP_DIR"); then
# 	if ! $(rm -r "$TEMP_DIR"); then f_die "Failed removing directory '$TEMP_DIR'" false $?; fi
# 	f_die "Failed setting ownership for '$TEMP_DIR'" false $?;
# 	fi
echo "Copying git configs"
if ! $(cp "$ADMIN_HOME_DIR/.git"* "$TEMP_DIR/"); then
	if ! $(rm -r "$TEMP_DIR"); then f_die "Failed removing directory '$TEMP_DIR'" false $?; fi
	f_die "Failed copying git configs" false $?;
	fi
echo "Copying ~/.ssh directory"
if ! $(cp -r "$ADMIN_HOME_DIR/.ssh" "$TEMP_DIR/"); then
	if ! $(rm -r "$TEMP_DIR"); then f_die "Failed removing directory '$TEMP_DIR'" false $?; fi
	f_die "Failed copying ~/.ssh directory" false $?;
	fi
# echo "Copying /var/local/git/ubuntu-tools/install/clean-setup and /var/local/git/ubuntu-tools/install/variables"
# if ! $(cp "/var/local/git/ubuntu-tools/install/clean-setup" "/var/local/git/ubuntu-tools/install/variables" "$TEMP_DIR/"); then
# 	if ! $(rm -r "$TEMP_DIR"); then f_die "Failed removing directory '$TEMP_DIR'" false $?; fi
# 	f_die "Failed copying /var/local/git/ubuntu-tools/install files" false $?;
# 	fi
echo "Setting ownership for contents of '$TEMP_DIR'"
if ! $(chown -R $ADMIN_USER:$ADMIN_USER "$TEMP_DIR"); then
	if ! $(rm -r "$TEMP_DIR"); then f_die "Failed removing directory '$TEMP_DIR'" false $?; fi
	f_die "Failed setting ownership for contents of '$TEMP_DIR'" false $?;
	fi
echo "Compressing '$TEMP_DIR' to '$SEED_TAR_FILE'"
echo tar -czf "$SEED_TAR_FILE" -C "$TEMP_DIR" .
if ! $(tar -czf "$SEED_TAR_FILE" -C "$TEMP_DIR" .); then
	echo "Deleting '$TEMP_DIR'"
	rm -r "$TEMP_DIR"
	f_die "Failed creating '$SEED_TAR_FILE'" false $?;
	fi
echo "Encrypting '$SEED_TAR_FILE' to '$SEED_GPG_FILE'"
echo Password is in 1Password at '"'Seed File for Ubuntu Installation'"'.
f_pause
if ! $(gpg -c "$SEED_TAR_FILE"); then
	echo "Deleting '$TEMP_DIR'"
	rm -r "$TEMP_DIR"
	echo "Deleting '$SEED_TAR_FILE'"
	rm "$SEED_TAR_FILE"
	f_die "Failed creating '$SEED_GPG_FILE'" false $?;
	fi
echo "Copying '$SEED_GPG_FILE' to 'seeds.tar.gz.gpg'."
if ! $(cp "$SEED_GPG_FILE" seeds.tar.gz.gpg); then
	f_die "Failed copying '$SEED_GPG_FILE' to 'seeds.tar.gz.gpg'." false $?;
	fi

echo "Deleting '$TEMP_DIR'"
rm -r "$TEMP_DIR"
echo "Deleting '$SEED_TAR_FILE'"
rm "$SEED_TAR_FILE"
if $DEBUG_MODE ; then echo "DEBUG MARKER $0 line ${LINENO}" $(date +"%F %T.%3N %Z") ; fi
echo "Updating ownerships in $(pwd)"
if $DEBUG_MODE ; then echo "DEBUG MARKER $0 line ${LINENO}" $(date +"%F %T.%3N %Z") ; fi
chown -R $SUDO_USER:$SUDO_USER $(pwd)
if $DEBUG_MODE ; then echo "DEBUG MARKER $0 line ${LINENO}" $(date +"%F %T.%3N %Z") ; fi
rm -f "$SEED_TAR_FILE"
if $DEBUG_MODE ; then echo "DEBUG MARKER $0 line ${LINENO}" $(date +"%F %T.%3N %Z") ; fi
# mv 'seeds.tar.gz.gpg' "$ADMIN_HOME_DIR/"
echo "Success creating $ADMIN_HOME_DIR/seeds.tar.gz.gpg."
if $DEBUG_MODE ; then echo "DEBUG MARKER $0 line ${LINENO}" $(date +"%F %T.%3N %Z") ; fi
echo "It has NOT been moved to the install directory of the master branch of ubuntu-tools."
if $DEBUG_MODE ; then echo "DEBUG MARKER $0 line ${LINENO}" $(date +"%F %T.%3N %Z") ; fi
echo "It has NOT been committed with git, or pushed to GitHub."
if $DEBUG_MODE ; then echo "DEBUG MARKER $0 line ${LINENO}" $(date +"%F %T.%3N %Z") ; fi
echo "That's essential, and it's up to you."
echo "Suggestion: Issue this command:"
echo "    cp seeds.tar.gz.gpg git/ubuntu-tools/install/"
echo "  then sync up to Github (presumably from Visual Studio Code)."
# echo "Attempting to email it to $ADMIN_EMAIL."
# echo "If the email doesn't reach you, download seeds.tar.gz.gpg with sftp."
# echo "  and add it to repository ubuntu-tools/install/"
# echo "Here is your seed file:" | mail -A ./seeds.tar.gz.gpg -s "Seed file from $HOST_FQDN" lane@lanehensley.org
# echo "Mail attempted."

if $DEBUG_MODE ; then echo "DEBUG ENDING $0 line ${LINENO}" $(date +"%F %T.%3N %Z") ; fi

# Include script footer file
	f_debug_variable "script_footer" "${PATHNAME[script_footer]}"
	source "${PATHNAME[script_footer]}"

exit 0
