#!/bin/bash
# make-ssh-keys

# Include script setup file
	source script-setup
	if [ ! $FUNCTIONS_ARE_DEFINED ]; then echo $0: Functions not defined. Aborting; logger $0: Functions not defined. Aborting; exit 1; fi
	if [ ! $VARIABLES_ARE_DEFINED ]; then echo $0: Variables not defined. Aborting; logger $0: Variables not defined. Aborting; exit 1; fi

# Run requirements
	f_require_ubuntu
	f_require_minimum_version_number 20

# Do updates
	f_run_apt_updates

# Install putty (including puttygen)
	f_install putty

# Install util-linux (including uuidgen)
	f_install util-linux

# Create ssh keys
	# ssh-keygen -t ed25519 -C "$SSH_KEY_NAME" -P "" -f "$HOME_ME/.ssh/id_ed25519"
#	SSH_IMPRESS="$ADMIN_EMAIL-$START_DATEANDTIMESTAMP-id_ed25519"
	SSH_IMPRESS="$(uuidgen)-$START_DATEANDTIMESTAMP-id_ed25519"
	SSH_LOCATION="$ADMIN_HOME_DIR/.ssh/$SSH_IMPRESS"
	rm -f "$SSH_LOCATION"
	rm -f "$SSH_LOCATION.pub"
	ssh-keygen -t ed25519 -f "$SSH_LOCATION" -C "$SSH_IMPRESS" -P "" -q
	puttygen "$SSH_LOCATION" -o "$SSH_LOCATION-Putty-Private.ppk" -O private -q
	puttygen "$SSH_LOCATION" -o "$SSH_LOCATION-Putty-Public" -O public -q
	cp -f "$SSH_LOCATION" "$ADMIN_HOME_DIR/.ssh/id_ed25519"
	cp -f "$SSH_LOCATION.pub" "$ADMIN_HOME_DIR/.ssh/id_ed25519.pub"
	cat "$SSH_LOCATION.pub" >> "$ADMIN_HOME_DIR/.ssh/authorized_keys"
	#echo "Public key attached." | mail -s "$SSH_LOCATION.pub" -A "$SSH_LOCATION.pub" $ADMIN_EMAIL

# Apply configs to set permissions within ~/.ssh
	f_apply_configs
	f_apply_permissions

# Display the public key
	echo ""
	echo ""
	echo "IMPORTANT: Add this public key to git/go/configs/ssh/home-.ssh-authorized_keys"
	echo ""
	echo "# $SSH_IMPRESS"
	cat "$SSH_LOCATION.pub"
	echo "#"
	echo ""
	echo ""

# Include script footer file
	f_debug_variable "script_footer" "${PATHNAME[script_footer]}"
	source "${PATHNAME[script_footer]}"

exit 0
