#!/bin/bash
# make-ssh-keys

# Include script setup file
	source script-setup
	if [ ! $FUNCTIONS_ARE_DEFINED ]; then echo $0: Functions not defined. Aborting; logger $0: Functions not defined. Aborting; exit 1; fi
	if [ ! $VARIABLES_ARE_DEFINED ]; then echo $0: Variables not defined. Aborting; logger $0: Variables not defined. Aborting; exit 1; fi

# Run requirements
	f_require_ubuntu
	f_require_minimum_version_number 20

# Do updates
	f_run_apt_updates

# Make $USER_ME and $USER_UBUNTU users and give them sudo access and ssh access
	ssh-keygen -C "$SSH_KEY_NAME" -P "" -f "$HOME_ME/.ssh/id_rsa"

# Invoke /usr/local/sbin/apply-configs
	f_apply-configs

# Display the public key
	echo "IMPORTANT: Add this public key to git/go/configs/ssh/home-.ssh-authorized_keys"
	cat "$HOME_ME/.ssh/id_rsa.pub"

# Include script footer file
	f_debug_variable "script_footer" "${PATHNAME[script_footer]}"
	source "${PATHNAME[script_footer]}"

exit 0
