#!/bin/bash
# make-passwords

# Include script setup file
	source script-setup
	if [ ! $FUNCTIONS_ARE_DEFINED ]; then echo $0: Functions not defined. Aborting; logger $0: Functions not defined. Aborting; fi
	if [ ! $VARIABLES_ARE_DEFINED ]; then echo $0: Variables not defined. Aborting; logger $0: Variables not defined. Aborting; fi

echo ""
echo "30-character passwords (for MySQL)"
apg -s -a 1 -m $MAX_MYSQL_PASSWORD_LENGTH -n 50 -E $EXCLUDED_PASSWORD_CHARACTERS
echo ""
echo "60-character passwords"
apg -s -a 1 -m $LENGTH_OF_PASSWORDS -n 50 -E $EXCLUDED_PASSWORD_CHARACTERS
echo ""

# Include script footer file
	f_debug_variable "script_footer" "${PATHNAME[script_footer]}"
	source "${PATHNAME[script_footer]}"

exit 0
