#!/bin/bash

# Include script setup file
	source script-setup
	if [ ! $FUNCTIONS_ARE_DEFINED ]; then echo $0: Functions not defined. Aborting; logger $0: Functions not defined. Aborting; exit 1; fi
	if [ ! $VARIABLES_ARE_DEFINED ]; then echo $0: Variables not defined. Aborting; logger $0: Variables not defined. Aborting; exit 1; fi

# POSSIBLE OPTION: USE IF YOU WANT
# Require root
	f_require_root

TEMP_DIR="$ADMIN_HOME_DIR/seeds-$START_DATEANDTIMESTAMP"

echo "Making directory '$TEMP_DIR'"
if ! $(mkdir "$TEMP_DIR"); then f_die "Failed making directory '$TEMP_DIR'" false $?; fi
echo "Setting ownership for '$TEMP_DIR'"
if ! $(chown $ADMIN_USER:$ADMIN_USER "$TEMP_DIR"); then
	if ! $(rm -r "$TEMP_DIR"); then f_die "Failed removing directory '$TEMP_DIR'" false $?; fi
	f_die "Failed setting ownership for '$TEMP_DIR'" false $?;
	fi

if ! $(cp "$ADMIN_HOME_DIR/.git"* "$TEMP_DIR/"); then
	if ! $(rm -r "$TEMP_DIR"); then f_die "Failed removing directory '$TEMP_DIR'" false $?; fi
	f_die "Failed copying git configs" false $?;
	fi
if ! $(cp -r "$ADMIN_HOME_DIR/.ssh" "$TEMP_DIR/"); then
	if ! $(rm -r "$TEMP_DIR"); then f_die "Failed removing directory '$TEMP_DIR'" false $?; fi
	f_die "Failed copying ~/.ssh directory" false $?;
	fi

# Include script footer file
	f_debug_variable "script_footer" "${PATHNAME[script_footer]}"
	source "${PATHNAME[script_footer]}"

exit 0

