#!/bin/bash
# master-loop

source $(dirname $0)/script-setup

f_debug_variable "script.shrink-plex-ts-files.pathname" "$(f_get-config script.shrink-plex-ts-files.pathname)"
$(f_get-config script.shrink-plex-ts-files.pathname)

f_debug_variable "script.script-footer.pathname" "$(f_get-config script.script-footer.pathname)"
source $(f_get-config script.script-footer.pathname)

exit 0
