#!/bin/bash
# master-loop

# Include script setup file
	source script-setup
	if [ ! $FUNCTIONS_ARE_DEFINED ]; then echo $0: Functions not defined. Aborting; logger $0: Functions not defined. Aborting; fi
	if [ ! $VARIABLES_ARE_DEFINED ]; then echo $0: Variables not defined. Aborting; logger $0: Variables not defined. Aborting; fi

f_debug_variable "shrink_plex_ts_files" "$PATHNAME[shrink_plex_ts_files]"
f_require_file "$PATHNAME[shrink_plex_ts_files]" ]

"$PATHNAME[shrink_plex_ts_files]"
sleep 60

# Include script footer file
	f_debug_variable "script_footer" "${PATHNAME[script_footer]}"
	source "${PATHNAME[script_footer]}"

exit 0
