#!/bin/bash

# Include script setup file
	source script-setup
	if [ ! $FUNCTIONS_ARE_DEFINED ]; then echo $0: Functions not defined. Aborting; logger $0: Functions not defined. Aborting; exit 1; fi
	if [ ! $VARIABLES_ARE_DEFINED ]; then echo $0: Variables not defined. Aborting; logger $0: Variables not defined. Aborting; exit 1; fi

# "Run as a service" check
#	if [ "$PPID" != "1" ]; then
#		f_die "This script only runs as a systemd service. Try sudo systemctl start $(basename $0)" false
#		fi
#	SERVICE_FLAG=true;

# Only allow this to run on server nuc01.
	f_only_on_server "nuc01"

# Do the looping work
	THIS_SCRIPT=$(basename "$0")

	EXCLUDE_MASK2=".grab/"

	SOURCE_ROOT_DIR="/mnt/bob/plex/dvr/tv"
	TARGET_ROOT_DIR="/mnt/bob/plex/dvr/in/tv"
	rsync --remove-source-files \
		--exclude "$EXCLUDE_MASK2" -aloprtv \
	"$SOURCE_ROOT_DIR"/* "$TARGET_ROOT_DIR"

	SOURCE_ROOT_DIR="/mnt/bob/plex/dvr/movies"
	TARGET_ROOT_DIR="/mnt/bob/plex/dvr/in/movies"
	rsync --remove-source-files \
		--exclude "$EXCLUDE_MASK2" -aloprtv \
	"$SOURCE_ROOT_DIR"/* "$TARGET_ROOT_DIR"

    SOURCE_ROOT_DIR="/var/lib/plexmediaserver/Library/work"
	TARGET_ROOT_DIR="/mnt/bob/plex/dvr/in"
	rsync --remove-source-files \
		--exclude "$EXCLUDE_MASK2" -aloprtv \
	"$SOURCE_ROOT_DIR"/* "$TARGET_ROOT_DIR"

	SOURCE_ROOT_DIR="/mnt/12TBA/plexcontent/dvr"
	TARGET_ROOT_DIR="/mnt/bob/plex/dvr/in"
	rsync --remove-source-files \
		--exclude "$EXCLUDE_MASK2" -aloprtv \
	"$SOURCE_ROOT_DIR"/* "$TARGET_ROOT_DIR"

# Include script footer file
	f_debug_variable "script_footer" "${PATHNAME[script_footer]}"
	source "${PATHNAME[script_footer]}"

exit 0
