#!/bin/bash
# move-scans-to-onedrive

debug_mode=false
#debug_mode=true
if $debug_mode ; then
  set -x
  fi

# Include header file
PROGRAM_DIRECTORY=$(dirname $0)
source $PROGRAM_DIRECTORY/script-setup

SCAN_MAIL_DIR="/var/scans"
SCAN_ONEDRIVE="onedrive-personal:Brother"
RCLONE="rclone"

if [ $( ls -A $SCAN_MAIL_DIR ) ]; then # If files exist in $SCAN_MAIL_DIR 
	rm -f $SCAN_MAIL_DIR/textfile*
	ps -C "$RCLONE" >/dev/null # Check whether rclone is running
	if [ $? -eq 0 ]; then # If no error, that means it's running.
		true # Dummy value indicating everything is OK because rclone already is running
	else
		rclone move "$SCAN_MAIL_DIR" $SCAN_ONEDRIVE # Move files to OneDrive
	fi
	EXIT_STATUS=$? # Check the status of rclone or true, as the case may be
	if [ $EXIT_STATUS -ne 0 ]; then
		lanelog "Failed to upload scan(s) to OneDrive."
	else
		lanelog "Uploaded scan(s) to OneDrive"
	fi
fi
exit $EXIT_STATUS