#!/bin/bash

# Include script setup file
	source script-setup
	if [ ! $FUNCTIONS_ARE_DEFINED ]; then echo $0: Functions not defined. Aborting; logger $0: Functions not defined. Aborting; exit 1; fi
	if [ ! $VARIABLES_ARE_DEFINED ]; then echo $0: Variables not defined. Aborting; logger $0: Variables not defined. Aborting; exit 1; fi

# "Run as a service" check
	if [ "$PPID" != "1" ]; then
		f_die "This script only runs as a systemd service. Try sudo systemctl start $(basename $0)" false
		fi
	SERVICE_FLAG=true;

# Only allow this to run on server oz.
	f_only_on_server "pd1" #2023-08-16

# Set variables
	WATCH_DIRECTORY="/var/samba/brother" #2023-08-16
	REMOTE_NAME="onedrive"
	REMOTE_DIRECTORY="Brother"

# Watch and wait
	f_watch_wait_upload

# Include script footer file
	f_debug_variable "script_footer" "${PATHNAME[script_footer]}"
	source "${PATHNAME[script_footer]}"

exit 0
