#!/bin/bash
# process_ts
# Usage: move-one-file <input_file> <root_work_path> <root_storage_path>
# No final / on either path. For system root, use ""

production_mode=true
debug_mode=false
# debug_mode=true
if $debug_mode ; then
  set -x
  fi

IN_PATH=$1
ROOT_WORK_PATH=$2
ROOT_STORAGE_PATH=$3

# OUT_EXT="m4v"

ROOT_WORK_PATH_LENGTH=${#ROOT_WORK_PATH}

IN_PATH_LENGTH=${#IN_PATH}
IN_EXT="${IN_PATH##*.}"
IN_EXT_LENGTH="${#IN_EXT}"

RELATIVE_PATH_LENGTH=$[IN_PATH_LENGTH-ROOT_WORK_PATH_LENGTH-1]
RELATIVE_PATH=${IN_PATH: -$RELATIVE_PATH_LENGTH} # Remove ROOT_WORK_PATH
# RELATIVE_PATH_LENGTH=$[RELATIVE_PATH_LENGTH-IN_EXT_LENGTH-1] # Recalculate relative path length by removing extension length
# RELATIVE_PATH=${RELATIVE_PATH:0:RELATIVE_PATH_LENGTH} # Then remove IN_EXT

STORE_PATH="$ROOT_STORAGE_PATH/$RELATIVE_PATH"
# OUT_PATH="$ROOT_WORK_PATH/$RELATIVE_PATH.$OUT_EXT"
# STORE_PATH="$ROOT_STORAGE_PATH/$RELATIVE_PATH.$OUT_EXT"

HANDBRAKE="HandBrakeCLI"
PRESET="/home/lhensley/.HandBrake/Lane 1080p (BluRay).json"

# So here are useful variables defined ...
# $IN_PATH
# $STORE_PATH
# $ROOT_WORK_PATH
# $ROOT_STORAGE_PATH
# $RELATIVE_PATH

# Make sure only root can run our script
if [[ $EUID -ne 0 ]]; then
  echo "This script must be run as root."
  exit 1
fi

# Make the directory for storage
if [ ! -d $(dirname $STORE_PATH) ]; then
  mkdir -p "$(dirname $STORE_PATH)" >> /dev/null 2>&1 # Create the directory for the stored version
  exit_status=$?
  if [ $exit_status -ne 0 ]; then # If the transcoding failed ...
      logger "$0 FAILED to make $(dirname $STORE_PATH)"
      echo "Failed to make $(dirname $STORE_PATH)" | mail lanecell
      fi
  fi

# Move the transcoded file to storage
mv "$IN_PATH" "$STORE_PATH" >> /dev/null 2>&1
exit_status=$?
if [ $exit_status -ne 0 ]; then # If the transcoding failed ...
    logger "$0 FAILED to move $IN_PATH to $(dirname $STORE_PATH)"
    echo "Failed to move to storage $RELATIVE_PATH" | mail lanecell
    echo "Source $IN_PATH" | mail lanecell
    echo "Target dir $(dirname $STORE_PATH)" | mail lanecell
    echo "Source $STORE_PATH" | mail lanecell
    exit $exit_status
  else
    logger "$0 moved $IN_PATH to $(dirname $STORE_PATH)"
  fi

exit 0
