#!/bin/bash

# Include script setup file
	source script-setup
	if [ ! $FUNCTIONS_ARE_DEFINED ]; then echo $0: Functions not defined. Aborting; logger $0: Functions not defined. Aborting; exit 1; fi
	if [ ! $VARIABLES_ARE_DEFINED ]; then echo $0: Variables not defined. Aborting; logger $0: Variables not defined. Aborting; exit 1; fi

# POSSIBLE OPTION: USE IF YOU WANT
# Require root
	f_require_root

# POSSIBLE OPTION: USE IF YOU WANT
# Require a specific host
	f_require_host dsm1

sudo _apply-plex-permissions # Using the find command
rsync -avE --delete /mnt/4TBA/plex /mnt/5TBC/archives/4TBA
rsync -avE --delete /mnt/4TBA/archives /mnt/5TBC/archives/4TBA
rsync -avE --delete /mnt/4TBA/plex /mnt/20TBA/archives/4TBA
rsync -avE --delete /mnt/4TBA/archives /mnt/20TBA/archives/4TBA
rsync -avE --delete /mnt/12TBA/plex /mnt/12TBB/archives/12TBA
rsync -avE --delete /mnt/12TBA/archives /mnt/12TBB/archives/12TBA
rsync -avE --delete /mnt/12TBA/plex /mnt/20TBA/archives/12TBA
rsync -avE --delete /mnt/12TBA/archives /mnt/20TBA/archives/12TBA

echo "[$(hostname)] $(basename $0): completed" | mail "$ADMIN_CELL_EMAIL"

# Include script footer file
	f_debug_variable "script_footer" "${PATHNAME[script_footer]}"
	source "${PATHNAME[script_footer]}"

exit 0

