#!/bin/bash
# plex-status

production_mode=true
debug_mode=false
# debug_mode=true
if $debug_mode ; then
  set -x
  fi

# Make sure only root can run our script
if [[ $EUID -ne 0 ]]; then
  echo "This script must be run as root."
  exit 1
fi

# Confirm that this host is oz
if [[ $(hostname -s) != "oz" ]]; then
  echo "This script can ony be run on server oz."
  exit 1
fi

ROOT_WORK="/mnt/ssd1tb/plex"
ROOT_STORE="/mnt/rerun/plex"

FILE_COUNT=0

find "$ROOT_WORK" -type f -name "*.ts" -print -exec ((FILE_COUNT=FILE_COUNT+1)) \;
# >> /dev/null 2>&1

echo "Count $FILE_COUNT"

exit 0
