#!/bin/bash
# Syncs /mnt/12TBA and /mnt/12TBC to match /mnt/12TBB

# Include script setup file
	source script-setup
	if [ ! $FUNCTIONS_ARE_DEFINED ]; then echo $0: Functions not defined. Aborting; logger $0: Functions not defined. Aborting; exit 1; fi
	if [ ! $VARIABLES_ARE_DEFINED ]; then echo $0: Variables not defined. Aborting; logger $0: Variables not defined. Aborting; exit 1; fi


# POSSIBLE OPTION: USE IF YOU WANT
# Require root
	f_require_root

# Do stuff here
TARGET_FILE_SYSTEM="/mnt/12TBA"
	SOURCE_FILE_SYSTEM="/mnt/12TBB"
	mount "$TEMP_TARGET"
	mount "$TEMP_SOURCE"
	if ! [ $(f_is_mounted "$TARGET_FILE_SYSTEM") ]; then
		f_die "$TARGET_FILE_SYSTEM is not mounted." true
		fi
	rsync-wrapper "$TEMP_SOURCE" "" "$TEMP_TARGET" "" > /dev/null 2> /dev/null
	umount "$TEMP_TARGET"
TARGET_FILE_SYSTEM="/mnt/12TBC"
	SOURCE_FILE_SYSTEM="/mnt/12TBB"
	mount "$TEMP_TARGET"
	mount "$TEMP_SOURCE"
	if ! [ $(f_is_mounted "$TARGET_FILE_SYSTEM") ]; then
		f_die "$TARGET_FILE_SYSTEM is not mounted." true
		fi
	rsync-wrapper "$TEMP_SOURCE" "" "$TEMP_TARGET" "" > /dev/null 2> /dev/null
	umount "$TEMP_TARGET"

# Include script footer file
	f_debug_variable "script_footer" "${PATHNAME[script_footer]}"
	source "${PATHNAME[script_footer]}"

exit 0

