#!/bin/bash
# Syncs /mnt/12TBA and /mnt/12TBC to match /mnt/12TBB

# Include script setup file
	source script-setup
	if [ ! $FUNCTIONS_ARE_DEFINED ]; then echo $0: Functions not defined. Aborting; logger $0: Functions not defined. Aborting; exit 1; fi
	if [ ! $VARIABLES_ARE_DEFINED ]; then echo $0: Variables not defined. Aborting; logger $0: Variables not defined. Aborting; exit 1; fi

# POSSIBLE OPTION: USE IF YOU WANT
# Require root
	f_require_root

# POSSIBLE OPTION: USE IF YOU WANT
# Require a specific host
	f_require_host dsm1

chown -R lhensley:lhensley /mnt/4TBA/plex /mnt/12TBA/plex
find /mnt/4TBA/plex -type d -print -exec chmod 755 {} \; >> /dev/null 2>&1
find /mnt/4TBA/plex -type f -print -exec chmod 644 {} \; >> /dev/null 2>&1
find /mnt/12TBA/plex -type d -print -exec chmod 755 {} \; >> /dev/null 2>&1
find /mnt/12TBA/plex -type f -print -exec chmod 644 {} \; >> /dev/null 2>&1
rsync -avE --delete /mnt/4TBA/plex /mnt/5TBC/archives/4TBA
rsync -avE --delete /mnt/4TBA/archives /mnt/5TBC/archives/4TBA
rsync -avE --delete /mnt/4TBA/plex /mnt/20TBA/archives/4TBA
rsync -avE --delete /mnt/4TBA/archives /mnt/20TBA/archives/4TBA
rsync -avE --delete /mnt/12TBA/plex /mnt/12TBB/archives/12TBA
rsync -avE --delete /mnt/12TBA/archives /mnt/12TBB/archives/12TBA
rsync -avE --delete /mnt/12TBA/plex /mnt/20TBA/archives/12TBA
rsync -avE --delete /mnt/12TBA/archives /mnt/20TBA/archives/12TBA

# Include script footer file
	f_debug_variable "script_footer" "${PATHNAME[script_footer]}"
	source "${PATHNAME[script_footer]}"

exit 0

