#!/bin/bash
# Based on https://www.reddit.com/r/PleX/comments/6gcfok/comskip_ffmpeg_script/

# TO DO
# Install with apt-git: comskip ffmpeg ccextractor
# Install with git script: comchap

# Include script setup file
	source script-setup
	if [ ! $FUNCTIONS_ARE_DEFINED ]; then echo $0: Functions not defined. Aborting; logger $0: Functions not defined. Aborting; exit 1; fi
	if [ ! $VARIABLES_ARE_DEFINED ]; then echo $0: Variables not defined. Aborting; logger $0: Variables not defined. Aborting; exit 1; fi

# POSSIBLE OPTION: USE IF YOU WANT
# Require root
#	f_require_root

# PATH is unnecessary since it's already there, but it doesn't hurt anything.
ComChapPath="/usr/local/bin"
ComSkipINI="/etc/comskip/comskip-DEFAULT.ini"
PATH="$PATH:$ComChapPath"
PVFlockFile="/tmp/process-video-file.lock"
ComchaplockFile="/tmp/comchap.lock"
origFile="$1"
tmpFile="/tmp/$1.tmp"
tmpEncode="/tmp/$1.mkv"
tmpSrt="/tmp/$1.srt"
# dvrPostLog="/media/8eeb64f5-b001-47d0-a261-bbee8a83d11d/plexdvr/dvrProcessing.log"

# Check for input file
if (( $# < 1 )); then
    echo "No input file specified."
	exit -1
	fi

echo Gets to A---.

# Make sure comskip is installed
if $(f_is_installed "comskip"); then true ; else apt-get -y install comskip; fi

echo Gets to A--.

# Make sure ccextractor is installed
if $(f_is_installed "ccextractor"); then true ; else apt-get -y install ccextractor; fi

echo Gets to A-.

# Make sure ffmpeg is installed
if $(f_is_installed "ffmpeg"); then true ; else apt-get -y install ffmpeg; fi

echo Gets to A-2.

# Wait if post processing is already running
while [ -f $PVFlockFile ] ; do
    echo "'$PVFlockFile' exists, sleeping processing of '$origFile'" # | tee $dvrPostLog
    sleep 10
	done

echo Gets to A.

# Create lock file to prevent other post-processing from running simultaneously
echo "Creating lock file '$PVFlockFile' for processing '$origFile'" # | tee -a $dvrPostLog
touch "$PVFlockFile"
 
echo Gets to B.

# Mark and cut commercials
echo "cut from '$origFile'" # | tee -a $dvrPostLog
echo comcut --lockfile='ComchaplockFile' "$origFile"
comcut --lockfile='ComchaplockFile' --comskip-ini="$ComSkipINI" "$origFile"

echo Gets to C.

# Pull CC from file to SRT file
echo "Pulling Closed captions from '$origFile' to SRT file" # | tee -a $dvrPostLog
ccextractor "$origFile" -o "$tmpSrt"

echo Gets to D. WATCH FOR ERROR ABOUT NO CC FILE.

# Encode file to H.264 with mkv container using ffmpeg and mux in CC srt
echo "Re-encoding '$origFile' to MKV file while adding cc data" # | tee -a $dvrPostLog
/usr/bin/ffmpeg -i "$origFile" -i "$tmpSrt" -map 0 -map 1 -acodec copy -scodec copy -c:v libx264 -preset medium -profile:v high -level 4.0 -filter:v bwdif=mode=send_field:parity=auto:deint=all "$tmpEncode"

echo Gets to E.

# Remove SRT file
echo "Remove SRT file" # | tee -a $dvrPostLog
rm -f "$tmpSrt"

echo Gets to F.

# Rename first transcoded file to temp file in case no subtitles
echo "Rename transcoded file to tmp file" # | tee -a $dvrPostLog
mv -f "$tmpEncode" "$tmpFile"

echo Gets to G.

# Overwrite original ts file with the transcoded file
echo "Removing '$origFile'" # | tee -a $dvrPostLog
mv -f "$tmpFile" "$origFile"

echo Gets to Y.

# Remove lock file
echo "Done processing '$origFile' removing lock" # | tee -a $dvrPostLog
rm $PVFlockFile

echo Gets to Z.

# Include script footer file
	f_debug_variable "script_footer" "${PATHNAME[script_footer]}"
	source "${PATHNAME[script_footer]}"

exit 0

############################################################################################

exit -1

# Original script below:
# 
# 
# #!/bin/csh
# 
# set path = ($path /usr/local/bin)
# set lockFile = '/tmp/dvrProcessing.lock'
# set origFile = "$1"
# set tmpFile = "$1.tmp"
# set tmpEncode = "$1.mkv"
# set tmpSrt = "$1.srt"
# set dvrPostLog = '/media/8eeb64f5-b001-47d0-a261-bbee8a83d11d/plexdvr/dvrProcessing.log'
# 
# #Wait if post processing is already running
# while ( -f $lockFile )
#     echo "'$lockFile' exists, sleeping processing of '$origFile'" | tee $dvrPostLog
#     sleep 10
# end
# 
# #Create lock file to prevent other post-processing from running simultaneously
# echo "Creating lock file for processing '$origFile'" | tee -a $dvrPostLog
# touch $lockFile
# 
# #Mark and cut commercials
# echo "cut from '$origFile'" | tee -a $dvrPostLog
# /media/8eeb64f5-b001-47d0-a261-bbee8a83d11d/plexdvr/comchap/comcut --lockfile=/tmp/ComchaplockFile --comskip-ini=/media/8eeb64f5-b001-47d0-a261-bbee8a83d11d/plexdvr/comskip.ini "$origFile"
# 
# #Pull CC from file to SRT file
# echo "Pulling Closed captions from '$origFile' to SRT file" | tee -a $dvrPostLog
# ccextractor "$origFile" -o "$tmpSrt"
# 
# #Encode file to H.264 with mkv container using ffmpeg and mux in CC srt
# echo "Re-encoding '$origFile' to MKV file while adding cc data" | tee -a $dvrPostLog
# /usr/bin/ffmpeg -i "$origFile" -i "$tmpSrt" -map 0 -map 1 -acodec copy -scodec copy -c:v libx264 -preset medium -profile:v high -level 4.0 -deinterlace "$tmpEncode"
# 
# #Remove SRT file
# echo "Remove SRT file" | tee -a $dvrPostLog
# rm -f "$tmpSrt"
# 
# #Rename first transcoded file to temp file in case no subtitles
# echo "Rename transcoded file to tmp file" | tee -a $dvrPostLog
# mv -f "$tmpEncode" "$tmpFile"
# 
# #Overwrite original ts file with the transcoded file
# echo "Removing '$origFile'" | tee -a $dvrPostLog
# mv -f "$tmpFile" "$origFile"
# 
# #Remove lock file
# echo "Done processing '$origFile' removing lock" | tee -a $dvrPostLog
# rm $lockFile
# 
# exit 0
# 
# 