#!/bin/bash
# process_ts
# Usage: process_ts <input_file> <root_work_path> <root_storage_path>
# No final / on either path. For system root, use ""

INSTRING=$1
ROOT_WORK_PATH=$2
ROOT_STORAGE_PATH=$3

echo "In: $INSTRING"
echo "2 length: ${#2}"
echo "Work: $ROOT_WORK_PATH"
echo "Work length: ${#ROOT_WORK_PATH}"
echo "Storage: $ROOT_STORAGE_PATH"
echo "Storage length: ${#ROOT_STORAGE_PATH}"
echo "Without Work: ${INSTRING: -1-(${#ROOT_WORK_PATH})}"
echo "Without Work: ${INSTRING: -3}"
echo "Out: $3/${INSTRING: -1-(${#ROOT_WORK_PATH})}"
echo ""
