#!/bin/bash
# process-incoming-scans
#Add this to crontab, running it as user brother

# Include script setup file
# LEAVE THIS OUT until it can handle being run by a non-root user
# source $(dirname $0)/script-setup

while inotifywait -e modify,create ~/Scans > ~/.scan_message 2>&1
	do
		sleep 1
		rclone move ~/Scans lane_onedrive:Brother >> ~/.scan_message 2>&1
		echo ~/.scan_message | mail lanecell
	done

# Include script footer file
# LEAVE THIS OUT until it can handle being run by a non-root user
# f_debug_variable "script.script-footer.pathname" "${LANE_CONFIG[script.script-footer.pathname]}"
# LEAVE THIS OUT until it can handle being run by a non-root user
# source ${LANE_CONFIG[script.script-footer.pathname]}
