#!/bin/bash
# Based on https://www.reddit.com/r/PleX/comments/6gcfok/comskip_ffmpeg_script/
# Dependencies
# 	From apt-get: comskip ffmpeg ccextractor
#	From Github: https://github.com/BrettSheleski/comchap

# Include script setup file
	source script-setup
	if [ ! $FUNCTIONS_ARE_DEFINED ]; then echo $0: Functions not defined. Aborting; logger $0: Functions not defined. Aborting; exit 1; fi
	if [ ! $VARIABLES_ARE_DEFINED ]; then echo $0: Variables not defined. Aborting; logger $0: Variables not defined. Aborting; exit 1; fi

# If you want to iterate through a directory tree, do this:
#   find DIRECTORY -type f > LISTFILE
#   while read f ; do process-video-file $f ; done < LISTFILE
# Example: 
#	find '/mnt/12TBB/plex/TV Shows/Regular/DVR' -type f > ~/video-list)
#   while read f ; do process-video-file $f ; done < ~/video-list
# This could take a very long time. If the process is interrupted:
#   1. Check ~/last-video-processed to see the last video processed without error.
#   2. Edit the LISTFILE and remove everything from start to last video processed without error.
#   3. Re-start the process:
#        while read f ; do process-video-file $f ; done < LISTFILE
# 	   Example: 
#        while read f ; do process-video-file $f ; done < ~/video-list

# POSSIBLE OPTION: USE IF YOU WANT
# Require root
#	f_require_root

# PATH is unnecessary since it's already there, but it doesn't hurt anything.
ComChapPath="/usr/local/bin"
PATH="$PATH:$ComChapPath"
ComSkipINI="/etc/comskip/comskip-DEFAULT.ini"
PVFlockFile="/tmp/process-video-file.lock"
ComchaplockFile="/tmp/comchap.lock"
origFile="$1"
HandbrakePreset="/etc/HandBrake/Lane Highest Quality.json"
tmpHEVC="/tmp/tmpHEVC"
uuid=$(uuidgen)
#tmpFile="/tmp/$1.tmp"
#tmpEncode="/tmp/$1.mkv"
#tmpSrt="/tmp/$1.srt"
# dvrPostLog="/media/8eeb64f5-b001-47d0-a261-bbee8a83d11d/plexdvr/dvrProcessing.log"

# Check for input file
if (( $# < 1 )); then
    echo "No input file specified."
	exit -1
	fi
if ! exiftool -s3 -MIMEType "$1" | grep video > /dev/null ; then 
    echo "Not a video file: $1"
	exit -1
	fi

echo A

# Make sure comskip is installed
# if $(f_is_installed "comskip"); then true ; else apt-get -y install comskip; fi

# Make sure exiftool is installed
# if $(f_is_installed "exiftool"); then true ; else apt-get -y install exiftool; fi

# Make sure mediainfo is installed
# if $(f_is_installed "mediainfo"); then true ; else apt-get -y install mediainfo; fi

echo B

# Create lock file to prevent other post-processing from running simultaneously
echo && echo "Creating lock file '$PVFlockFile' for processing '$origFile'" # | tee -a $dvrPostLog
touch "$PVFlockFile"
 
echo C

# Mark and cut commercials
echo && echo "cut from '$origFile'" # | tee -a $dvrPostLog
comcut --lockfile='ComchaplockFile' --comskip-ini="$ComSkipINI" "$origFile"

echo D

echo && echo "Render the HEVC version"
HandBrakeCLI --preset-import-file "$HandbrakePreset" -i "$origFile" -o "$tmpHEVC"

echo E

echo && echo "Replace and tag the $origFile"
DIR="$(dirname "${origFile}")"
filename=$(basename -- "$origFile")
extension="${filename##*.}"
filename="${filename%.*}"
# rm -f "$origFile"
# mv "$tmpHEVC" "$DIR/$filename.mp4"
exiftool -overwrite_original -Information="comskip/comcut applied $(date -u)" "$tmpHEVC"
mv "$tmpHEVC" "$DIR/$filename.mp4"

echo F

# Leave status in the user's home directory
echo "$(date) $origFile" > ~/last-video-processed

echo G

# Remove lock file
echo && echo "Done processing '$origFile' removing lock" # | tee -a $dvrPostLog
rm $PVFlockFile

echo H

# Include script footer file
	f_debug_variable "script_footer" "${PATHNAME[script_footer]}"
	source "${PATHNAME[script_footer]}"

exit 0

echo I

############################################################################################

exit -1

# Original script below:
# 
# 
# #!/bin/csh
# 
# set path = ($path /usr/local/bin)
# set lockFile = '/tmp/dvrProcessing.lock'
# set origFile = "$1"
# set tmpFile = "$1.tmp"
# set tmpEncode = "$1.mkv"
# set tmpSrt = "$1.srt"
# set dvrPostLog = '/media/8eeb64f5-b001-47d0-a261-bbee8a83d11d/plexdvr/dvrProcessing.log'
# 
# #Wait if post processing is already running
# while ( -f $lockFile )
#     echo "'$lockFile' exists, sleeping processing of '$origFile'" | tee $dvrPostLog
#     sleep 10
# end
# 
# #Create lock file to prevent other post-processing from running simultaneously
# echo "Creating lock file for processing '$origFile'" | tee -a $dvrPostLog
# touch $lockFile
# 
# #Mark and cut commercials
# echo "cut from '$origFile'" | tee -a $dvrPostLog
# /media/8eeb64f5-b001-47d0-a261-bbee8a83d11d/plexdvr/comchap/comcut --lockfile=/tmp/ComchaplockFile --comskip-ini=/media/8eeb64f5-b001-47d0-a261-bbee8a83d11d/plexdvr/comskip.ini "$origFile"
# 
# #Pull CC from file to SRT file
# echo "Pulling Closed captions from '$origFile' to SRT file" | tee -a $dvrPostLog
# ccextractor "$origFile" -o "$tmpSrt"
# 
# #Encode file to H.264 with mkv container using ffmpeg and mux in CC srt
# echo "Re-encoding '$origFile' to MKV file while adding cc data" | tee -a $dvrPostLog
# /usr/bin/ffmpeg -i "$origFile" -i "$tmpSrt" -map 0 -map 1 -acodec copy -scodec copy -c:v libx264 -preset medium -profile:v high -level 4.0 -deinterlace "$tmpEncode"
# 
# #Remove SRT file
# echo "Remove SRT file" | tee -a $dvrPostLog
# rm -f "$tmpSrt"
# 
# #Rename first transcoded file to temp file in case no subtitles
# echo "Rename transcoded file to tmp file" | tee -a $dvrPostLog
# mv -f "$tmpEncode" "$tmpFile"
# 
# #Overwrite original ts file with the transcoded file
# echo "Removing '$origFile'" | tee -a $dvrPostLog
# mv -f "$tmpFile" "$origFile"
# 
# #Remove lock file
# echo "Done processing '$origFile' removing lock" | tee -a $dvrPostLog
# rm $lockFile
# 
# exit 0
# 
# 