#!/bin/bash
# process_ts
# Usage: process_ts <input_file> <root_work_path> <root_storage_path>
# No final / on either path. For system root, use ""

INSTRING=$1
ROOT_WORK_PATH=$2
ROOT_STORAGE_PATH=$3

INSTRING_LENGTH=${#INSTRING}
ROOT_WORK_PATH_LENGTH=${#ROOT_WORK_PATH}
RELATIVE_PATH_LENGTH=$[INSTRING_LENGTH-ROOT_WORK_PATH_LENGTH]
RELATIVE_PATH=${INSTRING: -ROOT_WORK_PATH_LENGTH}

echo "Instring length: $INSTRING_LENGTH"
echo "Root work path length: $ROOT_WORK_PATH_LENGTH"
echo "Relative path length: $RELATIVE_PATH_LENGTH"

RELATIVE_PATH=${INSTRING: -ROOT_WORK_PATH_LENGTH}

echo "In: $INSTRING"
echo "Work: $ROOT_WORK_PATH"
echo "Relative path: $RELATIVE_PATH"

#echo "Storage: $ROOT_STORAGE_PATH"
#echo "Storage length: ${#ROOT_STORAGE_PATH}"

#echo "Without Work: ${INSTRING: -($ROOT_WORK_PATH_LENGTH)}"
#echo "Without Work: ${INSTRING: -3}"
#echo "Out: $3/${INSTRING: -1-(${#ROOT_WORK_PATH})-1}"
echo ""
