#!/bin/bash
# restore-archive

# Include script setup file
	source script-setup
	if [ ! $FUNCTIONS_ARE_DEFINED ]; then echo $0: Functions not defined. Aborting; logger $0: Functions not defined. Aborting; exit 1; fi
	if [ ! $VARIABLES_ARE_DEFINED ]; then echo $0: Variables not defined. Aborting; logger $0: Variables not defined. Aborting; exit 1; fi

# Require root
	f_require_root

# Make sure the archive file is specified
	if [ $# -lt 1 ]; then
		f_log_and_echo "$0: FATAL: No archive file specified."
		echo "USAGE: $0 ArchivePathAndFile [RestorePointDirectory]"
		echo "  Default RestorePointDirecty = /var/restore-points/(RestoreStartDateAndTime)"
		exit 1
		fi

# Make sure the archive file exists
	if $(f_is_file "$1"); then
		f_log_and_echo "$0: FATAL: \"$1\" is not a file."
		echo "USAGE: $0 ArchivePathAndFile [RestorePointDirectory]"
		echo "  Default RestorePointDirectory = /var/restore-points/(RestoreStartDateAndTime)"
		echo "  Using the default RestorePointDirectory is recommended."
		exit 1
		fi

# Make the restore point directory
	RESTORE_POINT="/var/restore-points/$START_DATEANDTIMESTAMP"
	if [ $# -gt 1 ]; then
		RESTORE_POINT="$2"
		fi
	mkdir -p "$RESTORE_POINT"
	if [ $? -gt 0 ]; then
		f_log_and_echo "$0: FATAL: Can't create restore point \"$2\""
		exit 1
		fi

# Start the restoration
	tar -zvxf "$1" -C "$RESTORE_POINT" 
	if [ $? -gt 0 ]; then
		f_log_and_echo "$0: FATAL: Restore from \"$1\" to \"$RESTORE_POINT\" failed."
		exit 1
		fi

# Update log
	echo
	echo Restore from \"$1\" to \"$RESTORE_POINT\" completed $(/bin/date '+%Y-%m-%d-%H-%M-%S-%Z')
	echo Restore from \"$1\" to \"$RESTORE_POINT\" completed $(/bin/date '+%Y-%m-%d-%H-%M-%S-%Z') >> $COLD_BACKUP_LOG

# Include script footer file
	f_debug_variable "script_footer" "${PATHNAME[script_footer]}"
	source "${PATHNAME[script_footer]}"

exit 0
