#!/bin/bash

# Include script setup file
	source script-setup
	if [ ! $FUNCTIONS_ARE_DEFINED ]; then echo $0: Functions not defined. Aborting; logger $0: Functions not defined. Aborting; exit 1; fi
	if [ ! $VARIABLES_ARE_DEFINED ]; then echo $0: Variables not defined. Aborting; logger $0: Variables not defined. Aborting; exit 1; fi

if [ -z "$1" ]; then
  echo "Usage: rip \"Title (year) [ movie | <minimum_number_of_seconds> ]\" &"
  exit -1
  fi

if [ -z "$2" ]; then
    MINLENGTH=1200
  else if [ "$2" == "movie" ]; then
    MINLENGTH=4500
    else MINLENGTH=$2
    fi
  fi

f_require_value "MakeMKV Program Path" "${PATHNAME[makemkvcon]}"
f_require_value "MakeMKV Output Directory" "$MAKEMKV_OUTPUT_DIRECTORY"

# Delete the target directory if it already exists.
# Useful if it's necessary to re-rip a DVD.
	sudo -u $RUN_AS rm -fr "$MAKEMKV_OUTPUT_DIRECTORY/$1"
# Create the target directory.
	sudo -u $RUN_AS mkdir -p "$MAKEMKV_OUTPUT_DIRECTORY/$1"
# Test that the directory creation worked.
	f_require_directory "$MAKEMKV_OUTPUT_DIRECTORY/$1"

sudo -u $RUN_AS nice "${PATHNAME[makemkvcon]}" --minlength=$MINLENGTH mkv disc:0 all "$MAKEMKV_OUTPUT_DIRECTORY/$1"
exit_status=$?
f_beep
eject
if [ $exit_status -eq 0 ] ; then
  echo "$1: Disk ripping completed successfully." | mail "$TEXT_ALERTS"
  else echo "$1: Disk ripping FAILED. Code $exit_status" | mail "$TEXT_ALERTS"
  fi

# Include script footer file
	f_debug_variable "script_footer" "${PATHNAME[script_footer]}"
	source "${PATHNAME[script_footer]}"

exit $exit_status
