#!/bin/bash
# rip

# Include script setup file
source $(dirname $0)/script-setup

if [ -z "$1" ]; then
  echo "Usage: rip \"Title (year) [ movie | <minimum_number_of_seconds> ]\" &"
  exit -1
  fi

if [ -z "$2" ]; then
    MINLENGTH=1200
  else if [ "$2" == "movie" ]; then
    MINLENGTH=4500
    else MINLENGTH=$2
    fi
  fi

f_require_config "makemkv.program"
f_require_config "makemkv.output.directory"

mkdir -p "${LANE_CONFIG[makemkv.output.directory]}/$1"
f_require_directory "${LANE_CONFIG[makemkv.output.directory]}/$1"

"${LANE_CONFIG[makemkv.program]}" --minlength=$MINLENGTH mkv disc:0 all "${LANE_CONFIG[makemkv.output.directory]}/$1"
exit_status=$?
if [ $exit_status -eq 0 ] ; then
  echo "$1: Disk ripping completed successfully." | mail "${LANE_CONFIG[system.lane-cell]}"
  else echo "$1: Disk ripping FAILED. Code $exit_status" | mail "${LANE_CONFIG[system.lane-cell]}"
  fi
eject
exit $?
