#!/bin/bash

# Include script setup file
	source script-setup
	if [ ! $FUNCTIONS_ARE_DEFINED ]; then echo $0: Functions not defined. Aborting; logger $0: Functions not defined. Aborting; exit 1; fi
	if [ ! $VARIABLES_ARE_DEFINED ]; then echo $0: Variables not defined. Aborting; logger $0: Variables not defined. Aborting; exit 1; fi

# Require root
	f_require_root

# Require server nuc01
	f_only_on_server "nuc01"

# Show name, usage, and example.
	echo ""
	echo "$(basename $0)"
	echo ""
	echo "  USAGE:" "$(basename $0)" [source file system] [source content directory]
	echo "     [target file system]" [target content directory]
	echo "EXAMPLE:" "$(basename $0)" "\"/mnt/12TBB\"" "\"\"" "\"/mnt/12TBA\"" "\"\""
	echo ""

# Test for proper number of parameters
	if [ "$#" -ne 4 ]; then
		f_die "Illegal number of parameters." true
		fi

# Assign variables from program parameters
	SOURCE_FILE_SYSTEM="$1"
	SOURCE_PLEX_CONTENT_DIR="$2"
	TARGET_FILE_SYSTEM="$3"
	TARGET_PLEX_CONTENT_DIR="$4"

# Mount source file system
	if ! $(f_mount_fs_as_rw "$SOURCE_FILE_SYSTEM") ; then
		f_die "$SOURCE_FILE_SYSTEM cannot be mounted." true
		fi

# Mount target file system
	if ! $(f_mount_fs_as_rw "$TARGET_FILE_SYSTEM") ; then
		f_die "$TARGET_FILE_SYSTEM cannot be mounted." true
		fi

# Report that the needed file systems are mounted successfully.
	echo Source and target file systems mounted successfully.

# Backup all Plex content directories using rsync
#	for x in {1..3} # Do it three times to catch anything added while this script is running
#		do
			for this_directory in "plex"
				do
					SOURCE_DIR="$SOURCE_PLEX_CONTENT_DIR/$this_directory"
					TARGET_DIR="$TARGET_PLEX_CONTENT_DIR/$this_directory"
					# echo
					# echo Backing up $SOURCE_DIR to $TARGET_DIR
					rsync -aloprtvE --delete "$SOURCE_FILE_SYSTEM/$SOURCE_DIR/"* "$TARGET_FILE_SYSTEM/$TARGET_DIR"
				done
#		done

# Include script footer file
	f_debug_variable "script_footer" "${PATHNAME[script_footer]}"
	source "${PATHNAME[script_footer]}"

exit 0
