#!/bin/bash

# Include script setup file
	source script-setup
    source _functions-staging
	if [ ! $FUNCTIONS_ARE_DEFINED ]; then echo $0: Functions not defined. Aborting; logger $0: Functions not defined. Aborting; exit 1; fi
	if [ ! $VARIABLES_ARE_DEFINED ]; then echo $0: Variables not defined. Aborting; logger $0: Variables not defined. Aborting; exit 1; fi

# After 9:59pm
	echo Hour: $(date +%H)
	if [ "$(date +%H)" -gt "21" ]; then echo "TOO LATE"; exit 1; fi
# Before 7am
	if [ "$(date +%H)" -lt "7" ]; then echo "TOO EARLY"; exit 1; fi
# Uninterruptible program is running
	RUNNING_PROGRAMS='/usr/bin/tar\|'
	RUNNING_PROGRAMS+='/usr/local/sbin/backup\|'
	RUNNING_PROGRAMS+='/usr/local/sbin/cold-backup\|'
	RUNNING_PROGRAMS+='/usr/local/sbin/cold-restore\|'
	RUNNING_PROGRAMS+='/usr/local/sbin/configure-installer\|'
	RUNNING_PROGRAMS+='/usr/local/sbin/db-backup\|'
	RUNNING_PROGRAMS+='/usr/local/sbin/initialize-server\|'
	RUNNING_PROGRAMS+='/usr/local/sbin/install-virtual-host\|'
	RUNNING_PROGRAMS+='/usr/local/sbin/rip\|'
	RUNNING_PROGRAMS+='/usr/local/sbin/upd\|'
	RUNNING_PROGRAMS+='/usr/bin/apt-get\|'
	RUNNING_PROGRAMS+='/usr/bin/rsync\|'
	RUNNING_PROGRAMS+='/usr/bin/HandBrakeCLI\|'
	RUNNING_PROGRAMS+='Transcoder'
	ps -ef | grep $RUNNING_PROGRAMS
	if [ $(ps -ef | grep $RUNNING_PROGRAMS | wc -l) -ne "1" ]; then echo "UNINTERRUPTIBLE PROGRAMS RUNNING"; exit 1; fi
# Anyone logged in
	USERS_LOGGED_IN=f_users_logged_in
	echo Users logged in: $USERS_LOGGED_IN
	if [ $USERS_LOGGED_IN -ne "0" ]; echo "USERS LOGGED IN"; then exit 1; fi

# echo "Starting safe reboot." | mail text_alerts
	upd
	rm $RESET_FLAG_FILE
	echo "Reboot here."
#	init 6

# Include script footer file
	f_debug_variable "script_footer" "${PATHNAME[script_footer]}"
	source "${PATHNAME[script_footer]}"

exit 0
