#!/bin/bash
# show-plex-ts-files

source $(dirname $0)/script-setup

ROOT_DVR_WORK=$(f_get-config pathname.root-dvr-work)
ROOT_DVR_STORE=$(f_get-config pathname.root-dvr-store)

find "$ROOT_DVR_WORK" -type f -name "*.ts" -print
echo ""
ps -ef | grep "HandBrake\|cskipper\|sleep\|shrink-plex-ts-files"
echo ""
df -Ht ext4

source $(dirname $0)/script-footer
exit 0
