#!/bin/bash
# show-plex-ts-files

production_mode=true
debug_mode=false
# debug_mode=true
if $debug_mode ; then
  set -x
  fi

# Make sure only root can run our script
if [[ $EUID -ne 0 ]]; then
  echo "This script must be run as root."
  exit 1
fi

# Confirm that this host is oz
if [[ $(hostname -s) != "oz" ]]; then
  echo "This script can ony be run on server oz."
  exit 1
fi

WORK_ROOT="/mnt/ssd1tb/plex"

find "$WORK_ROOT" -type f -name "*.ts" -print

exit 0
