#!/bin/bash
# show-variables

# Include script setup file
source $(dirname $0)/script-setup

( set -o posix ; set )

# Include script footer file
f_debug_variable "script_script_footer_pathname" "${LANE_CONFIG[script_script_footer_pathname]}"
source ${PATHNAME[script_footer]}

