#!/bin/bash
# Based on https://superuser.com/questions/1001973/bash-find-string-index-position-of-substring

MYNAME="Lane Hensley"
MYEMAIL="lane@lanehensley.org"

COMMANDNAME="substr"
VERSION="0.1"
COLOPHON="$MYNAME, $MYEMAIL"

SEARCHSTRING="$1"
FULLSTRING="$2"
# FLAG="$3"

if [ "$FULLSTRING" = "" ] ; then
	echo "$COMMANDNAME v$VERSION"
	echo "by $COLOPHON"
	echo
	echo "Usage: $COMMANDNAME STRING_SEARCHED_FOR STRING_SEARCHED"
	echo "If the search succeeds, $COMMANDNAME returns the offset within STRING_SEARCHED "
	echo "  where STRING_SEARCHED_FOR is found."
	echo "If the search fails, $COMMANDNAME returns -1."
	exit -1
	fi

REMAINDER=${FULLSTRING#*$SEARCHSTRING}
OFFSET=$(( ${#FULLSTRING} - ${#REMAINDER} - ${#SEARCHSTRING} ))
if [ $? -ne 0 ] ; then 
	echo "Not found. Exit code is -1."
	exit -1
	fi
echo "Found. The exit code is the offset, ($OFFSET)."
# echo "Remainder: "'$REMAINDER'"
exit $OFFSET
