#!/bin/bash

# Include script setup file
	source script-setup
	if [ ! $FUNCTIONS_ARE_DEFINED ]; then echo $0: Functions not defined. Aborting; logger $0: Functions not defined. Aborting; exit 1; fi
	if [ ! $VARIABLES_ARE_DEFINED ]; then echo $0: Variables not defined. Aborting; logger $0: Variables not defined. Aborting; exit 1; fi

# Require root
	f_require_root

# Set key file permissions ############################################
	f_apply_plex_permissions

# Set variables
SLEEP=15
# rsync options used
#    -a = archive mode, equivalent to -rlptgoD
#    -g = preserve group ownership
#    -l = recreate symlinks on destination
#    -o = preserve owner
#    -p = preserve permissions
#    -q = quiet
#    -r = recursive (includes subdirectories)
#    -t = preserve modification times
#    -D = preserve device files and special files
#    -E = preserve executability
#    --delete = delete extraneous files from dest dirs
RSYNC="nice rsync -aopqrtE --delete"
PLEXBASE=/var/lib/plexmediaserver
PLEXMETA="$PLEXBASE/Library/Application Support"
PLEX1=/mnt/12TBB/Plex
PLEXX=/mnt/12TBB/Plexx
POOL01=$PLEX1/Pool01-1TB
POOL02=$PLEX1/Pool02-1TB
POOL03=$PLEX1/Pool03-1TB
POOL04=$PLEX1/Pool04-1TB
POOL05=$PLEX1/Pool05-1TB
POOL06=$PLEX1/Pool06-1TB
POOL07=$PLEX1/Pool07-1TB
POOL08=$PLEX1/Pool08-1TB
POOL09=$PLEX1/Pool09-1TB
POOL10=$PLEX1/Pool10-1TB
ARCBERTHA=/mnt/bertha
ARCGOFLEX=/mnt/GoFlex1T01
ARCBLACK4T=/mnt/Black4T01
ARCSILVER5TA=/mnt/Silver5TB-A
ARCSILVER5TB=/mnt/Silver5TB-B

# Mount needed filesystems
mount $ARCBERTHA > /dev/null 2> /dev/null &
mount $ARCBLACK4T > /dev/null 2> /dev/null &
mount $ARCSILVER5TA > /dev/null 2> /dev/null &
mount $ARCSILVER5TB > /dev/null 2> /dev/null &

# Run a system update
$PROGRAM_DIRECTORY/upd > /dev/null 2> /dev/null &

# Kill renmants of earlier instances
killall -9 timeout > /dev/null 2> /dev/null &
killall -9 rsync > /dev/null 2> /dev/null &

# Set ownerships and permissions
chown -R plex:plex $PLEXBASE > /dev/null 2> /dev/null &
chown -R plex:plex $PLEX1 > /dev/null 2> /dev/null &
chown -R plex:plex $PLEXX > /dev/null 2> /dev/null &
find $PLEXBASE -type d -print -exec chmod 775 {} \; > /dev/null 2> /dev/null &
find $PLEXBASE -type f -print -exec chmod 664 {} \; > /dev/null 2> /dev/null &
find $PLEX1 -type d -print -exec chmod 775 {} \; > /dev/null 2> /dev/null &
find $PLEX1 -type f -print -exec chmod 664 {} \; > /dev/null 2> /dev/null &
find $PLEXX -type d -print -exec chmod 775 {} \; > /dev/null 2> /dev/null &
find $PLEXX -type f -print -exec chmod 664 {} \; > /dev/null 2> /dev/null &

# Run syncs

sleep $SLEEP

$RSYNC \
  $POOL01 \
  $POOL02 \
  $POOL03 \
  $POOL04 \
  $POOL05 \
  $ARCSILVER5TA/archives/ > /dev/null 2> /dev/null &

# $RSYNC \
#   $POOL06 \
#   $POOL07 \
#   $POOL08 \
#   $POOL09 \
#   $POOL10 \
#   $ARCSILVER5TB/archives > /dev/null 2> /dev/null &

#$RSYNC \
#  $POOL04 \
#  $POOL05 \
#  $POOL06 \
#  $POOL07 \
#  $ARCBLACK4T/archives > /dev/null 2> /dev/null &

# $RSYNC \
#   "$PLEXMETA" \
#   $ARCBERTHA > /dev/null 2> /dev/null &

# Remove all remaining tempfiles. #####################################
source $SCRIPTS_DIRECTORY/cleanup-and-exit

