#!/bin/bash

# Include script setup file
	source script-setup
	if [ ! $FUNCTIONS_ARE_DEFINED ]; then echo $0: Functions not defined. Aborting; logger $0: Functions not defined. Aborting; exit 1; fi
	if [ ! $VARIABLES_ARE_DEFINED ]; then echo $0: Variables not defined. Aborting; logger $0: Variables not defined. Aborting; exit 1; fi

# Require server nuc01
	f_only_on_server red

# Make target directories
	mkdir -p /mnt/12TBA/archives/nuc01/plex/12TBB
	mkdir -p /mnt/12TBA/archives/nuc01/plex/work
	
# Sync files to red
	rsync -r --delete nuc01:/mnt/12TBB/Plex/* /mnt/12TBA/archives/nuc01/plex/12TBB
	rsync -r --delete nuc01:/var/lib/plexmediaserver/Library/work /mnt/12TBA/archives/nuc01/plex/work

# Include script footer file
	f_debug_variable "script_footer" "${PATHNAME[script_footer]}"
	source "${PATHNAME[script_footer]}"

exit 0
