#!/bin/bash
# tellme

# Include script setup file
	source script-setup
    source _functions-staging
	if [ ! $FUNCTIONS_ARE_DEFINED ]; then echo $0: Functions not defined. Aborting; logger $0: Functions not defined. Aborting; exit 1; fi
	if [ ! $VARIABLES_ARE_DEFINED ]; then echo $0: Variables not defined. Aborting; logger $0: Variables not defined. Aborting; exit 1; fi

# Define UUID stuff
	THIS_TEMP_FILE="/tmp$0 - $(uuidgen)"
	mkdir -p $(dirname "$THIS_TEMP_FILE")
	touch "$THIS_TEMP_FILE"

# Compose the message
	echo $(date)                                                                                         >  "$THIS_TEMP_FILE" 2>&1
	echo $THIS_TEMP_FILE                                                                                 >> "$THIS_TEMP_FILE" 2>&1
	# echo $(top -b -n 1)																				 >> "$THIS_TEMP_FILE" 2>&1
	ls -alh $THIS_ARCHIVE_DIRECTORY/*                                                                    >> "$THIS_TEMP_FILE" 2>&1
	tail $ADMIN_HOME_DIR/.coldstorage.log                                                                >> "$THIS_TEMP_FILE" 2>&1
#	ps -ef | grep "?" | grep -E '/usr/local/sbin|/lib/plexmediaserver/Plex Media Server|/mysql|/postfix' >> "$THIS_TEMP_FILE" 2>&1
    cat /var/log/syslog | grep -E 'dvr|lgh|Sleeping'                                                     >> "$THIS_TEMP_FILE" 2>&1
	ps -ef | grep lgh >> "$THIS_TEMP_FILE" 2>&1                                                          >> "$THIS_TEMP_FILE" 2>&1
	df -HT | grep -E "ntfs|fuseblk|ext4"                                                                 >> "$THIS_TEMP_FILE" 2>&1
	if [ "$HOSTNAME"=="nuc01" ]; then
		d="/var/lib/plexmediaserver/Library/work"; f="*.ts"; 	echo $(find "$d" -name "$f" -print | wc -l) $f in $d	 >> "$THIS_TEMP_FILE" 2>&1
		d="/var/lib/plexmediaserver/Library/work"; f="*.m4v"; 	echo $(find "$d" -name "$f" -print | wc -l) $f in $d	 >> "$THIS_TEMP_FILE" 2>&1
		d="/mnt/cloteal/Plex/Pool06-1TB/dvr-nuc01"; 	f="*.ts"; 	echo $(find "$d" -name "$f" -print | wc -l) $f in $d	 >> "$THIS_TEMP_FILE" 2>&1
		d="/mnt/cloteal/Plex/Pool06-1TB/dvr-nuc01"; 	f="*.m4v"; 	echo $(find "$d" -name "$f" -print | wc -l) $f in $d	 >> "$THIS_TEMP_FILE" 2>&1
		d="/var/lib/plexmediaserver/Library/work"; echo $(du -hs "$d") stored in $d						 >> "$THIS_TEMP_FILE" 2>&1
		d="/mnt/cloteal/Plex/Pool06-1TB/dvr-nuc01"; 	echo $(du -hs "$d") stored in $d						 >> "$THIS_TEMP_FILE" 2>&1
		fi
	if [ "$HOSTNAME"=="oz" ]; then
		d="/mnt/ssd1tb"; f="*.ts"; 	echo $(find "$d" -name "$f" -print | wc -l) $f in $d					 >> "$THIS_TEMP_FILE" 2>&1
		d="/mnt/ssd1tb"; f="*.m4v"; 	echo $(find "$d" -name "$f" -print | wc -l) $f in $d					 >> "$THIS_TEMP_FILE" 2>&1
		d="/mnt/ext10tb01"; 	f="*.ts"; 	echo $(find "$d" -name "$f" -print | wc -l) $f in $d				 >> "$THIS_TEMP_FILE" 2>&1
		d="/mnt/ext10tb01"; 	f="*.m4v"; 	echo $(find "$d" -name "$f" -print | wc -l) $f in $d				 >> "$THIS_TEMP_FILE" 2>&1
		d="/mnt/ssd1tb"; echo $(du -hs "$d") stored in $d												 >> "$THIS_TEMP_FILE" 2>&1
		d="/mnt/ext10tb01"; 	echo $(du -hs "$d") stored in $d												 >> "$THIS_TEMP_FILE" 2>&1
		fi

# Send the message
    cat "$THIS_TEMP_FILE"
	# echo $(cat "$THIS_TEMP_FILE") | unix2dos | mail $ADMIN_EMAIL
	unlink "$THIS_TEMP_FILE"
	# f_beep

# Include script footer file
	f_debug_variable "script_footer" "${PATHNAME[script_footer]}"
	source "${PATHNAME[script_footer]}"

exit 0
