#!/bin/bash
# tellme

# Include script setup file
	source script-setup
    source _functions-staging
	if [ ! $FUNCTIONS_ARE_DEFINED ]; then echo $0: Functions not defined. Aborting; logger $0: Functions not defined. Aborting; exit 1; fi
	if [ ! $VARIABLES_ARE_DEFINED ]; then echo $0: Variables not defined. Aborting; logger $0: Variables not defined. Aborting; exit 1; fi

# Define UUID stuff
	THIS_TEMP_FILE="/tmp$0 - $(uuidgen)"
	mkdir -p $(dirname "$THIS_TEMP_FILE")
	touch "$THIS_TEMP_FILE"

# Compose the message
    cat /var/log/syslog | grep dvr > "$THIS_TEMP_FILE" 2>&1
	df -Ht ext4 >> $THIS_TEMP_FILE 2>&1

# Send the message
	cat "$0: $THIS_TEMP_FILE" | logger
	cat "$0: $THIS_TEMP_FILE" | mail text_alerts $EMAIL_ALERTS
	cat "$0: $THIS_TEMP_FILE"
	unlink "$THIS_TEMP_FILE"
	f_beep

# Include script footer file
	f_debug_variable "script_footer" "${PATHNAME[script_footer]}"
	source "${PATHNAME[script_footer]}"

exit 0
