#!/bin/bash
# tellme

# Include script setup file
	source script-setup
    source _functions-staging
	if [ ! $FUNCTIONS_ARE_DEFINED ]; then echo $0: Functions not defined. Aborting; logger $0: Functions not defined. Aborting; exit 1; fi
	if [ ! $VARIABLES_ARE_DEFINED ]; then echo $0: Variables not defined. Aborting; logger $0: Variables not defined. Aborting; exit 1; fi

# Define UUID stuff
	THIS_TEMP_FILE="/tmp$0 - $(uuidgen)"
	mkdir -p $(dirname "$THIS_TEMP_FILE")
	touch "$THIS_TEMP_FILE"

# Compose the message
	echo $(date)                                                                                         >  "$THIS_TEMP_FILE" 2>&1
	echo $THIS_TEMP_FILE                                                                                 >> "$THIS_TEMP_FILE" 2>&1
    cat /var/log/syslog | grep -E 'dvr|lgh'                                                              >> "$THIS_TEMP_FILE" 2>&1
	ls -alh /mnt/ext10tb01/archives/oz/*                                                                 >> "$THIS_TEMP_FILE" 2>&1
	tail $ADMIN_HOME_DIR/.coldstorage.log                                                                >> "$THIS_TEMP_FILE" 2>&1
	ps -ef | grep "?" | grep -E '/usr/local/sbin|/lib/plexmediaserver/Plex Media Server|/mysql|/postfix' >> "$THIS_TEMP_FILE" 2>&1
	df -Ht ext4                                                                                          >> "$THIS_TEMP_FILE" 2>&1

# Send the message
    cat "$THIS_TEMP_FILE"
	# echo $(cat "$THIS_TEMP_FILE") | unix2dos | mail $ADMIN_EMAIL
	unlink "$THIS_TEMP_FILE"
	f_beep

# Include script footer file
	f_debug_variable "script_footer" "${PATHNAME[script_footer]}"
	source "${PATHNAME[script_footer]}"

exit 0
