#!/bin/bash
# testme

            TIMESTART=$(currenttimeinseconds)
            echo $TIMESTART
            sleep 69
            echo $(currenttimeinseconds)
            echo $(($(currenttimeinseconds) - TIMESTART ))
            echo $(timeformat $(( $(currenttimeinseconds) - TIMESTART )))
              echo "Transcoding to $VIDEONAME complete. Run time $(timeformat $(( $(currenttimeinseconds) - TIMESTART )))"
exit 0
