#!/bin/bash

# Include script setup file
	source script-setup
	if [ ! $FUNCTIONS_ARE_DEFINED ]; then echo $0: Functions not defined. Aborting; logger $0: Functions not defined. Aborting; exit 1; fi
	if [ ! $VARIABLES_ARE_DEFINED ]; then echo $0: Variables not defined. Aborting; logger $0: Variables not defined. Aborting; exit 1; fi

# Require root
	f_require_root

# From plexstatus
	# df -Ht ext4
	# systemctl status plexmediaserver

echo $(f_is_file "$SOURCE_FILE")
echo ! $(f_in_use "$SOURCE_FILE" false)
echo [ $(f_is_file "$SOURCE_FILE") && ! $(f_in_use "$SOURCE_FILE" false ]

# Include script footer file
	f_debug_variable "script_footer" "${PATHNAME[script_footer]}"
	source "${PATHNAME[script_footer]}"

exit 0
