#!/bin/bash
# cold-backup

# Include script setup file
	source script-setup
	if [ ! $FUNCTIONS_ARE_DEFINED ]; then echo $0: Functions not defined. Aborting; logger $0: Functions not defined. Aborting; exit 1; fi
	if [ ! $VARIABLES_ARE_DEFINED ]; then echo $0: Variables not defined. Aborting; logger $0: Variables not defined. Aborting; exit 1; fi

#!/bin/sh

lockdir=/tmp/upload-to-nuc01.lock

if ! mkdir "$lockdir"; then
   f_die "rsync already in progress"
fi

trap 'rmdir "$lockdir"' EXIT

PATH=$PATH:/usr/local/bin

rsync -aloprtvE --remove-source-files $VIDEO_STORE_DIRECTORY/* nuc01.lanehensley.org:/mnt/12TBB/plex-dvr

# Include script footer file
	f_debug_variable "script_footer" "${PATHNAME[script_footer]}"
	source "${PATHNAME[script_footer]}"

exit 0
