#!/bin/bash

# Include script setup file
	source script-setup
	if [ ! $FUNCTIONS_ARE_DEFINED ]; then echo $0: Functions not defined. Aborting; logger $0: Functions not defined. Aborting; exit 1; fi
	if [ ! $VARIABLES_ARE_DEFINED ]; then echo $0: Variables not defined. Aborting; logger $0: Variables not defined. Aborting; exit 1; fi

# Require root
	f_require_root

HOME_DIRECTORY="/home/lhensley"

# Secure webmin
DIRNAME=/usr/share/webmin
# cp /usr/local/sbin/.htaccess.all.off $DIRNAME/.htaccess
rm $DIRNAME/.htaccess

# Secure phpmyadmin
DIRNAME=/usr/share/phpmyadmin
# cp /usr/local/sbin/.htaccess.all.off $DIRNAME/.htaccess
rm $DIRNAME/.htaccess

# Secure father-lane.gets-it
DIRNAME=/var/www/father-lane.gets-it/wp-admin
# cp /usr/local/sbin/.htaccess.all.off $DIRNAME/.htaccess
rm $DIRNAME/.htaccess

# Secure html
DIRNAME=/var/www/html/wp-admin
# cp /usr/local/sbin/.htaccess.all.off $DIRNAME/.htaccess
rm $DIRNAME/.htaccess

# Secure lane.likes-pie
DIRNAME=/var/www/lane.likes-pie/wp-admin
# cp /usr/local/sbin/.htaccess.all.off $DIRNAME/.htaccess
rm $DIRNAME/.htaccess

# Secure limesurvey
DIRNAME=/var/www/limesurvey/admin
# cp /usr/local/sbin/.htaccess.all.off $DIRNAME/.htaccess
rm $DIRNAME/.htaccess

# Secure music.from-tx.com
DIRNAME=/var/www/music.from-tx.com/wp-admin
# cp /usr/local/sbin/.htaccess.all.off $DIRNAME/.htaccess
rm $DIRNAME/.htaccess

# Restart web secure
/etc/init.d/apache2 restart

# Include script footer file
	f_debug_variable "script_footer" "${PATHNAME[script_footer]}"
	source "${PATHNAME[script_footer]}"
