#!/bin/bash
# upd
#
# Include header file
logger Begin $0
PROGRAM_DIRECTORY=$(dirname $0)
source $PROGRAM_DIRECTORY/script-setup

# Update from github.com
_git

# Invoke /usr/local/sbin/apply-configs
# chmod 500 $SBIN_DIR/apply-configs
$SBIN_DIR/apply-configs

# Update Dynamic DNS
ddclient -daemon 0

# Run apt updates
/usr/local/sbin/_run_apt_updates
