#!/bin/bash

# Include script setup file
	source script-setup
	if [ ! $FUNCTIONS_ARE_DEFINED ]; then echo $0: Functions not defined. Aborting; logger $0: Functions not defined. Aborting; exit 1; fi
	if [ ! $VARIABLES_ARE_DEFINED ]; then echo $0: Variables not defined. Aborting; logger $0: Variables not defined. Aborting; exit 1; fi

# Require root
	f_require_root

# Update from github.com
	f_git

# Update Dynamic DNS
#	if $(f_is_file "/usr/sbin/ddclient"); then ddclient -daemon 0; fi

# Other updates
	f_upd

# This heads off a network manager problem defined at https://askubuntu.com/questions/71159/network-manager-says-device-not-managed
	# touch /etc/NetworkManager/conf.d/10-globally-managed-devices.conf

# Include script footer file
	f_debug_variable "script_footer" "${PATHNAME[script_footer]}"
	source "${PATHNAME[script_footer]}"


