#!/bin/bash	

# Include script setup file
	source script-setup
	if [ ! $FUNCTIONS_ARE_DEFINED ]; then echo $0: Functions not defined. Aborting; logger $0: Functions not defined. Aborting; exit 1; fi
	if [ ! $VARIABLES_ARE_DEFINED ]; then echo $0: Variables not defined. Aborting; logger $0: Variables not defined. Aborting; exit 1; fi

# Arguments
# $1: latest release from https://community.limesurvey.org/downloads/, VERY latest, not LTS.

# Require root
	f_require_root

# Check number of arguments
if [ $# -ne 1 ]; then 
    echo "Please specify the download file."
	echo "You can find it at https://community.limesurvey.org/downloads/"
	echo "If you want to do this manually, see https://manual.limesurvey.org/Upgrading_from_a_previous_version"
	echo "Usage: update-limesurvey DOWNLOAD_URL"
	f_die "$0 failed." false -1
fi

# Define variables
	temp_dir="/tmp/limesurvey"
	install_dir="/var/www/survey.lanehensley.org"
	if ! $(f_is_directory "$install_dir"); then install_dir="/var/www/s2.lanehensley.org"; fi
	if ! $(f_is_directory "$install_dir"); then f_die "Can't find installation directory $install_dir" false -1; fi
	zip_file=$temp_dir/limesurvey.zip
	archive_file=$(echo ~/LimeSurveyArchive-$(date "+%Y.%m.%d-%H.%M.%S.%Z").tar.gz)

# Get rid of any older updates.
	rm -rf "$temp_dir"
    if $(f_is_directory "$temp_dir"); then f_die "Can't remove $temp_dir." false -1; fi
	
# Explain ourselves to the user
	echo Downloading "\"$1\"" to "\"$temp_dir\""

# Try to download the file
	if ! wget "$1" -P "$temp_dir"; then
		f_die "Can't download $1" false -1
		fi

# Try to rename the downloaded file
	if ! mv "$temp_dir/"lime* "$zip_file"; then
		f_die "Can't find LimeSurvey in the downloaded materials." false -1
		fi

# Unzip the downloaded file
	echo "Unzipping the downloaded file."
	if ! unzip -qq "$zip_file" -d /tmp ; then
		f_die "Can't unzip the downloaded file." false -1
		fi

# Test for the presence of a key file to confirm that the download actually is LimeSurvey
	if ! $(f_is_file "$temp_dir/application/core/ConsoleApplication.php"); then
		f_die "The downloaded file doesn't seem to be a LimeSurvey distribution." false -1
		fi

# Remove the downloaded file
	rm "$zip_file"

# Copy over customizations from existing installation
	if $(f_is_file "$install_dir/application/config/security.php"); then
		if ! cp "$install_dir/application/config/security.php" "$temp_dir/application/config/security.php"; then
			f_die "Can't copy over customizations from existing installation." false -1
			fi
		fi
	if ! cp "$install_dir/application/config/config.php" "$temp_dir/application/config/config.php"; then
		f_die "Can't copy over customizations from existing installation." false -1
		fi
	if ! cp -r "$install_dir/upload" "$temp_dir/"; then
		f_die "Can't copy over customizations from existing installation." false -1
		fi

# Archive the existing installation
	echo "Archiving the existing installation."
	if ! tar -zcf "$archive_file" "$install_dir" > /dev/null 2>&1 ; then
		f_die "Can't archive the existing installation." false -1
		fi

# Remove the existing installation
	if ! rm -r "$install_dir/"* ; then
		f_die "Can't remove the existing installation." false -1
		fi

# Install the upgrade
	echo "Installing the upgraded software."
	if ! cp -r "$temp_dir/"* "$install_dir"/ ; then
		f_die "Can't install the upgrade." false -1
		fi

# Assigning ownership of downloaded files.
	if ! chown -R www-data:www-data "$install_dir"; then
		f_die "Can't change ownership of downloaded files." false -1
		fi

# # Update the database schema.
# 	echo "Updating the database schema."
# 	php "$install_dir/application/commands/console.php" updatedb

# Victory lap
	echo ""
	echo "Your upgrade is DONE."
	echo "An archive of the old installation is at $archive_file"
	echo "Make sure to go to the admin page to see in a database update is necessary."
	echo "You may need to clear your browser cache and cookies."

# Include script footer file
	f_debug_variable "script_footer" "${PATHNAME[script_footer]}"
	source "${PATHNAME[script_footer]}"
