#!/bin/bash

# Include script setup file
	source script-setup
	if [ ! $FUNCTIONS_ARE_DEFINED ]; then echo $0: Functions not defined. Aborting; logger $0: Functions not defined. Aborting; exit 1; fi
	if [ ! $VARIABLES_ARE_DEFINED ]; then echo $0: Variables not defined. Aborting; logger $0: Variables not defined. Aborting; exit 1; fi

BASEDIR="/home/$ADMIN_USER/.cryfs-basedir"
MOUNTDIR="/home/$ADMIN_USER/vault"

echo "This script doesn't work yet. Sorry."
exit 1

# Check for presence of remote host argument.
if [ "$#" -eq 0 ]; then
    echo "Usage: syncvault remote-hostname[.domain.tld]"
	exit 1
fi

# Open local vault
cryfs $BASEDIR $MOUNTDIR
if [ $? -ne 0 ]
then
  echo "Could not open $MOUNTDIR on localhost."
  echo "Unmounting local vault."
  cryfs-unmount $MOUNTDIR
  exit 1
fi

# Open remote vault
ssh $1 "cryfs $BASEDIR $MOUNTDIR"
if [ $? -ne 0 ]
then
  echo "Could not open $MOUNTDIR on $1."
  echo "Unmounting vault on $1."
  ssh $1 "cryfs-unmount $MOUNTDIR"
  if [ $? -ne 0 ]
  then
	echo "Count not unmount vault on $1."
  fi
  echo "Unmounting local vault."
  cryfs-unmount $MOUNTDIR
fi

# Do the sync
nice rsync -aE --delete "$MOUNTDIR/$(hostname -s)" "$1:$MOUNTDIR/$(hostname -s)/"

# Unmount remote vault
echo "Unmounting vault on $1."
ssh $1 "cryfs-unmount $MOUNTDIR"
if [ $? -ne 0 ]
then
  echo "Count not unmount vault on $1."
fi

# Unmount local vault
echo "Unmounting local vault."
cryfs-unmount $MOUNTDIR

# Include script footer file
	f_debug_variable "script_footer" "${PATHNAME[script_footer]}"
	source "${PATHNAME[script_footer]}"
