#!/bin/bash
# openvault

BASEDIR="/home/lhensley/.cryfs-basedir"
MOUNTDIR="/home/lhensley/vault"

# Open local vault
echo "Opening $MOUNTDIR directory."
cryfs $BASEDIR $MOUNTDIR
if [ $? -ne 0 ]
then
  echo "Could not open $MOUNTDIR on localhost."
  echo "Unmounting local vault."
  cryfs-unmount $MOUNTDIR
else
  echo "Vault opened successfully."
fi
