#!/bin/bash

# Include script setup file
	source script-setup
	if [ ! $FUNCTIONS_ARE_DEFINED ]; then echo $0: Functions not defined. Aborting; logger $0: Functions not defined. Aborting; exit 1; fi
	if [ ! $VARIABLES_ARE_DEFINED ]; then echo $0: Variables not defined. Aborting; logger $0: Variables not defined. Aborting; exit 1; fi

BASEDIR="/home/lhensley/.cryfs-basedir"
MOUNTDIR="/home/lhensley/vault"

# Open local vault
echo "Opening $MOUNTDIR directory."
cryfs $BASEDIR $MOUNTDIR
if [ $? -ne 0 ]
then
  echo "Could not open $MOUNTDIR on localhost."
  echo "Unmounting local vault."
  cryfs-unmount $MOUNTDIR
else
  echo "Vault opened successfully."
fi

# Include script footer file
	f_debug_variable "script_footer" "${PATHNAME[script_footer]}"
	source "${PATHNAME[script_footer]}"
