#!/bin/bash
# closevault

BASEDIR="/home/lhensley/.cryfs-basedir"
MOUNTDIR="/home/lhensley/vault"

# Close local vault
echo "Closing $MOUNTDIR directory."
if grep -qs "$MOUNTDIR " /proc/mounts; then
    cryfs-unmount $MOUNTDIR
    if [ $? -ne 0 ]
    then
      echo "Could not close $MOUNTDIR on localhost."
    else
      echo "$MOUNTDIR closed successfully."
    fi
else
    echo "$MOUNTDIR is already closed."
fi
