#!/bin/bash
# TEMPORARY script. OK to delete.

# Include script setup file
	source script-setup
	if [ ! $FUNCTIONS_ARE_DEFINED ]; then echo $0: Functions not defined. Aborting; logger $0: Functions not defined. Aborting; exit 1; fi
	if [ ! $VARIABLES_ARE_DEFINED ]; then echo $0: Variables not defined. Aborting; logger $0: Variables not defined. Aborting; exit 1; fi


# POSSIBLE OPTION: USE IF YOU WANT
# Require root
	f_require_root

# Set variables
	X_HOME="/home/lhensley"
	X_A2="$X_HOME/apache2"
	X_OLD="$X_A2/old"
	X_NEW="$X_A2/new"
	X_OLD_ETC="$X_OLD/etc"
	X_NEW_ETC="$X_NEW/etc"
	X_OLD_WWW="$X_OLD/www"
	X_NEW_WWW="$X_NEW/www"

# Do stuff here
	rm -rf "$X_A2"
	mkdir -p "$X_OLD_ETC" "$X_NEW_ETC" "$X_OLD_WWW" "$X_NEW_WWW"
	exit 0

	mkdir -p /home/lhensley/apache2/old/var/www
	mkdir -p /home/lhensley/apache2/new/etc
	mkdir -p /home/lhensley/apache2/new/var/www
	cp -pr /etc/apache2 /home/lhensley/apache2/new/etc/
	cp -pr /etc/letsencrypt /home/lhensley/apache2/new/etc/
	cp -pr /var/www/* /home/lhensley/apache2/new/var/www/
	cp -pr /home/lhensley/cold-backup.2022-04/etc/apache2 /home/lhensley/a2/old/etc/
	cp -pr /home/lhensley/cold-backup.2022-04/etc/letsencrypt /home/lhensley/a2/old/etc/
	cp -pr /home/lhensley/cold-backup.2022-04/var/www/* /home/lhensley/a2/old/var/www/

# Include script footer file
	f_debug_variable "script_footer" "${PATHNAME[script_footer]}"
	source "${PATHNAME[script_footer]}"

exit 0

