#!/bin/bash
# install-utils
# Revised 2020-06-04
# PURPOSE: Install uncomplicated, no-down-side utilities.
# NOTE: This install script can run safely even if the software already is installed.

# Include header file
PROGRAM_DIRECTORY=$(dirname $0)
source $PROGRAM_DIRECTORY/../script-setup
s
function install() {
   logger $0 Installing $1
   DEBIAN_FRONTEND=noninteractive apt-get install -yq $1
   logger $0 Installation of $1 done exit code $?
}

# Get to work
install ufw
# UFW first; others depend on it
install at
install apg                     # Password generator 
install cryfs                   # Encrypted file system
install comskip                 # Commercial skipper for videos
install curl
install ddclient
install exiftool
install fail2ban
install ffmpeg
install filezilla
install gimp
install git && ufw allow git
install gpg
install gzip
install inotify-tools           # Do something when a file is created, deleted, or changed
install net-tools
install openssl
install openvpn
install bridge-utils
install ifupdown
install resolvconf
install ripmime                 # Process files sent by email
install ssh && ufw allow ssh
install sysbench
install tasksel
install unzip
install vim
install wget
install xrdp

ufw allow http
ufw allow https
