#!/bin/bash
# install-utils
# Revised 2020-06-04
# PURPOSE: Install uncomplicated, no-down-side utilities.
# NOTE: This install script can run safely even if the software already is installed.

# Include header file
PROGRAM_DIRECTORY=$(dirname $0)
source $PROGRAM_DIRECTORY/../script-setup

function install() {
   logger Installing $1
   apt-get install -y $1
}

# Get to work
install ufw
install apg
install cryfs
install curl
install ddclient
install fail2ban
install filezilla
install gimp
install git && ufw allow git
install net-tools
install openssl
install openvpn
    install bridge-utils
    install ifupdown
install resolvconf
install ssh && ufw allow ssh
install sysbench
install tasksel
install unzip
install vim
install wget
install xrdp

ufw allow http
ufw allow https
