#!/bin/bash
# install-utils
# PURPOSE: Install uncomplicated, no-down-side utilities.
# NOTE: This install script can run safely even if the software already is installed.

# Include script setup file
	source script-setup
	if [ ! $FUNCTIONS_ARE_DEFINED ]; then echo $0: Functions not defined. Aborting; logger $0: Functions not defined. Aborting; fi
	if [ ! $VARIABLES_ARE_DEFINED ]; then echo $0: Variables not defined. Aborting; logger $0: Variables not defined. Aborting; fi

# Get to work
f_install ufw
# UFW first; others depend on it
f_install at
f_install apg                     # Password generator 
f_install cryfs                   # Encrypted file system
f_install comskip                 # Commercial skipper for videos
f_install curl
f_install ddclient
f_install exiftool
f_install fail2ban
f_install ffmpeg
f_install filezilla
f_install ghostscript             # Compressing PDF scans
f_install gimp
f_install git && ufw allow git
f_install gpg
f_install gzip
f_install inotify-tools           # Do something when a file is created, deleted, or changed
f_install net-tools
f_install openssl
f_install openvpn
f_install bridge-utils
f_install ifupdown
f_install resolvconf
f_install ripmime                 # Process files sent by email
f_install ssh && ufw allow ssh
f_install sysbench
f_install tasksel
f_install unzip
# f_install uuid                  # Use uuidgen instead. It's built-in.
f_install vim
f_install wget
f_install xrdp

ufw allow http
ufw allow https

# Include script footer file
	f_debug_variable "script_footer" "${PATHNAME[script_footer]}"
	source "${PATHNAME[script_footer]}"

exit 0

