#!/bin/bash
# purge-openvpn

# Include header file
PROGRAM_DIRECTORY=$(dirname $0)
source $PROGRAM_DIRECTORY/../script-setup

systemctl stop openvpn@client.service
systemctl stop openvpn@server.service
systemctl disable openvpn@client.service
systemctl disable openvpn@server.service
logger Purging OpenVPN
upd
apt-get -f install
apt-get purge -y openvpn

ufw deny 1194
ufw deny 1900