#!/bin/bash
# setup-os
# PURPOSE: Installs basic software.
# IMPORTANT: Check variables at the top of the script before running it!

######################################################
######### IMPORTANT! #################################
######### Fill in this section carefully, ############
######### copy-and-paste it into Roboform ############
######### BEFORE running install script ##############
MAIN_MAILER_TYPE="'Internet with smarthost'"
RELAYHOST="mail.twc.com" # Spectrum Internet
# RELAYHOST="mail.mchsi.com" # Mediacom Cable Internet
######### END password information ###################
######################################################

install_apache2=true
install_openssl=true
install_php=true
install_certbot=true
install_mailutils=true
install_mysql_server=true
install_phpmyadmin=true
install_plexmediaserver=false # CAUTION: NOT TESTED FOR UBUNTU 20
install_webmin=true
install_zoom=true
install_chrome=true
install_lsyncd=true
install_makemkv=true
install_handbrake=true

echo "#########################################################################"
echo "#########################################################################"
echo "#########################################################################"
echo "Starting setup ...  #####################################################"
echo "#########################################################################"
echo "#########################################################################"

source $(dirname $0)/../script-setup

if [[ $NAME = "Ubuntu" ]]; then
    if [[ $(echo $VERSION_ID | cut -c1-3) = "20." ]]; then
      echo "Ubuntu version 20 confirmed."
    else
      echo "This script does not support version $VERSION_ID of Ubuntu."
      exit 1
    fi
else
  echo "This script works only on Ubuntu."
  exit 1
fi

# Do updates
apt-get update && apt -y dist-upgrade && apt -y clean && apt -y autoremove

if ! [ -x "$(command -v apg)" ]; then
  echo "Installing apg"
  DEBIAN_FRONTEND=noninteractive apt-get install -yq apg
fi

# Install uncomplicated, no-down-side utilities.
$SBIN_DIR/setup/install-utils

# NUMBER_OF_DESIGNATED_PASSWORDS=7
TEMP_PASSWORD_INCLUDE="/tmp/passwords"
echo "" > $TEMP_PASSWORD_INCLUDE
echo "PASSWORD_ME=\"$(apg -c cl_seed -a 1 -m $LENGTH_OF_PASSWORDS -n 1 -E $EXCLUDED_PASSWORD_CHARACTERS)\"" >> $TEMP_PASSWORD_INCLUDE
echo "PASSWORD_UBUNTU=\"$(apg -c cl_seed -a 1 -m $LENGTH_OF_PASSWORDS -n 1 -E $EXCLUDED_PASSWORD_CHARACTERS)\"" >> $TEMP_PASSWORD_INCLUDE
echo "MYSQL_ROOT_PASSWORD=\"$(apg -c cl_seed -a 1 -m $MAX_MYSQL_PASSWORD_LENGTH -n 1 -E $EXCLUDED_PASSWORD_CHARACTERS)\"" >> $TEMP_PASSWORD_INCLUDE
echo "MYSQL_ADMIN_PASSWORD=\"$(apg -c cl_seed -a 1 -m $MAX_MYSQL_PASSWORD_LENGTH -n 1 -E $EXCLUDED_PASSWORD_CHARACTERS)\"" >> $TEMP_PASSWORD_INCLUDE
echo "PHPMYADMIN_APP_PASS=\"$(apg -c cl_seed -a 1 -m $LENGTH_OF_PASSWORDS -n 1 -E $EXCLUDED_PASSWORD_CHARACTERS)\"" >> $TEMP_PASSWORD_INCLUDE
echo "PHPMYADMIN_ROOT_PASS=\"$(apg -c cl_seed -a 1 -m $LENGTH_OF_PASSWORDS -n 1 -E $EXCLUDED_PASSWORD_CHARACTERS)\"" >> $TEMP_PASSWORD_INCLUDE
echo "PHPMYADMIN_APP_DB_PASS=\"$(apg -c cl_seed -a 1 -m $LENGTH_OF_PASSWORDS -n 1 -E $EXCLUDED_PASSWORD_CHARACTERS)\"" >> $TEMP_PASSWORD_INCLUDE
echo "" >> $TEMP_PASSWORD_INCLUDE

chown root:root $TEMP_PASSWORD_INCLUDE
chmod 500 $TEMP_PASSWORD_INCLUDE
source $TEMP_PASSWORD_INCLUDE

# Update hostname
echo "Updating hostname"
hostnamectl set-hostname $HOST_NAME
echo $HOST_NAME > /etc/hostname
chmod 644 /etc/hostname
chown root:root /etc/hostname

# Install ssh
apt-get update
DEBIAN_FRONTEND=noninteractive apt-get install -yq ufw ssh
ufw allow ssh

# Make $USER_ME and $USER_UBUNTU users and give them sudo access and ssh access
echo "Making $USER_ME and $USER_UBUNTU users and give them sudo access and ssh access"
# useradd $USER_ME
# useradd $USER_UBUNTU
# TWO PROBLEMS WITH THE COMMANDS BELOW: The --stdin flag doesn't work in this version of Linux, and my password is going to be dropped anyway.
# echo $PASSWORD_ME | passwd --stdin $USER_ME
# echo $PASSWORD_UBUNTU | passwd --stdin $USER_UBUNTU
usermod -aG sudo $USER_ME
# usermod -aG sudo $USER_UBUNTU
sudo $USER_ME ssh-keygen -C "$SSH_KEY_NAME" -P "" -q -f "$HOME_ME/.ssh/id_rsa"
#   echo "# $SSH_KEY_NAME" >> $GO_CONFIGS/ssh/home-.ssh-authorized_keys
#   # This section is a good idea, but the flaw is that writing to the local $GO_CONFIGS file doesn't sync it back up to the master.
#   cat $HOME_ME/.ssh/id_rsa.pub >> $GO_CONFIGS/ssh/home-.ssh-authorized_keys
#   echo "" >> $GO_CONFIGS/ssh/home-.ssh-authorized_keys
#   echo "#" >> $GO_CONFIGS/ssh/home-.ssh-authorized_keys

echo Configure sudo $USER_ME and $USER_UBUNTU as sudo users
echo "$USER_ME ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/lane-NOPASSWD-users
echo "$USER_UBUNTU ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers.d/lane-NOPASSWD-users
echo Removing passwords for $USER_ME and $USER_UBUNTU
chmod 440 /etc/sudoers.d/lane-NOPASSWD-users
# Not sure I want to drop my password. Still don't need it for ssh. 6/1/2020
# passwd -d $USER_ME
# This probably will fail, and that's fine.'
# passwd -d $USER_UBUNTU
echo "Passwords removed for $USER_ME and $USER_UBUNTU"
echo "Or not"

# Add custom application definitions for ufw
echo "Adding custom application definitions for ufw"
cp $GO_CONFIGS/lane-applications /etc/ufw/applications.d/
chown root:root /etc/ufw/applications.d/lane-applications
chmod 644 /etc/ufw/applications.d/lane-applications
ufw app update lane-applications
echo "Special LANE applications installed to ufw."

# Install MakeMKV
# DON'T USE THE SNAP INSTALLER
if $install_makemkv ; then
  echo "Installing MakeMKV"
  add-apt-repository ppa:heyarje/makemkv-beta
  apt-get update
  DEBIAN_FRONTEND=noninteractive apt-get install -yq makemkv-bin makemkv-oss ccextractor
  usermod -a -G cdrom $USER_ME
  echo "MakeMKV installed."
  fi

if $install_apache2 ; then
  echo "Installing apache2"
  DEBIAN_FRONTEND=noninteractive apt-get install -yq apache2 apache2-doc apache2-suexec-pristine
  ufw allow 'Apache'
  ufw allow 'Apache Full'
  ufw allow http
  ufw allow https
  a2enmod ssl rewrite
  systemctl restart apache2
  echo "apache2 installed."
  fi

# Install Google Chrome
DEBIAN_FRONTEND=noninteractive apt-get install -yq wget gdebi-core
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
gdebi --n google-chrome-stable_current_amd64.deb
rm ./google-chrome-stable_current_amd64.deb

if $install_openssl ; then
  echo "Installing openssl"
  OPENSSL_PACKAGES="openssl libcurl4-openssl-dev libssl-dev libcurl4-doc"
  OPENSSL_PACKAGES="$OPENSSL_PACKAGES libidn11-dev libkrb5-dev libldap2-dev "
  OPENSSL_PACKAGES="$OPENSSL_PACKAGES librtmp-dev libssh2-1-dev zlib1g-dev libssl-doc"
  DEBIAN_FRONTEND=noninteractive apt-get install -yq $OPENSSL_PACKAGES 
  echo "openssl installed."
  fi

if $install_php ; then
  echo "Installing php"
  PHP_PACKAGES="php libapache2-mod-php php-mysql php-gd php-curl php-imap php-ldap"
  PHP_PACKAGES="$PHP_PACKAGES libmcrypt-dev php-mbstring php-dev php-pear"
  PHP_PACKAGES="$PHP_PACKAGES libc-client2007e mlock php-curl php-imap uw-mailutils"
  DEBIAN_FRONTEND=noninteractive apt-get install -yq $PHP_PACKAGES
  phpenmod gd curl imap ldap mbstring
  systemctl restart apache2
  echo "php installed."
  fi

if $enable_certbot ; then
  echo "Installing certbot"
  apt install -y certbot python3-certbot-apache
  echo "certbot installed."
  fi

if $install_mailutils ; then
  echo "installing mailutils"
  debconf-set-selections <<< "postfix postfix/relayhost $RELAYHOST"
  debconf-set-selections <<< "postfix postfix/mailname string $MAILNAME"
  debconf-set-selections <<< "postfix postfix/main_mailer_type string $MAIN_MAILER_TYPE"
  apt-get install -y mailutils
  ufw allow mail
  echo "mailutils installed."
  fi
  
if $install_mysql_server ; then
  echo "Installing mysql server"
###### EXTREMELY IMPORTANT: Edit /etc/mysql/mysql.conf.d/mysqld.cnf and open up bind-address * ###########
  MYSQL_PACKAGES="mysql-server openssl libcurl4-openssl-dev libssl-dev php-gmp php-symfony-service-implementation php-imagick php-twig-doc php-symfony-translation"
  DEBIAN_FRONTEND=noninteractive apt-get install -yq $MYSQL_PACKAGES
  ufw allow mysql
  mysqladmin -u root password "$MYSQL_ROOT_PASSWORD"
  mysql -u root -p"$MYSQL_ROOT_PASSWORD" -e "DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')"
  mysql -u root -p"$MYSQL_ROOT_PASSWORD" -e "DELETE FROM mysql.user WHERE User=''"
  mysql -u root -p"$MYSQL_ROOT_PASSWORD" -e "DELETE FROM mysql.db WHERE Db='test' OR Db='test_%'"
  mysql -u root -p"$MYSQL_ROOT_PASSWORD" -e "CREATE USER '$MYSQL_ADMIN_NAME'@'localhost' IDENTIFIED WITH caching_sha2_password BY '$MYSQL_ADMIN_PASSWORD'"
  mysql -u root -p"$MYSQL_ROOT_PASSWORD" -e "GRANT ALL PRIVILEGES ON *.* TO '$MYSQL_ADMIN_NAME'@localhost WITH GRANT OPTION"
  mysql -u root -p"$MYSQL_ROOT_PASSWORD" -e "FLUSH PRIVILEGES"
  mkdir -p $MYSQL_CLIENT_CERTS_DIR
  cp "$MYSQL_SERVER_BIN_DIR/ca.pem" "$MYSQL_CLIENT_CERTS_DIR/$HOST_NAME-MySQL-ca.pem"
  cp "$MYSQL_SERVER_BIN_DIR/client-cert.pem" "$MYSQL_CLIENT_CERTS_DIR/$HOST_NAME-MySQL-client-cert.pem"
  cp "$MYSQL_SERVER_BIN_DIR/client-key.pem" "$MYSQL_CLIENT_CERTS_DIR/$HOST_NAME-MySQL-client-key.pem"
  chown -R $USER_ME:$USER_ME "$MYSQL_CLIENT_CERTS_DIR"
  # Install .my.cnf in home directory
    backup-file $HOME_ME/.my.cnf
    cp $GO_CONFIGS/mysql/home_directory_.my.cnf $HOME_ME/.my.cnf
    replace-in-file "$HOME_ME/.my.cnf" "UserValue" "$MYSQL_ADMIN_NAME"
    replace-in-file "$HOME_ME/.my.cnf" "PasswordValue" "$MYSQL_ADMIN_PASSWORD"
    chown $USER_ME:$USER_ME "$HOME_ME/.my.cnf*"
    chmod 600 "$HOME_ME/.my.cnf*"
  # Install .my.cnf for root user
    backup-file /root/.my.cnf
    cp $GO_CONFIGS/mysql/home_directory_.my.cnf /root/.my.cnf
    replace-in-file "root/.my.cnf" "UserValue" "$MYSQL_ADMIN_NAME"
    replace-in-file "root/.my.cnf" "PasswordValue" "$MYSQL_ADMIN_PASSWORD"
    chown root:root "/root/.my.cnf*"
    chmod 600 "root/.my.cnf*"
  echo "MySQL server installed."
  fi

# phpMyAdmin should be installed AFTER php and MySQL
if $install_phpmyadmin ; then
  echo "Installing phpMyAdmin"
  # Based on https://www.digitalocean.com/community/tutorials/how-to-install-and-secure-phpmyadmin-on-ubuntu-20-04
  debconf-set-selections <<< "phpmyadmin phpmyadmin/reconfigure-webserver multiselect apache2"
  debconf-set-selections <<< "phpmyadmin phpmyadmin/dbconfig-install boolean true"
  debconf-set-selections <<< "phpmyadmin phpmyadmin/app-password-confirm password $PHPMYADMIN_APP_PASS"
  debconf-set-selections <<< "phpmyadmin phpmyadmin/mysql/admin-pass password $PHPMYADMIN_ROOT_PASS"
  debconf-set-selections <<< "phpmyadmin phpmyadmin/mysql/app-pass password $PHPMYADMIN_APP_DB_PASS"
  apt install -y phpmyadmin php-mbstring php-zip php-gd php-json php-curl
  phpenmod mbstring
  cp $GO_CONFIGS/phpmyadmin.config.inc.php $PHPMYADMIN_DIR/config.inc.php
  chown -R www-data:www-data $PHPMYADMIN_DIR
  chmod 644 $PHPMYADMIN_DIR/config.inc.php
#  cp $GO_CONFIGS/html/.htaccess.html.www.var $THIS_WEB_ROOT/.htaccess
#  chown -R www-data:www-data $THIS_WEB_ROOT/.htaccess
#  chmod 644 $THIS_WEB_ROOT/.htaccess
  systemctl restart apache2
  echo "phpMyAdmin installed."
  fi

if $install_plexmediaserver ; then
# CAUTION: NOT TESTED FOR UBUNTU 20
# NOTE: As of 8/20/2020, it is difficult to impossible to automate this because the name 
# of the latest/current release cannot be anticipated. See instructions 
# at https://www.plex.tv/media-server-downloads/ 
# and https://support.plex.tv/articles/200288586-installation/.
# Copy the deb file to /home/lhensley, and run
#   sudo dpkg -i ./plexmediaserver*deb
#   sudo ufw allow plexmediaserver
#   sudo usermod -a -G plex lhensley
#   sudo mkdir /var/lib/plexmediaserver/Library/work
#   sudo mkdir /var/lib/plexmediaserver/Library/store
#   sudo chown plex:plex /var/lib/plexmediaserver/Library/*
# Mount the drives and add the libraries.
# Browse to http://<server>:32400/web
# Ubuntu 18 instructions below:
  echo "Installing Plex Media Server"
  rm /etc/apt/sources.list.d/plexmediaserver.list
  deb https://downloads.plex.tv/repo/deb public main | tee /etc/apt/sources.list.d/plexmediaserver.list
  curl https://downloads.plex.tv/plex-keys/PlexSign.key | apt-key add -
  apt update
  apt install plexmediaserver
  ufw allow plexmediaserver
  echo "Plex Media Server installed."
  # Install Tautulli for https://this-server:8181
  See https://tautulli.com/
  DEBIAN_FRONTEND=noninteractive apt-get install -yq python python-setuptools tzdata
  cd /opt
  git clone https://github.com/Tautulli/Tautulli.git
  addgroup tautulli && sudo adduser --system --no-create-home tautulli --ingroup tautulli
  chown tautulli:tautulli -R /opt/Tautulli
  systemctl daemon-reload
  systemctl enable tautulli.service
  systemctl start tautulli.service
  ufw allow 8181
  cd
  fi

if $install_webmin ; then
  echo "Installing Webmin"
  wget http://www.webmin.com/download/deb/webmin-current.deb
  WEBMIN_PACKAGES="openssl libcurl4-openssl-dev libssl-dev perl libnet-ssleay-perl libauthen-pam-perl"
  WEBMIN_PACKAGES="$WEBMIN_PACKAGES libnet-ssleay-perl libauthen-pam-perl libpam-runtime"
  WEBMIN_PACKAGES="$WEBMIN_PACKAGES libio-pty-perl apt-show-versions python libsocket6-perl"
  DEBIAN_FRONTEND=noninteractive apt-get install -yq $WEBMIN_PACKAGES
  dpkg --install webmin-current.deb
  rm webmin-current.deb
  ufw allow webmin
  echo "Webmin installed."
  fi

# Install Zoom Client
if $install_zoom ; then
  echo "Installing Zoom Client"
  wget https://zoom.us/client/latest/zoom_amd64.deb
  DEBIAN_FRONTEND=noninteractive apt-get install -yq ./zoom_amd64.deb
  rm ./zoom_amd64.deb
  echo "Zoom Client installed."
  fi

# Install Google Chrome
if $install_chrome ; then
  echo "Installing Google Chrome"
  DEBIAN_FRONTEND=noninteractive apt-get install -yq gdebi-core
  wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  gdebi --n google-chrome-stable_current_amd64.deb
  rm ./google-chrome-stable_current_amd64.deb
  echo "Google Chrome installed."
  fi

# Install lsyncd
if $install_lsyncd ; then
  echo "Installing lsyncd"
  DEBIAN_FRONTEND=noninteractive apt-get install -yq lsyncd rsync
  mkdir -p /etc/lsyncd
  mkdir -p /var/log/lsyncd
  systemctl start lsyncd
  systemctl enable lsyncd
  echo "lsyncd installed."
  fi

# Set up some cron jobs
echo "Adding cronjobs"
crontab -l > $TEMP_CRON
if grep -Fxq "ddclient" $TEMP_CRON
then
    unlink $TEMP_CRON
else
    echo "@reboot /usr/sbin/ddclient -daemon $DDCLIENT_INTERVAL -syslog #Updates dyndns.org" >> $TEMP_CRON
    echo "@reboot echo \"$(hostname) booted\" | mail $LANE_CELL #Bootup Notification" >> $TEMP_CRON
    echo "59 23 * * * $SBIN_DIR/secureserver #Secure Server" >> $TEMP_CRON
    crontab $TEMP_CRON
    unlink $TEMP_CRON
fi

if $install_handbrake ; then
  echo "Installing HandBrake"
  add-apt-repository -y ppa:stebbins/handbrake-releases
  apt-get update
  DEBIAN_FRONTEND=noninteractive apt-get install -yq handbrake-gtk handbrake-cli
  echo "HandBrake installed."
  echo "GUI version is NOT configured: Presets ($HOME_DIR/.HandBrake/*) need to be added."
  fi

# Invoke /usr/local/sbin/_apply-configs
# chmod 777 $SBIN_DIR/_apply-configsHOME
$SBIN_DIR/_apply-configs

KEYS_FILE=$HOME_DIR/os-security-info.txt
echo "MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD" > $KEYS_FILE
echo "MYSQL_ADMIN_NAME: $MYSQL_ADMIN_NAME" >> $KEYS_FILE
echo "MYSQL_ADMIN_PASSWORD: $MYSQL_ADMIN_PASSWORD" >> $KEYS_FILE
echo "PHPMYADMIN_APP_PASS: $PHPMYADMIN_APP_PASS" >> $KEYS_FILE
echo "PHPMYADMIN_ROOT_PASS: $PHPMYADMIN_ROOT_PASS" >> $KEYS_FILE
echo "PHPMYADMIN_APP_DB_PASS: $PHPMYADMIN_APP_DB_PASS" >> $KEYS_FILE
echo "" >> $KEYS_FILE
echo "# Add to $GO_CONFIGS/ssh/home-.ssh-authorized_keys:" >> $KEYS_FILE
echo "" >> $KEYS_FILE
echo "# $SSH_KEY_NAME" >> $KEYS_FILE
cat "$HOME_ME/.ssh/id_rsa.pub" >> $KEYS_FILE
echo "#" >> $KEYS_FILE
chmod 400 $KEYS_FILE
chown $USER_ME:$USER_ME $KEYS_FILE
echo ""
echo "# IMPORTANT: Move the contents of $KEYS_FILE into 1Password NOW, delete it, and reboot."
echo "# Once you continue, these passwords cannot be recovered."
echo ""
rm $TEMP_PASSWORD_INCLUDE

source $(dirname $0)/../script-footer
echo "Done."
exit 0
