#!/bin/bash
# install-openvswitch
# Based on https://docs.openvswitch.org/en/latest/intro/install/distributions/#debian-ubuntu
# Assumes Ubuntu 22.04
# Open vSwitch is a multilayer software switch 
#   licensed under the open source Apache 2 license. 
#   Our goal is to implement a production quality switch platform 
#   that supports standard management interfaces 
#   and opens the forwarding functions to programmatic extension and control.
# If this isn't installed, running "sudo netplan apply"
#   will throw this error and abort:
#     WARNING:root:Cannot call Open vSwitch: ovsdb-server.service is not running.
#   Supposedly, this was fixed in May 2023.
#   But in practice, it seems to persist (as of Dec. 16, 2023) -LH


# Include script setup file
	source script-setup
	if [ ! $FUNCTIONS_ARE_DEFINED ]; then echo $0: Functions not defined. Aborting; logger $0: Functions not defined. Aborting; exit 1; fi
	if [ ! $VARIABLES_ARE_DEFINED ]; then echo $0: Variables not defined. Aborting; logger $0: Variables not defined. Aborting; exit 1; fi

# Require root
	f_require_root

# Some error checking that would help:
	# Confirm that debconf-set-selections with
		# sudo dpkg-query -S /usr/bin/debconf-set-selections

# Install
	# To restart relevant services automatically without prompting the user
		sed -i 's/#$nrconf{restart} = '"'"'i'"'"';/$nrconf{restart} = '"'"'a'"'"';/g' /etc/needrestart/needrestart.conf
	# Update existing Debian packages
		apt-get-update-if-needed
	# Install main package
		apt install openvswitch-switch openvswitch-common

# Include script footer file
	f_debug_variable "script_footer" "${PATHNAME[script_footer]}"
	source "${PATHNAME[script_footer]}"

exit 0

