#!/bin/bash

if [[ $EUID -ne 0 ]]; then
	# echo "You are not using root credentials."
	echo "Root privileges required."
	exit 1
	fi

function f_pause () {
  read -s -n 1 -p "Press any key to continue . . .\n"
}

echo
echo apt-get -y update && sudo apt-get -y dist-upgrade
apt-get -y update && sudo apt-get -y dist-upgrade

echo
echo apt-get -y --install-recommends --install-suggests install '\'
echo "   " coreutils git-all gpg moreutils curl '\'
echo "   " openssh-client openssh-server ufw util-linux
apt-get -y --install-recommends --install-suggests install \
	coreutils git-all gpg moreutils curl \
	openssh-client openssh-server ufw util-linux
systemctl enable --now ssh

exit 0

at certbot coreutils curl fail2ban git-all gpg gzip mailutils moreutils openssl php python3 rsync unzip vim webmin

sudo apt-get -y --install-recommends --install-suggests install at certbot coreutils curl fail2ban git-all gpg gzip mailutils moreutils openssl php python3 rsync unzip vim


# curl -L -o ~/go https://raw.githubusercontent.com/lhensley/ubuntu-tools/master/install/go


echo
echo curl -L -O https://github.com/lhensley/ubuntu-tools/raw/master/install/clean-setup
# wget --no-cache -O clean-setup https://github.com/lhensley/ubuntu-tools/raw/master/install/clean-setup
curl -L -O https://github.com/lhensley/ubuntu-tools/raw/master/install/clean-setup

echo
echo curl -L -O https://github.com/lhensley/ubuntu-tools/raw/master/install/variables
# wget --no-cache -O variables https://github.com/lhensley/ubuntu-tools/raw/master/install/variables
curl -L -O https://github.com/lhensley/ubuntu-tools/raw/master/install/variables

echo
echo gpg -d -o seeds.tar.gz seeds.tar.gz.gpg
echo Password is in 1Password at '"'Seed File for Ubuntu Installation'"'.
f_pause
gpg -d -o seeds.tar.gz seeds.tar.gz.gpg # Password in 1Password; search "seed"

echo
echo chmod 600 seeds.tar.gz
chmod 600 seeds.tar.gz

echo
echo tar -xvzf ./seeds.tar.gz
tar -xvzf ./seeds.tar.gz

echo
echo "chmod 700 ./clean-setup"
chmod 700 ./clean-setup

echo
echo chown -R $SUDO_USER:$SUDO_USER ./*
chown -R $SUDO_USER:$SUDO_USER ./*

echo
echo Next step: run sudo ./clean-setup
echo '('I would do it for you, but you may not want me to.')'
echo

exit 0
