#!/bin/bash

# Include script setup file
	source script-setup
	if [ ! $FUNCTIONS_ARE_DEFINED ]; then echo $0: Functions not defined. Aborting; logger $0: Functions not defined. Aborting; exit 1; fi
	if [ ! $VARIABLES_ARE_DEFINED ]; then echo $0: Variables not defined. Aborting; logger $0: Variables not defined. Aborting; exit 1; fi

# Define file locations
	SOURCE_ROOT_DIR="$VIDEO_WORK_DIRECTORY"
	TARGET_ROOT_DIR="$VIDEO_STORE_DIRECTORY"
	MOVE_MASK="*.m4v"
	THIS_SCRIPT=$(basename "$0")

# Do the work
#    sudo -u $ADMIN_USER \
		rsync --remove-source-files --include $MOVE_MASK --exclude ".grab/" --exclude "*.ts" \
			--archive --links --owner --perms --times --verbose \
			"$SOURCE_ROOT_DIR" "$TARGET_ROOT_DIR" \
			| logger -t "$THIS_SCRIPT"

# Include script footer file
	f_debug_variable "script_footer" "${PATHNAME[script_footer]}"
	source "${PATHNAME[script_footer]}"

exit 0
