#!/bin/bash

# Include script setup file
	source script-setup
	if [ ! $FUNCTIONS_ARE_DEFINED ]; then echo $0: Functions not defined. Aborting; logger $0: Functions not defined. Aborting; exit 1; fi
	if [ ! $VARIABLES_ARE_DEFINED ]; then echo $0: Variables not defined. Aborting; logger $0: Variables not defined. Aborting; exit 1; fi

# "Run as a service" check
	if [ "$PPID" != "1" ]; then
		f_die "This script only runs as a systemd service. Try sudo systemctl start $(basename $0)" false
		fi
	SERVICE_FLAG=true;

# Only allow this to run on server oz.
	f_only_on_server "oz"

# Do the looping work
	THIS_SCRIPT=$(basename "$0")
	while true; do
		# Define file locations
			SOURCE_ROOT_DIR="/mnt/ext10tb01/plex/dvr-oz"
			TARGET_ROOT_DIR="/mnt/12TBB/Plex/Pool06-1TB/dvr-pd1"
			TARGET_SERVER="pd1.lanehensley.org"
			WAIT_AFTER_SOURCE_SCAN="6h"
			MOVE_MASK="*.m4v"
			EXCLUDE_MASK1="*.ts"
			EXCLUDE_MASK2=".*"
			EXCLUDE_MASK3=".grab/"
		# See https://github.com/$GITHUB_USER/ubuntu-tools/blob/master/documentation/rsync%20options.md
#        sudo -u $ADMIN_USER \
			rsync --remove-source-files --include "$MOVE_MASK" \
			--exclude "$EXCLUDE_MASK1" --exclude "$EXCLUDE_MASK2" \
			--exclude "$EXCLUDE_MASK3" -aloprtv \
			"$SOURCE_ROOT_DIR"/* "$TARGET_SERVER:$TARGET_ROOT_DIR" \
			| logger -t "$THIS_SCRIPT"
		f_log_and_echo "Sleeping $WAIT_AFTER_SOURCE_SCAN." false
		sleep "$WAIT_AFTER_SOURCE_SCAN"
        done

# Include script footer file
	f_debug_variable "script_footer" "${PATHNAME[script_footer]}"
	source "${PATHNAME[script_footer]}"

exit 0

