#!/bin/bash

# Include script setup file
	source script-setup
	if [ ! $FUNCTIONS_ARE_DEFINED ]; then echo $0: Functions not defined. Aborting; logger $0: Functions not defined. Aborting; exit 1; fi
	if [ ! $VARIABLES_ARE_DEFINED ]; then echo $0: Variables not defined. Aborting; logger $0: Variables not defined. Aborting; exit 1; fi

# Require root
	f_require_root

f_require_config "plex.backup.app.support"
f_require_config "plex.live.app.support"
f_require_directory "${LANE_CONFIG[plex.live.app.support]}"

systemctl stop plexmediaserver
mkdir -p ${LANE_CONFIG[plex.backup.app.support]}
f_require_directory "plex.backup.app.support"
cp -R "${LANE_CONFIG[plex.live.app.support]}"/* "${LANE_CONFIG[plex.backup.app.support]}"/
systemctl start plexmediaserver

# Include script footer file
	f_debug_variable "script_footer" "${PATHNAME[script_footer]}"
	source "${PATHNAME[script_footer]}"

exit 0
