#!/bin/bash
# tv-show-filter-status
# Usage: tv-show-filter-status <input_file>
# Returns 0 = Not filtered (i.e., file does not match filter pattern)
# Returns 1 = Filtered (i.e., file matches filter pattern)

logger "$0 started for $1"

if [[ "$1" != *"ABC World News Tonight"* ]] \
    && [[ "$1" != *"BBC World News"* ]] \
    && [[ "$1" != *"CBS Evening News"* ]] \
    && [[ "$1" != *"CBS Morning News"* ]] \
    && [[ "$1" != *"CBS This Morning"* ]] \
    && [[ "$1" != *"CBS Weekend News"* ]] \
    && [[ "$1" != *"Face the Nation"* ]] \
    && [[ "$1" != *"Jimmy Kimmel Life"* ]] \
    && [[ "$1" != *"KXAN News"* ]] \
    && [[ "$1" != *"Meet the Press"* ]] \
    && [[ "$1" != *"NBC Nightly News"* ]] \
    && [[ "$1" != *"Sunday Today"* ]] \
    && [[ "$1" != *"The Late Show"* ]] \
    && [[ "$1" != *"The Tonight Show"* ]] \
    && [[ "$1" != *"Today (195"* ]] \
    && [[ "$1" != *".grab"* ]]; then
#         echo "$(date) $0 Not filtered (Not matched)"
        logger "$0 Not filtered (Not matched) $1"
        exit 0
    fi

# echo "$(date) $0 Filtered (Matched)"
logger "$0 Filtered (Matched) $1"
exit 1
