#!/bin/bash

# Require root
if [[ $EUID -ne 0 ]]; then
  echo "Root privileges required." >&2
  exit 163
  fi

# Copy to MySQL server /var/lib/mysql and set ownership
if [ -d "/var/lib/mysql" ]; then # Execute only if target directory exists
  mkdir -p /home/lhensley/killme1 \
    && cp /home/lhensley/MySQL-Certs/*.pem /home/lhensley/killme1/ \
    && chown mysql:mysql /home/lhensley/killme1/*.pem
  fi

# Copy to mysqladmin configs /etc/phpmyadmin and set ownership
if [ -d "/etc/phpmyadmin" ]; then # Execute only if target directory exists
#  mkdir -p /etc/phpmyadmin/MySQL-Certs/$(hostname) \
#    && cp /home/lhensley/MySQL-Certs/*.pem /etc/phpmyadmin/MySQL-Certs/$(hostname)/ \
#    && chown www-data:www-data /etc/phpmyadmin/MySQL-Certs/$(hostname)/*.pem
  mkdir -p /home/lhensley/killme2 \
    && cp /home/lhensley/MySQL-Certs/*.pem /home/lhensley/killme2/ \
    && chown www-data:www-data /home/lhensley/killme2/*.pem
  fi

# Email certificates to root (Lane)
echo "See attached." | mail -s "$(hostname) MySQL Certificates" \
  -A /home/lhensley/MySQL-Certs/ca-key.pem \
  -A /home/lhensley/MySQL-Certs/ca.pem \
  -A /home/lhensley/MySQL-Certs/client-cert.pem \
  -A /home/lhensley/MySQL-Certs/client-key.pem \
  -A /home/lhensley/MySQL-Certs/client-req.pem \
  -A /home/lhensley/MySQL-Certs/private_key.pem \
  -A /home/lhensley/MySQL-Certs/public_key.pem \
  -A /home/lhensley/MySQL-Certs/server-cert.pem \
  -A /home/lhensley/MySQL-Certs/server-key.pem \
  -A /home/lhensley/MySQL-Certs/server-req.pem \
  root

echo "Done. DON'T FORGET to <rm -r /home/lhensley/MySQL-Certs> as soon as possible!"

exit 0

#################################################################################################
##### Optional Modules (move up to use) #########################################################
#################################################################################################
echo CRITICAL ERROR: The script MUST include an exit 0 command before the optional modules section.
exit 1

# Echo to standard error
echo "This text is being sent to standard error." >&2

# Require root
if [[ $EUID -ne 0 ]]; then
  echo "Root privileges required." >&2
  exit 163
  fi

function f_require_root () {
  # If running with root privileges, do nothing. Otherwise, abort with error.
  if [[ $EUID -ne 0 ]]; then
    # echo "You are not using root credentials."
    f_die "Root privileges required." false $EXIT_CODE_ROOT_REQUIRED
    fi
    }

function f_is_directory {
  # Usage: if $(f_is_directory "directory_name"); then commands_if_true; else commands_if_false; fi
  # $1 = "$string_to_check"
    if [ -d "$1" ]; then echo true; else echo false; fi
    }

function f_is_file {
  # Usage: if $(f_is_file "file_or_path_name"); then commands_if_true; else commands_if_false; fi
  # $1 = "$string_to_check"
    if [ -f "$1" ]; then echo true; else echo false; fi
    }


